### ISSUE TITLE
kiwisolver fail to compile

### ISSUE THREAD

**Issue by vince06fr** [kivy/buildozer#1003]
I try to compile an apk with matplotlib and the matplotlib flower but have an error with kiwisolver

## Application:
```python
from kivy.garden.matplotlib.backend_kivyagg import FigureCanvasKivyAgg
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
import matplotlib.pyplot as plt

plt.plot([1, 23, 2, 4])
plt.ylabel('some numbers')

class MyApp(App):

    def build(self):
        box = BoxLayout()
        box.add_widget(FigureCanvasKivyAgg(plt.gcf()))
        return box

MyApp().run()
```

## Error Log

```python
[INFO]:    Building kiwisolver for armeabi-v7a
[INFO]:    kiwisolver apparently isn't already in site-packages
[INFO]:    Building compiled components in kiwisolver
[INFO]:    -> directory context /home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/kiwisolver-python3/armeabi-v7a__ndk_target_21/kiwisolver
[INFO]:    -> running python setup.py build_ext -v
Exception in thread background thread for pid 5129:                            
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
zip_safe flag not set; analyzing archive contents...
cppy.__pycache__.__init__.cpython-37: module references __file__

Installed /home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/kiwisolver-python3/armeabi-v7a__ndk_target_21/kiwisolver/.eggs/cppy-1.0.2-py3.7.egg
/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '1.2.0.dev' to '1.2.0.dev0'
  normalized_version,
running build_ext
building 'kiwisolver' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/py
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -I/home/vince/.buildozer/android/platform/android-ndk-r17c/platforms/android-27/arch-arm-v7a/usr/include -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fPIC -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/kiwisolver-python3/armeabi-v7a__ndk_target_21/kiwisolver/.eggs/cppy-1.0.2-py3.7.egg/cppy/include -I. -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c py/kiwisolver.cpp -o build/temp.linux-x86_64-3.7/py/kiwisolver.o -std=c++11
py/kiwisolver.cpp: In function 'bool {anonymous}::add_objects(PyObject*)':
py/kiwisolver.cpp:87:56: error: 'pyobject_cast' was not declared in this scope
     cppy::ptr var( pyobject_cast( Variable::TypeObject ) );
                                                        ^
In file included from ./kiwi/constraint.h:13:0,
                 from ./kiwi/kiwi.h:9,
                 from py/kiwisolver.cpp:9:
./kiwi/strength.h: At global scope:
./kiwi/strength.h:30:14: warning: 'kiwi::strength::strong' defined but not used [-Wunused-variable]
 const double strong = create( 1.0, 0.0, 0.0 );
              ^
./kiwi/strength.h:32:14: warning: 'kiwi::strength::medium' defined but not used [-Wunused-variable]
 const double medium = create( 0.0, 1.0, 0.0 );
              ^
./kiwi/strength.h:34:14: warning: 'kiwi::strength::weak' defined but not used [-Wunused-variable]
 const double weak = create( 0.0, 0.0, 1.0 );
              ^
error: command '/usr/bin/ccache' failed with exit status 1


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1192, in <module>
    main()
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 668, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 206, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 577, in build_recipes
    recipe.build_arch(arch)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 893, in build_arch
    self.build_compiled_components(arch)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 948, in build_compiled_components
    super(CppCompiledComponentsPythonRecipe, self).build_compiled_components(arch)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 905, in build_compiled_components
    _env=env, *self.setup_extra_args)
  File "/home/vince/workspace/kivy/mplot/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 180, in shprint
    for line in output:
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/vince/workspace/kivy/venv/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
zip_safe flag not set; analyzing archive contents...
cppy.__pycache__.__init__.cpython-37: module references __file__

Installed /home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/kiwisolver-python3/armeabi-v7a__ndk_target_21/kiwisolver/.eggs/cppy-1.0.2-py3.7.egg
/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '1.2.0.dev' to '1.2.0.dev0'
  normalized_version,
running build_ext
building 'kiwisolver' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/py
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/vince/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -I/home/vince/.buildozer/android/platform/android-ndk-r17c/platforms/android-27/arch-arm-v7a/usr/include -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/vince/.buildozer/android/platform/android-ndk-r17c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fPIC -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/kiwisolver-python3/armeabi-v7a__ndk_target_21/kiwisolver/.eggs/cppy-1.0.2-py3.7.egg/cppy/include -I. -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c py/kiwisolver.cpp -o build/temp.linux-x86_64-3.7/py/kiwisolver.o -std=c++11
py/kiwisolver.cpp: In function 'bool {anonymous}::add_objects(PyObject*)':
py/kiwisolver.cpp:87:56: error: 'pyobject_cast' was not declared in this scope
     cppy::ptr var( pyobject_cast( Variable::TypeObject ) );
                                                        ^
In file included from ./kiwi/constraint.h:13:0,
                 from ./kiwi/kiwi.h:9,
                 from py/kiwisolver.cpp:9:
./kiwi/strength.h: At global scope:
./kiwi/strength.h:30:14: warning: 'kiwi::strength::strong' defined but not used [-Wunused-variable]
 const double strong = create( 1.0, 0.0, 0.0 );
              ^
./kiwi/strength.h:32:14: warning: 'kiwi::strength::medium' defined but not used [-Wunused-variable]
 const double medium = create( 0.0, 1.0, 0.0 );
              ^
./kiwi/strength.h:34:14: warning: 'kiwi::strength::weak' defined but not used [-Wunused-variable]
 const double weak = create( 0.0, 0.0, 1.0 );
              ^
error: command '/usr/bin/ccache' failed with exit status 1


  STDERR:

# Command failed: /home/vince/workspace/kivy/venv/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy,matplotlib,numpy,six --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/vince/workspace/kivy/mplot/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/Tarzan:@/tmp/.ICE-unix/2816,unix/Tarzan:/tmp/.ICE-unix/2816'
#     COLORTERM = 'truecolor'
#     _fzf_orig_completion_tee = 'complete -F %s tee #_longopt'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     _fzf_orig_completion_rm = 'complete -F %s rm #_longopt'
#     _fzf_orig_completion_rmdir = 'complete -F %s rmdir #_longopt'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     GTK_IM_MODULE = 'ibus'
#     _fzf_orig_completion_uniq = 'complete -F %s uniq #_longopt'
#     QT4_IM_MODULE = 'ibus'
#     _fzf_orig_completion_ftp = 'complete -F %s ftp #_known_hosts'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     SSH_AUTH_SOCK = '/run/user/1001/keyring/ssh'
#     _fzf_orig_completion_tail = 'complete -F %s tail #_longopt'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     SSH_AGENT_PID = '2736'
#     GTK_MODULES = 'gail:atk-bridge'
#     DBUS_STARTER_BUS_TYPE = 'session'
#     _fzf_orig_completion_mv = 'complete -F %s mv #_longopt'
#     PWD = '/home/vince/workspace/kivy/mplot'
#     LOGNAME = 'vince'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_SESSION_TYPE = 'x11'
#     GPG_AGENT_INFO = '/run/user/1001/gnupg/S.gpg-agent:0:1'
#     XAUTHORITY = '/run/user/1001/gdm/Xauthority'
#     WINDOWPATH = '2'
#     _fzf_orig_completion_diff = 'complete -F %s diff #_longopt'
#     HOME = '/home/vince'
#     USERNAME = 'vince'
#     IM_CONFIG_PHASE = '1'
#     LANG = 'fr_FR.UTF-8'
#     _fzf_orig_completion_awk = 'complete -F %s awk #_longopt'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     _fzf_orig_completion_telnet = 'complete -F %s telnet #_known_hosts'
#     VIRTUAL_ENV = '/home/vince/workspace/kivy/venv'
#     VTE_VERSION = '5802'
#     _fzf_orig_completion_grep = 'complete -F %s grep #_longopt'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/1e0d4e19_5f05_46f1_a370_2b63d1e7ab7c'
#     INVOCATION_ID = 'd93117f18c0d46c9a8cb8c25ad68d54f'
#     _fzf_orig_completion_python = 'complete -F %s python #_python'
#     MANAGERPID = '2618'
#     CLUTTER_IM_MODULE = 'ibus'
#     _fzf_orig_completion_du = 'complete -F %s du #_longopt'
#     _fzf_orig_completion_sort = 'complete -F %s sort #_longopt'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     _fzf_orig_completion_cat = 'complete -F %s cat #_longopt'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     _fzf_orig_completion_ln = 'complete -F %s ln #_longopt'
#     LIBVIRT_DEFAULT_URI = 'qemu:///system'
#     USER = 'vince'
#     _fzf_orig_completion_ld = 'complete -F %s ld #_longopt'
#     _fzf_orig_completion_ls = 'complete -F %s ls #_longopt'
#     GNOME_TERMINAL_SERVICE = ':1.97'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     QT_IM_MODULE = 'ibus'
#     _fzf_orig_completion_pushd = 'complete -o nospace -F %s pushd #_cd'
#     DBUS_STARTER_ADDRESS = 'unix:path=/run/user/1001/bus,guid=735cb5fd24e287369ad2b8f45df9cd95'
#     _fzf_orig_completion_vim = 'complete -F %s vim #_filedir_xspec'
#     XDG_RUNTIME_DIR = '/run/user/1001'
#     PS1 = ('(venv) \\[\\e]0;\\u@\\h: '
 '\\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ')
#     _fzf_orig_completion_cd = 'complete -o nospace -F %s cd #_cd'
#     JOURNAL_STREAM = '9:44535'
#     _fzf_orig_completion_less = 'complete -F %s less #_longopt'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     _fzf_orig_completion_cp = 'complete -F %s cp #_longopt'
#     PATH = '/home/vince/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/vince/workspace/kivy/venv/bin:/home/vince/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/var/lib/snapd/snap/bin:/home/vince/.local/bin/:/home/vince/.fzf/bin'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1001/bus,guid=735cb5fd24e287369ad2b8f45df9cd95'
#     _fzf_orig_completion_sed = 'complete -F %s sed #_longopt'
#     _fzf_orig_completion_head = 'complete -F %s head #_longopt'
#     _fzf_orig_completion_wc = 'complete -F %s wc #_longopt'
#     _ = '/home/vince/workspace/kivy/venv/bin/buildozer'
#     OLDPWD = '/home/vince/workspace/kivy'
#     PACKAGES_PATH = '/home/vince/.buildozer/android/packages'
#     ANDROIDSDK = '/home/vince/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/vince/.buildozer/android/platform/android-ndk-r17c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
```

## buidspec
```python
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,matplotlib

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
garden_requirements = matplotlib

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
android.accept_sdk_license = True

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

Thanks for helping

**Comment by MBM1607** [comment]
I have the exact same problem. Did you find any solution or something?

**Comment by Sahil-pixel** [comment]
I have same problem .. please help..

**Comment by KoenBaak** [comment]
Same problem here as well

**Comment by aydindemircioglu** [comment]
me too :/

**Comment by vince06fr** [comment]
I have trying your fix, the problem persists

**Comment by xape4ka** [comment]
> me too :/
> i now added
> 
> #define pyobject_cast( o ) ( reinterpret_cast<PyObject*>( o ) )
> #define void_cast( o ) ( reinterpret_cast<void*>( o ) )
> #define pytype_cast( o ) ( reinterpret_cast<PyTypeObject*>( o ) )
> 
> to kiwi.h, somewhere hear .buildozer/android/platform/build-armeabi-v7a/build/other_builds/kiwisolver-python3/armeabi-v7a__ndk_target_21/kiwisolver/kiwi/kiwi.h

I had the same problem, but this edit kiwi.h work for me. Thx

**Comment by marcets** [comment]
To apply the aydindemircioglu fix. I have install "apt install python3-openssl" in my case.
Hope it will help someone.

**Comment by AndreMiras** [comment]
I believe this was fixed with the recent `wikisolver` recipe update https://github.com/kivy/python-for-android/pull/2075
Otherwise feel free to update
