### ISSUE TITLE
Error with pillow in android with error 

### ISSUE THREAD

**Issue by oukiar** [kivy/buildozer#1020]
### Versions

* Python: 3.7.1
* OS: ubuntu 18.04.3, ubuntu 19.04
* Buildozer: develop

### Description

Compiling projects that are using the pillow repository crash the android app when try to import the pillow module.

The problem appears in a fresh installs of ubuntu 18.04.3 and 19.04, and the specific error is related to _imaging.so cannot found fmod symbol, thats related to math module. I found the tip here https://github.com/termux/termux-packages/issues/2722

The apk compiles fine but crash at starting the app, the workaround was add the " -lm" to cflags in the recipe for pillow in the python-for-android recipes .

### buildozer.spec
```
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = Myapp

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = com.github.oukiar

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests, bin, atlas, .git, screenshots

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.98.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3, pyjnius, beautifulsoup4, requests, bcrypt, pyasn1, cryptography, pycrypto, ecdsa, paramiko==2.1.6, sqlite3, plyer, pillow, libiconv, pathlib, libzbar, pyzbar==0.1.8, git+https://gitlab.com/kivymd/kivymd.git, openssl, kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =
garden_requirements = xcamera

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png
presplash.filename = %(source.dir)s/splashscreen.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png
icon.filename = %(source.dir)s/monstruola_icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET
android.permissions = VIBRATE, INTERNET, CAMERA, WRITE_EXTERNAL_STORAGE, WAKE_LOCK, ACCESS_NETWORK_STATE

# (int) Target Android API, should be as high as possible.
#android.api = 26

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
android.wakelock = True

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

### Logs

```
I/python  (30797):  Traceback (most recent call last):
I/python  (30797):    File "/home/oscar/monstruolapp/.buildozer/android/app/main.py", line 34, in <module>
I/python  (30797):    File "/home/oscar/monstruolapp/.buildozer/android/app/zbarcam/__init__.py", line 1, in <module>
I/python  (30797):    File "/home/oscar/monstruolapp/.buildozer/android/app/zbarcam/zbarcam.py", line 11, in <module>
I/python  (30797):    File "/home/oscar/monstruolapp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/monstruolapp/PIL/ImageOps.py", line 20, in <module>
I/python  (30797):    File "/home/oscar/monstruolapp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/monstruolapp/PIL/Image.py", line 64, in <module>
I/python  (30797):  ImportError: dlopen failed: cannot locate symbol "fmod" referenced by "_imaging.so"...
I/python  (30797): Python for android ended.
```

**Comment by oukiar** [comment]
If it helps to someone else the specific file to solve this issue is:
.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/__init__.py

and you must changle the line
            env['CFLAGS'] += cflags
to this new line with the math flag:
            env['CFLAGS'] += cflags + " -lm"

clean the python-for-android and rebuild.
buildozer android clean
buildozer android debug

If this is helpful and seems correct, i can do the pull request.

**Comment by MIDFlELDER** [comment]
i had the same problem here working with polliw 
I/python  (22708):    File "/home/mehdi/test/.buildozer/android/app/main.py", line 8, in <module>
I/python  (22708):    File "/home/mehdi/test/.buildozer/android/app/dbmanager.py", line 3, in <module>
I/python  (22708):    File "/home/mehdi/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/PIL/Image.py", line 64, in <module>
I/python  (22708):  ImportError: dlopen failed: cannot locate symbol "fmod" referenced by "_imaging.so"...

dbmanager.py", line 3  is from PIL import Image ...

**Comment by AndreMiras** [comment]
Thanks @oukiar for the info, would you like to make a pull request about it if this is still an issue?
https://github.com/kivy/python-for-android/blob/v2020.04.29/pythonforandroid/recipes/Pillow/__init__.py
One thing I don't get is I do use Pillow with zbarcam and haven't seen this issue. Maybe it was already fixed recently?

**Comment by misl6** [comment]
@AndreMiras I just noticed this issue with a x86 apk during runtime, let me see if the fix @oukiar mentioned it works also in this case.

**Comment by NikitaAkimov** [comment]
Who got this error: ImportError: dlopen failed: cannot locate symbol "log" referenced by "_imaging.so"...
A way to edit the __init__.py file will help too.

.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/__init__.py

and you must changle the line
env['CFLAGS'] += cflags

to this new line with the math flag:
env['CFLAGS'] += cflags + " -lm"

clean the python-for-android and rebuild.

buildozer android clean
buildozer android debug

**Comment by Julian-O** [comment]
Closing as completed
