### ISSUE TITLE
Problem with naming of current Android NDK release: 21 

### ISSUE THREAD

**Issue by pnhofmann** [kivy/buildozer#1029]
Use of Android NDK 21 (``android.ndk = 21``; release Jan 13) results in:

```
Traceback (most recent call last):
  File "/home/phil/.local/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1053, in run_command
    self.run_default()
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1026, in run_default
    self.run_command(cmd)
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1071, in run_command
    self.target.run_commands(args)
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 178, in prepare_for_build
    self.target.install_platform()
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/targets/android.py", line 666, in install_platform
    self._install_android_ndk()
  File "/home/phil/.local/lib/python3.8/site-packages/buildozer/targets/android.py", line 411, in _install_android_ndk
    _version = re.search('(.+?)[a-z]', self.android_ndk_version).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Apparently Google changed naming convention - instead of something like '20b' the current version is just called '21' - and that's why ``'(.+?)[a-z]'`` fails. Don't experience any issues with this regex changed to: ``'(.+?)[a-z]?'

**Comment by AndreMiras** [comment]
Please open a pull request about it :+1:

**Comment by pnhofmann** [comment]
#1130
