### ISSUE TITLE
unusual folder name error every time i try to build apk using buildozer

### ISSUE THREAD

**Issue by hussam132** [kivy/buildozer#1040]
I built an apk with buildozer for the first time online very well and the app work fine but when i want to build anther one it gives me the following error also I tried to run buildozer -v android clean and tried to change the package name to be myKivyApp but still I get this error 
but when I cd into this directory

`/mnt/c/users/husam/kivy_apk/.buildozer/android/platform/build-armeabi-v7a/dists`

i find this folder myKivyApp_ armeabi-v7a and when i change the name to myKivyApp and rebuild the apk is work fine
so Is that normal or there are some issue ?

the error log

```
# Package the application
Traceback (most recent call last):
  File "/home/hussam/.local/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 1062, in run_command
    self.target.run_commands(args)
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 222, in build
    self.target.build_package()
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/targets/android.py", line 985, in build_package
    self._update_libraries_references(dist_dir)
  File "/home/hussam/.local/lib/python3.6/site-packages/buildozer/targets/android.py", line 1198, in _update_libraries_references
    with io.open(project_fn, 'w', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/users/husam/kivy_apk/.buildozer/android/platform/build-armeabi-v7a/dists/myKivyApp/project.properties'
```

all the processes before the` # Package the application` line is work without an error

**Comment by sangram1010** [comment]
I also have the same error, did you find any solution?

**Comment by AndreMiras** [comment]
We cannot really tell without full log and additional informations requested by the issue template.
Feel free to re-open providing all the context information asked in the template
