### ISSUE TITLE
MacOS: NameError when session is locked during build (Python 3 compatibility)

### ISSUE THREAD

**Issue by lerela** [kivy/buildozer#1070]
There is a rogue `raw_input` in `targets/ios.py` that breaks the build when Buildozer asks for the keychain password in Python 3:

```
# Package the application
# Run 'security unlock-keychain -u'
# Cwd None
security: SecKeychainUnlock <NULL>: User interaction is not allowed.
Password to unlock the default keychain:
# Run 'security' ...
# Cwd None
The keychain password can be saved in the build directory
As soon as the build directory will be cleaned, the password will be erased.
Traceback (most recent call last):
  File "/Users/lerela/Library/Python/3.7/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/__init__.py", line 1071, in run_command
    self.target.run_commands(args)
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/__init__.py", line 214, in build
    self.target.build_package()
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/targets/ios.py", line 161, in build_package
    self._unlock_keychain()
  File "/Users/lerela/Library/Python/3.7/lib/python/site-packages/buildozer/targets/ios.py", line 401, in _unlock_keychain
    q = raw_input('Do you want to save the password (Y/n): ')
NameError: name 'raw_input' is not defined
```

**Comment by AndreMiras** [comment]
Thanks for the report and the fix
