### ISSUE TITLE
MacOS: ImportError: The 'six' package is required

### ISSUE THREAD

**Issue by Foreman76** [kivy/buildozer#1077]
### Versions

* Python: 3.7.5
* OS: MacOS Catalina 10.15.1
* Buildozer: buildozer==1.0.1.dev0

### Description

When I compile my application in apk file. I get the error  ImportError: The 'six' package is required; This package is in my Python 3.7. My OS MacOS Catalina. Any ideas how to fix it?

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = Btest

# (str) Package name
package.name = btest

# (str) Package domain (needed for android/ios packaging)
package.domain = ru.int24

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,jpeg,ttf,md,kv,json

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*

# (str) Application versioning (method 2)
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py
# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy==1.11.1
#,git+https://github.com/HeaTTheatR/KivyMD.git,pillow,pygments
# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
#requirements.source.kivymd = ../../kivymd
# (str) Presplash of the application
presplash.filename = %(source.dir)s/data/kivy-presplash.jpg
# (str) Icon of the application
icon.filename = %(source.dir)s/data/kivy-icon.png
# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait
# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0
# (string) Presplash background color (for new android toolchain)
android.presplash_color = #FFFFFF
# (list) Permissions
android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE
# (int) Target Android API, should be as high as possible.
android.api = 28
# (int) Minimum API your APK will support.
android.minapi = 21
# (str) Android NDK version to use
android.ndk = 19b
# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
android.skip_update = False
# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
android.accept_sdk_license = True
# (str) Android logcat filters to use
android.logcat_filters = *:S python:D
# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a
[buildozer]
# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2
# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 0
# (str) Path to build artifact storage, absolute or relative to spec file
build_dir = ./.buildozer
# (str) Path to build output (i.e. .apk, .ipa) storage
bin_dir = ./bin
#

```

### Logs

```
(Venvpy3_kivy) Macs-MacBook-Pro:Test Macbook$ buildozer android debug logcat > log.txt
/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:85: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO]:    Recipe kivy: version "1.11.1" requested
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 28
[INFO]:    Available Android APIs are (28)
[INFO]:    Requested API target 28 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /Users/Macbook/.buildozer/android/platform/android-ndk-r19b
[INFO]:    Found NDK version 19b
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    Found virtualenv at /Users/Macbook/virtualPython/Venvpy3_kivy/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'android', 'kivy']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name btest and requirements (python3, kivy)
[INFO]:    Dist contains the following requirements as recipes: ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'android', 'kivy']
[INFO]:    Dist will also contain modules (certifi) installed from pip
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Recipe build order is ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'android', 'kivy']
[INFO]:    The requirements (certifi) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 28 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/hostpython3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
[INFO]:    hostpython3 download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading libffi
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 23 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/libffi
[INFO]:    -> running basename https://github.com/libffi/libffi/archive/8fa8837.tar.gz
[INFO]:    libffi download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 24 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/openssl
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.1.1f.tar.gz
[INFO]:    openssl download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 27 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.tar.gz
[INFO]:    sdl2_image download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 27 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 25 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 24 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/sqlite3
[INFO]:    -> running basename https://www.sqlite.org/2016/sqlite-amalgamation-3150100.zip
[INFO]:    sqlite3 download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading python3
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 24 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/python3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
[INFO]:    python3 download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 21 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
[INFO]:    sdl2 download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading setuptools
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 27 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/setuptools
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/setuptools/setuptools-40.9.0.zip
[INFO]:    setuptools download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 20 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
[INFO]:    six download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 24 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/1.2.1.zip
[INFO]:    pyjnius download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-arme...(and 21 more)
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.11.1.zip
[INFO]:    kivy download already cached, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop
[INFO]:    hostpython3 is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking libffi for armeabi-v7a
[INFO]:    -> running basename https://github.com/libffi/libffi/archive/8fa8837.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21
[INFO]:    libffi is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.1.1f.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org/2016/sqlite-amalgamation-3150100.zip
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/sqlite3/armeabi-v7a__ndk_target_21
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking python3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21
[INFO]:    python3 is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking setuptools for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/setuptools/setuptools-40.9.0.zip
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21
[INFO]:    setuptools is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/six-python3/armeabi-v7a__ndk_target_21
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/1.2.1.zip
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    -> running rm -rf /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeab...(and 80 more)
[INFO]:    -> running cp -a /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-an...(and 199 more)
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.11.1.zip
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/kivy-python3/armeabi-v7a__ndk_target_21
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding libffi for armeabi-v7a
[INFO]:    libffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for libffi[armeabi-v7a]
[INFO]:    libffi already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sqlite3 for armeabi-v7a
[INFO]:    sqlite3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
[INFO]:    python3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python3[armeabi-v7a]
[INFO]:    python3 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding setuptools for armeabi-v7a
[INFO]:    setuptools has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/android-python3-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    hostpython3 said it is already built, skipping
[INFO]:    Building libffi for armeabi-v7a
[INFO]:    libffi said it is already built, skipping
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    openssl said it is already built, skipping
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building sqlite3 for armeabi-v7a
[INFO]:    sqlite3 said it is already built, skipping
[INFO]:    Building python3 for armeabi-v7a
[INFO]:    python3 said it is already built, skipping
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android
[INFO]:    Building setuptools for armeabi-v7a
[INFO]:    setuptools apparently isn't already in site-packages
[INFO]:    Installing setuptools into site-packages
[INFO]:    -> directory context /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21/setuptools
[INFO]:    -> running python3 setup.py install -O2 --root=/Users/Macbook/PycharmProjects/Test/.buildozer/...(and 78 more)
Exception in thread background thread for pid 59071:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/btest --install-lib=.

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21/setuptools/setuptools/__init__.py", line 15, in <module>
    from setuptools.extern.six import PY3, string_types
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21/setuptools/setuptools/extern/__init__.py", line 57, in load_module
    raise ImportError(
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.


  STDERR:


Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1199, in <module>
    main()
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 671, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 155, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 209, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 960, in build_arch
    self.install_python_package(arch)
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 979, in install_python_package
    _env=hpenv, *self.setup_extra_args)
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 180, in shprint
    for line in output:
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/Macbook/virtualPython/Venvpy3_kivy/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/btest --install-lib=.

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21/setuptools/setuptools/__init__.py", line 15, in <module>
    from setuptools.extern.six import PY3, string_types
  File "/Users/Macbook/PycharmProjects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21/setuptools/setuptools/extern/__init__.py", line 57, in load_module
    raise ImportError(
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.


  STDERR:

(Venvpy3_kivy) Macs-MacBook-Pro:Test Macbook$ 
[log.txt](https://github.com/kivy/buildozer/files/4527829/log.txt)

```

**Comment by zebra-lucky** [comment]
Try to add to requirements: six==1.14.0, setuptools==41.6.0

i'm trying versions arbitrarily, but this fixes building problem for now

maybe some problems with PyPi?

**Comment by zebra-lucky** [comment]
I've make another build, only adding explicit requirements for "six, setuptools" fixes the build

maybe someone make more investigation

**Comment by Foreman76** [comment]
thanks, I'll try to rebuild

**Comment by Foreman76** [comment]
i tried to build apk with requirements six==1.14.0, setuptools==41.6.0 It's Don't work for me ! mistake ImportError: The 'six' package is required
any idea?

**Comment by zebra-lucky** [comment]
currently requirements in my buildozer.spec has such order:
```
requirements =
    six,
    setuptools,
    python3,
...
```

**Comment by zebra-lucky** [comment]
and clean build works yesterday

**Comment by zebra-lucky** [comment]
maybe try clean repo clone and build there (for clean build)

**Comment by zebra-lucky** [comment]
or problem in some other place, not sure

**Comment by Foreman76** [comment]
i same thinks. this problem in other place
