### ISSUE TITLE
Buildozer on OS X can't compile my app

### ISSUE THREAD

**Issue by Alexandrelzeg** [kivy/buildozer#1084]
* Python: 3.7
* OS: 10.15.4
* Buildozer: 1.0
* Kivy: 1.11.1

Trying to use
 buildozer android debug deploy run

getting an error

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /Users/iportstachek/Documents/andr/venv/bin/cython
# Search for Java compiler (javac)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac
# Search for Java keytool (keytool)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /Users/iportstachek/Documents/andr/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /Users/iportstachek/Documents/andr/.buildozer/android/platform/python-for-android
* master 8cf66cc1 [origin/master] Merge pull request #2111 from kivy/release-2020.03.30
# Run '/Users/iportstachek/Documents/andr/venv/bin/python -m pip install -q  \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'pytoml\' \'virtualenv<20\''
# Cwd None
# Apache ANT found at /Users/iportstachek/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /Users/iportstachek/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 19b
# Android NDK found at /Users/iportstachek/.buildozer/android/platform/android-ndk-r19b
# Installing/updating SDK platform tools if necessary
# Run '/Users/iportstachek/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools'
# Cwd /Users/iportstachek/.buildozer/android/platform/android-sdk
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
# Command failed: /Users/iportstachek/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools
# ENVIRONMENT:
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     TMPDIR = '/var/folders/l5/s7j0795n2d52zrnqdrm1wy200000gn/T/'
#     USER = 'iportstachek'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.uulrfTWw0Z/Listeners'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x7:0x31'
#     VIRTUAL_ENV = '/Users/iportstachek/Documents/andr/venv'
#     PATH = '/Users/iportstachek/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/iportstachek/Documents/andr/venv/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin'
#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
#     PWD = '/Users/iportstachek/Documents/andr'
#     XPC_FLAGS = '0x0'
#     PS1 = '(venv) \\h:\\W \\u\\$ '
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/iportstachek'
#     LOGNAME = 'iportstachek'
#     LC_CTYPE = 'ru_RU.UTF-8'
#     _ = '/Users/iportstachek/Documents/andr/venv/bin/buildozer'
#     __PYVENV_LAUNCHER__ = '/Users/iportstachek/Documents/andr/venv/bin/python'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2


```

**Comment by AndreMiras** [comment]
https://python-for-android.readthedocs.io/en/latest/troubleshooting/?highlight=java.lang.NoClassDefFoundError#errors-related-to-java-version

**Comment by Alexandrelzeg** [comment]
got later the next issue

```
Exception in thread background thread for pid 13814:                                                                                                                                     
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 2606, in background_thread
    handle_exit_code(exit_code)
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 2304, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_127: 

  RAN: /Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh

  STDOUT:
/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh: line 2: exec: autoreconf: not found


  STDERR:


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1199, in <module>
    main()
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 671, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 155, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 209, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/__init__.py", line 40, in build_arch
    shprint(sh.Command('./autogen.sh'), _env=env)
  File "/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 180, in shprint
    for line in output:
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 925, in next
    self.wait()
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 849, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/iportstachek/Documents/morseandroid/venv/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_127: 

  RAN: /Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh

  STDOUT:
/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh: line 2: exec: autoreconf: not found


  STDERR:

# Command failed: /Users/iportstachek/Documents/morseandroid/venv/bin/python -m pythonforandroid.toolchain create --dist_name=morse --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/iportstachek/Documents/morseandroid/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     TMPDIR = '/var/folders/l5/s7j0795n2d52zrnqdrm1wy200000gn/T/'
#     USER = 'iportstachek'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.GZ65akg7bo/Listeners'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x7:0x31'
#     VIRTUAL_ENV = '/Users/iportstachek/Documents/morseandroid/venv'
#     PATH = '/Users/iportstachek/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/iportstachek/Documents/morseandroid/venv/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin'
#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
#     PWD = '/Users/iportstachek/Documents/morseandroid'
#     XPC_FLAGS = '0x0'
#     PS1 = '(venv) \\h:\\W \\u\\$ '
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/iportstachek'
#     LOGNAME = 'iportstachek'
#     LC_CTYPE = 'ru_RU.UTF-8'
#     _ = '/Users/iportstachek/Documents/morseandroid/venv/bin/buildozer'
#     __PYVENV_LAUNCHER__ = '/Users/iportstachek/Documents/morseandroid/venv/bin/python'
#     PACKAGES_PATH = '/Users/iportstachek/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/iportstachek/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/iportstachek/.buildozer/android/platform/android-ndk-r19b'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by AndreMiras** [comment]
This is also documented a lot across existing bugs.
For support questions try Discord support channels. This is a bug tracker to report bugs that are not yet reported
