### ISSUE TITLE
Unable to add "requirements" buildozer.spec

### ISSUE THREAD

**Issue by yagupta** [kivy/buildozer#109]
When I add "requirements" to buildozer.spec, it does not seem to work. 

Snippet from buildozer.spec

```
# (list) Application requirements
requirements = kivy requests

Failure : 

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/yatharth/src/kivy-test/.buildozer/venv/build/kivy/setup.py", line 94, in <module>

    from Cython.Distutils import build_ext

ImportError: No module named Cython.Distutils

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/yatharth/src/kivy-test/.buildozer/venv/build/kivy
Storing debug log for failure in /Users/yatharth/.pip/pip.log
[YaGupta-Debug] - Self.CMD Failed, pip install --download-cache=/Users/yatharth/.buildozer/cache --target=/Users/yatharth/src/kivy-test/.buildozer/applibs kivy requests
# Command failed: pip install --download-cache=/Users/yatharth/.buildozer/cache --target=/Users/yatharth/src/kivy-test/.buildozer/applibs kivy requests
```

How pip free clearly shows that Cython is installed : 

```
Cython==0.20.1
PyRSS2Gen==1.0.0
Twisted==12.2.0
altgraph==0.10.1
astroid==1.1.0
bdist-mpkg==0.4.4
bonjour-py==0.3
buildozer==0.15-dev
colorama==0.2.7
logilab-common==0.61.0
macholib==1.5
matplotlib==1.1.1
modulegraph==0.10.1
numpy==1.6.2
py2app==0.7.1
pyOpenSSL==0.13
pylint==1.2.0
pyobjc-core==2.3.2a0
pyobjc-framework-AddressBook==2.3.2a0
pyobjc-framework-AppleScriptKit==2.3.2a0
pyobjc-framework-AppleScriptObjC==2.3.2a0
pyobjc-framework-Automator==2.3.2a0
pyobjc-framework-CFNetwork==2.3.2a0
pyobjc-framework-Cocoa==2.3.2a0
pyobjc-framework-Collaboration==2.3.2a0
pyobjc-framework-CoreData==2.3.2a0
pyobjc-framework-CoreLocation==2.3.2a0
pyobjc-framework-CoreText==2.3.2a0
pyobjc-framework-DictionaryServices==2.3.2a0
pyobjc-framework-ExceptionHandling==2.3.2a0
pyobjc-framework-FSEvents==2.3.2a0
pyobjc-framework-InputMethodKit==2.3.2a0
pyobjc-framework-InstallerPlugins==2.3.2a0
pyobjc-framework-InstantMessage==2.3.2a0
pyobjc-framework-InterfaceBuilderKit==2.3.2a0
pyobjc-framework-LatentSemanticMapping==2.3.2a0
pyobjc-framework-LaunchServices==2.3.2a0
pyobjc-framework-Message==2.3.2a0
pyobjc-framework-OpenDirectory==2.3.2a0
pyobjc-framework-PreferencePanes==2.3.2a0
pyobjc-framework-PubSub==2.3.2a0
pyobjc-framework-QTKit==2.3.2a0
pyobjc-framework-Quartz==2.3.2a0
pyobjc-framework-ScreenSaver==2.3.2a0
pyobjc-framework-ScriptingBridge==2.3.2a0
pyobjc-framework-SearchKit==2.3.2a0
pyobjc-framework-ServiceManagement==2.3.2a0
pyobjc-framework-SyncServices==2.3.2a0
pyobjc-framework-SystemConfiguration==2.3.2a0
pyobjc-framework-WebKit==2.3.2a0
pyobjc-framework-XgridFoundation==2.3.2a0
python-dateutil==1.5
pytz==2012d
requests==2.2.1
scipy==0.11.0
soco==0.6
versioneer==0.10
virtualenv==1.11.4
wsgiref==0.1.2
xattr==0.6.4
zope.interface==3.8.0
```

**Comment by YJonmo** [comment]
I am getting a bit frustrated with kivy. I am just using online sample codes and still it does not work. on my Ubuntu 14.04 terminal after I type 

buildozer android debug deploy run 

it shows things are going well and at the end it types:

# Application pushed.
# Run on 4df149060fbf6f21
# Run '/home/yjon701/.buildozer/android/platform/android-sdk-20/platform-tools/adb shell am start -n com.wordpress.bytedebugger.accelplot/org.renpy.android.PythonActivity -a org.renpy.android.PythonActivity'
# Cwd /home/yjon701/.buildozer/android/platform
Starting: Intent { act=org.renpy.android.PythonActivity cmp=com.wordpress.bytedebugger.accelplot/org.renpy.android.PythonActivity }
# Application started.

but on my Samsung Galaxy III the screen of the 'loading ...' appears but then it crashes. Most of the codes I made for the android end in the same way. So I don't know what is wrong. Any idea? 

Thanks

**Comment by inclement** [comment]
@YJonmo Please open a new issue, don't add to this old closed one which refers to a different problem.

But before you do that, use `buildozer android logcat` to see the error log when your app runs (see [the doc](https://kivy.org/docs/guide/android.html#debugging-your-application-on-the-android-platform), and debug it using this information. If you can't find the problem this way, ask on the Kivy mailing list or irc. Github issues are better for actual framework bugs.
