### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'buildozer.spec'

### ISSUE THREAD

**Issue by asm201** [kivy/buildozer#1159]
### Versions

* Python: 3.8
* OS: ubuntu 20.04 on windows
* Buildozer: 1.2.0 dev0

### Description
 I'm trying to create buildozer.spec using buildozer init, however i recieve this message error, i also wanted to use python 3.7, but i don't know how to change the python path.

### Logs

```
Traceback (most recent call last):
  File "/home/asm201/.local/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/home/asm201/.local/lib/python3.8/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/asm201/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 994, in run_command
    getattr(self, cmd)(*args)
  File "/home/asm201/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1033, in cmd_init
    copyfile(join(dirname(__file__), 'default.spec'), 'buildozer.spec')
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'buildozer.spec'
```

**Comment by AndreMiras** [comment]
You don't provide enough info for us to tell if this is a real bug. Usually permissions issues for current working directory, you need to show the proof you're not doing it in a directory that doesn't make sense. It's like if I do `touch /foo` obviously I don't have permission to write to the root directory and it's not a bug in the `touch` command.
Feel free to re-open with more information or come to Discord if what you look for is support
