### ISSUE TITLE
Building for android api 28 fails

### ISSUE THREAD

**Issue by dante7989** [kivy/buildozer#1162]
I am trying to run `buildozer android release` but it's failing.
It started after i change from api 27 to 28 and min api from 21 to 28.
I am using Java 8 as -> `export "JAVA_HOME=$(/usr/libexec/java_home -v 1.8)"` 

```
# Command failed: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pythonforandroid.toolchain create --dist_name=pluberx --bootstrap=sdl2 --requirements=python3,kivy,validate_email --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/dante/Desktop/kivytest/kivySite/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=28
# ENVIRONMENT:
#     TERM_PROGRAM = 'Apple_Terminal'
#     ANDROID_HOME = '/Users/dante/Library/Android/sdk'
#     SHELL = '/bin/bash'
#     TERM = 'xterm-256color'
#     TMPDIR = '/var/folders/b2/shy4fkcs41qcjdqfq2vy37bw0000gn/T/'
#     TERM_PROGRAM_VERSION = '433'
#     OLDPWD = '/Users/dante'
#     TERM_SESSION_ID = '402F0F64-12EE-455E-B29F-94909C2CA176'
#     USER = 'dante'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.Sx9EN0C2Gq/Listeners'
#     PATH = ('/Users/dante/.buildozer/android/platform/apache-ant-1.9.4/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin '
 'Workbooks.app/Contents/SharedSupport/path-bin:/Users/dante/Library/Android/sdk/tools:/Users/dante/Library/Android/sdk/build-tools/28.0.2')
#     PWD = '/Users/dante/Desktop/kivytest/kivySite'
#     JAVA_HOME = '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home'
#     XPC_FLAGS = '0x0'
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/dante'
#     LOGNAME = 'dante'
#     LC_CTYPE = 'UTF-8'
#     _ = '/Library/Frameworks/Python.framework/Versions/3.7/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x0'
#     __PYVENV_LAUNCHER__ = '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3'
#     PACKAGES_PATH = '/Users/dante/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/dante/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/dante/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '28'
#     ANDROIDMINAPI = '28'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

spec file:

```
[app]

# (str) Title of your application
title = Plumber X

# (str) Package name
package.name = pluberx

# (str) Package domain (needed for android/ios packaging)
package.domain = org.dante.plumberx

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,ttf

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,validate_email

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
android.api = 28

# (int) Minimum API your APK will support.
android.minapi = 28

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

**Comment by AndreMiras** [comment]
This bug is invalid as it doesn't provide enough information.
Please provide the entire build log, not just the final part that provides too little info

**Comment by dante7989** [comment]
where can i find it?

**Comment by AndreMiras** [comment]
It's the complete shell output of your `buildozer android debug` command. If what you look for is support and not making a bug report, then join the Discord chat instead

**Comment by dante7989** [comment]
```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/local/git/bin/git
# Search for Cython (cython)
#  -> found at /Library/Frameworks/Python.framework/Versions/2.7/bin/cython
# Search for Java compiler (javac)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac
# Search for Java keytool (keytool)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android
* master 1b3b0e3f [origin/master] Merge pull request #2225 from kivy/release-2020.06.02
# Run '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'toml\''
# Cwd None
# Apache ANT found at /Users/dantebenty/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /Users/dantebenty/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 19c
# Android NDK found at /Users/dantebenty/.buildozer/android/platform/android-ndk-r19c
# Check application requirements
# Compile platform
# Run '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pythonforandroid.toolchain create --dist_name=pluberx --bootstrap=sdl2 --requirements=python3,kivy,validate_email --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=28'
# Cwd /Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android
/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:84: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 28
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1260, in <module>
    main()
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 709, in __init__
    getattr(self, command)(args)
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 147, in wrapper_func
    user_ndk_api=self.ndk_api)
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 300, in prepare_build_environment
    apis = get_available_apis(self.sdk_dir)
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 74, in get_available_apis
    targets = get_targets(sdk_dir)
  File "/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 62, in get_targets
    targets = avdmanager('list', 'target').stdout.decode('utf-8').split('\n')
  File "/Users/dantebenty/Library/Python/3.7/lib/python/site-packages/sh.py", line 1549, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/dantebenty/Library/Python/3.7/lib/python/site-packages/sh.py", line 793, in __init__
    self.wait()
  File "/Users/dantebenty/Library/Python/3.7/lib/python/site-packages/sh.py", line 849, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/dantebenty/Library/Python/3.7/lib/python/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/dantebenty/.buildozer/android/platform/android-sdk/tools/bin/avdmanager list target

  STDOUT:

ERROR: JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Homeclear

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.



  STDERR:

# Command failed: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pythonforandroid.toolchain create --dist_name=pluberx --bootstrap=sdl2 --requirements=python3,kivy,validate_email --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/dantebenty/Desktop/kivytest/kivySite/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=28
# ENVIRONMENT:
#     TERM_PROGRAM = 'Apple_Terminal'
#     ANDROID_HOME = '/Users/dantebenty/Library/Android/sdk'
#     SHELL = '/bin/bash'
#     TERM = 'xterm-256color'
#     TMPDIR = '/var/folders/b2/shy4fkcs41qcjdqfq2vy37bw0000gn/T/'
#     TERM_PROGRAM_VERSION = '433'
#     OLDPWD = '/Users/dantebenty'
#     TERM_SESSION_ID = '402F0F64-12EE-455E-B29F-94909C2CA176'
#     USER = 'dantebenty'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.Sx9EN0C2Gq/Listeners'
#     PATH = ('/Users/dantebenty/.buildozer/android/platform/apache-ant-1.9.4/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin '
 'Workbooks.app/Contents/SharedSupport/path-bin:/Users/dantebenty/Library/Android/sdk/tools:/Users/dantebenty/Library/Android/sdk/build-tools/28.0.2')
#     PWD = '/Users/dantebenty/Desktop/kivytest/kivySite'
#     JAVA_HOME = '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Homeclear'
#     XPC_FLAGS = '0x0'
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/dantebenty'
#     LOGNAME = 'dantebenty'
#     LC_CTYPE = 'UTF-8'
#     _ = '/Library/Frameworks/Python.framework/Versions/3.7/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x0'
#     __PYVENV_LAUNCHER__ = '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3'
#     PACKAGES_PATH = '/Users/dantebenty/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/dantebenty/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/dantebenty/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '28'
#     ANDROIDMINAPI = '28'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by AndreMiras** [comment]
OK so you forgot some slightly super important details in the origin bug report :joy: 
The operating system for instance. The bug report comes with a template for this exact reason, so other things we ask like Cython version, buildozer version, Python version are important.
Also I see this error:
```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000111d18dc0 (most recent call first):
<no Python frame>
configure: error: python3.8 interpreter not found
```
This error is new to me, but I would look for it in the entire kivy bug tracker as well as in Google if I were you.
Another thing is you did `buildozer android release` that feels not natural to try to build a release if debug already doesn't work. If debug works, but not release then you also want to mention this non-detail to the report.

**Comment by foobarbecue** [comment]
Presumably the same as https://github.com/kivy/buildozer/issues/1162

**Comment by foobarbecue** [comment]
I had a similar issue but it resolved itself when I deleted my .buildozer directory.
