### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by nitinkgp23** [kivy/buildozer#1179]
### Versions

* Python: 3.7
* OS: macOS Mojave  10.14.6
* Buildozer: 1.2.0

### Description

I am getting this error, when I try to build my android application from kivy. I have used kivymd, and some other libraries such as google-auth-client, which you can see in requirements in spec file. I guess this error comes due to some incompatible python versions (I am not sure), but I have made sure I am using same python version (3.7.7) both for the project and for running buildozer.

### buildozer.spec
Command:
```
buildozer android debug deploy run
```

Spec file:
```
[app]

# (str) Title of your application
title = Budget-Tracker

# (str) Package name
package.name = budgeteer

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3==3.7.7, kivy, git+https://github.com/HeaTTheatR/KivyMD.git@master, google-auth-oauthlib,
               google-api-python-client, gspread, python-dateutil, beautifulsoup4

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
Traceback (most recent call last):
  File "/Users/nitinchoudhary/miniconda3/envs/budget/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nitinchoudhary/miniconda3/envs/budget/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1260, in <module>
    main()
  File "/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 709, in __init__
    getattr(self, command)(args)
  File "/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 155, in wrapper_func
    func(self, args, **kw)
  File "/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1128, in apk
    output, build_args = self._build_package(args, package_type='apk')
  File "/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1038, in _build_package
    key=LooseVersion)
  File "/Users/nitinchoudhary/miniconda3/envs/budget/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/nitinchoudhary/miniconda3/envs/budget/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Command failed: /Users/nitinchoudhary/miniconda3/envs/budget/bin/python -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name budgeteer --name Budget-Tracker --version 0.1 --package org.test.budgeteer --minsdk 21 --ndk-api 21 --private /Users/nitinchoudhary/budgeteer/.buildozer/android/app --permission INTERNET --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir="/Users/nitinchoudhary/budgeteer/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#
#     LC_TERMINAL_VERSION = '3.3.11'
#     Apple_PubSub_Socket_Render = '/private/tmp/com.apple.launchd.e6qPua8JHn/Render'
#     COLORFGBG = '15;0'
#     ITERM_PROFILE = 'Default'
#     SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS = '/Users/nitinchoudhary/Library/WebKit/Databases'
#     XPC_FLAGS = '0x0'
#     PWD = '/Users/nitinchoudhary/budgeteer'
#     SHELL = '/bin/zsh'
#     SECURITYSESSIONID = '18785'
#     TERM_PROGRAM_VERSION = '3.3.11'
#     TERM_PROGRAM = 'iTerm.app'
#     PATH = '/Users/nitinchoudhary/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/nitinchoudhary/.local/bin:/Users/nitinchoudhary/miniconda3/envs/budget/bin:/Users/nitinchoudhary/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
#     LC_TERMINAL = 'iTerm2'
#     COLORTERM = 'truecolor'
#     COMMAND_MODE = 'unix2003'
#     TERM = 'xterm-256color'
#     HOME = '/Users/nitinchoudhary'
#     TMPDIR = '/var/folders/y8/xrjmc_xj6w19t9cmzpzbm9ww0000gn/T/'
#     USER = 'nitinchoudhary'
#     XPC_SERVICE_NAME = '0'
#     LOGNAME = 'nitinchoudhary'
#     ITERM_SESSION_ID = 'w0t4p0:532DE596-19C0-4C27-8623-6B3C9116092C'
#     __CF_USER_TEXT_ENCODING = '0x0:0:0'
#     SHLVL = '1'
#     OLDPWD = '/Users/nitinchoudhary'
#     ZSH = '/Users/nitinchoudhary/.oh-my-zsh'
#     PAGER = 'less'
#     LESS = '-R'
#     LSCOLORS = 'Gxfxcxdxbxegedabagacad'
#     LC_CTYPE = 'UTF-8'
#     CONDA_EXE = '/Users/nitinchoudhary/miniconda3/bin/conda'
#     _CE_M = ''
#     _CE_CONDA = ''
#     CONDA_PYTHON_EXE = '/Users/nitinchoudhary/miniconda3/bin/python'
#     CONDA_SHLVL = '2'
#     CONDA_PREFIX = '/Users/nitinchoudhary/miniconda3/envs/budget'
#     CONDA_DEFAULT_ENV = 'budget'
#     CONDA_PROMPT_MODIFIER = '(budget) '
#     LC_ALL = 'en_US.UTF-8'
#     LANG = 'en_US.UTF-8'
#     CONDA_PREFIX_1 = '/Users/nitinchoudhary/miniconda3'
#     _ = '/Users/nitinchoudhary/.local/bin/buildozer'
#     PACKAGES_PATH = '/Users/nitinchoudhary/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/nitinchoudhary/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/nitinchoudhary/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by nitinkgp23** [comment]
[log.txt](https://github.com/kivy/buildozer/files/4886360/log.txt)

**Comment by AndreMiras** [comment]
I understand the error, but I don't know what in your setup makes it happening.
I would put a breakpoint in `/Users/nitinchoudhary/miniconda3/envs/budget/lib/python3.7/distutils/version.py` on `TypeError` to try to debug why it's happening. So for instancing printing both `self.version` and `other.version` may give some clue about which versions it's trying to compare and where it comes from

**Comment by nitinkgp23** [comment]
I re-installed buildozer using the same python version as I am keeping the project on, i.e. 3.7.7, including downloading SDK,etc.. Made sure python version is same everywhere, and that made the error go away.
Thanks!

**Comment by alirezaAsadi2018** [comment]
I encountered the same error and found out that in my <SDK_DIR>/build-tools/ directory there is a subdirectory whose name is not a number. In my case the following command would result in:
 ```
$ ls /opt/sdk/build-tools
27.0.3  30.0.2 tools
```
I realized that the command raising the error `TypeError: '<' not supported between instances of 'str' and 'int' ` was merely trying to find all the directory names listed above and sort them by their names, thus causing this error when comparing those two numbers with a string.
All in all,  removing `tools` directory did the trick for me.

**Comment by Julian-O** [comment]
This appears to be a support issue that has been answered.

We try to use GitHub Issues only to track work for developers to do to fix bugs and add new features to Buildozer.

This issue is being closed, because it doesn't describe a bug in Buildozer.

If you have further support questions, please don't post them here. Instead, there is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.
