### ISSUE TITLE
can't build on macosx, error on ffmpeg

### ISSUE THREAD

**Issue by giona69** [kivy/buildozer#1236]
### Versions

* Python 3.6.12
* OS: MacOS Catilina 10.15.6
* Buildozer: 1.2.0

### Description

Buildozer will stop compiling on MacOS

### buildozer.spec
Command:
```sh
buildozer android debug deploy run
```

Spec file:
```
[app]

# (str) Title of your application
title = Visual Note

# (str) Package name
package.name = visualnote

# (str) Package domain (needed for android/ios packaging)
package.domain = com.visualnote

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py, pyx, png, jpg, kv, atlas, ini, ttf, wav, gif, json

# (list) List of inclusions using pattern matching
#source.include_patterns = ./mobile_resources/*

# (list) Source files to exclude (let empty to not exclude anything)
source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = venv3, build, dist, resources, soundfonts, service,  bin, venv

# (list) List of exclusions using pattern matching
source.exclude_patterns = *.spec, factory.py, visualnotedesktop*, librouter/examples/*

# (str) Application versioning (method 1)
version = 2.1.7

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
# requirements = python3crystax==3.6, ffpyplayer, ffpyplayer_codecs, kivy==master, PyGuitarPro, android, pyjnius, pyjwt, attrs==17.1.0, requests, urllib3, chardet, certifi, idna, py3audiostream
requirements = libffi, openssl, python3, ffpyplayer, ffpyplayer_codecs, kivy, android , pyjwt, attrs==17.1.0, audiostream, requests
# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
# garden_requirements = roulette, roulettescroll

# (str) Presplash of the application
presplash.filename = mobile_resources/images/portrait/splash_screen.jpg

# (str) Icon of the application
icon.filename = mobile_resources/images/portrait/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
# services = midiservice:./service/main.py

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.10.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET, BLUETOOTH, BLUETOOTH_ADMIN, WAKE_LOCK, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE, ACCESS_COARSE_LOCATION

# (int) Android API to use
android.api = 28

# (int) Minimum API required
android.minapi = 23

# (int) Android SDK version to use
android.sdk = 28

# (str) Android NDK version to use
android.ndk = 19b
#android.ndk = 13b

# (bool) Use --private data storage (True) or --dir public storage (False)
android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path = /home/mirko/DATA/sdk_toolchains/crystax-ndk-10.3.2
#android.ndk_path = /home/mirko/DATA/sdk_toolchains/android-ndk-r19b

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path = /home/mirko/Android/Sdk

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
android.add_src = java_snippets, blelib/android/java

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
android.add_aars = blelib/android/aar/scanner.aar

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
android.gradle_dependencies = com.android.support:support-v4:26+

# (str) python-for-android branch to use, defaults to master
p4a.fork = kivy
p4a.branch = develop

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = APP

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/armeabi-v7a/*.so
#android.add_libs_arm64_v8a = libs/arm64-v8a/*.so
android.add_libs_armeabi_v7a = libs/armeabi-v7a/*.so
#android.add_libs_x86 = libs/x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
android.wakelock = True

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
#android.arch = arm64-v8a
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2/jni
[INFO]:    -> running ndk-build V=1 NDK_DEBUG=1
[INFO]:    <- directory context /Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android
[INFO]:    Building ffmpeg for armeabi-v7a
[INFO]:    -> directory context /Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_23/ffmpeg
[INFO]:    -> running configure --disable-everything --enable-openssl --enable-nonfree --enable-protocol=https,tls_openssl --enable-libx264 --enable-libshine --enable-parsers --enable-decode...(and 739 more)
Exception in thread background thread for pid 84273:
Traceback (most recent call last):
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_23/ffmpeg/configure --disable-everything --enable-openssl --enable-nonfree --enable-protocol=https,tls_openssl --enable-libx264 --enable-libshine --enable-parsers --enable-decoders --enable-encoders --enable-muxers --enable-demuxers --disable-symver --disable-programs --disable-doc --enable-filter=aresample,resample,crop,adelay,volume,scale --enable-protocol=file,http,hls --enable-small --enable-hwaccels --enable-gpl --enable-pic --disable-static --disable-debug --enable-shared --target-os=android --enable-cross-compile --cross-prefix=armv7a-linux-androideabi23- --arch=arm --strip=arm-linux-androideabi-strip --sysroot=/Users/gionagranata/.buildozer/android/platform/android-ndk-r19b/toolchains/llvm/prebuilt/linux-x86_64/sysroot --enable-neon --prefix=/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_23/ffmpeg

  STDOUT:
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
armv7a-linux-androideabi23-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.


  STDERR:


Traceback (most recent call last):
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1266, in <module>
    main()
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 715, in __init__
    getattr(self, command)(args)
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 215, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 579, in build_recipes
    recipe.build_arch(arch)
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/ffmpeg/__init__.py", line 135, in build_arch
    shprint(configure, *flags, _env=env)
  File "/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 863, in next
    self.wait()
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/gionagranata/anaconda3/envs/kivy-env36/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_23/ffmpeg/configure --disable-everything --enable-openssl --enable-nonfree --enable-protocol=https,tls_openssl --enable-libx264 --enable-libshine --enable-parsers --enable-decoders --enable-encoders --enable-muxers --enable-demuxers --disable-symver --disable-programs --disable-doc --enable-filter=aresample,resample,crop,adelay,volume,scale --enable-protocol=file,http,hls --enable-small --enable-hwaccels --enable-gpl --enable-pic --disable-static --disable-debug --enable-shared --target-os=android --enable-cross-compile --cross-prefix=armv7a-linux-androideabi23- --arch=arm --strip=arm-linux-androideabi-strip --sysroot=/Users/gionagranata/.buildozer/android/platform/android-ndk-r19b/toolchains/llvm/prebuilt/linux-x86_64/sysroot --enable-neon --prefix=/Users/gionagranata/PycharmProjects/visualnote-kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_23/ffmpeg

  STDOUT:
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
armv7a-linux-androideabi23-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.


  STDERR:

```

**Comment by RobertFlatt** [comment]
This is probably artifact of the MacOS Terminal (configuration?), tput is failing because the terminal is not in interactive mode. The tput is part of the ffmpeg build commands

I'm not a mac user, I have no idea how to address this.

This has been seen before, but none of these threads suggest a solution:
https://groups.google.com/forum/?oldui=1#!searchin/kivy-users/$24TERM$20ffpyplayer/kivy-users/KY20m76jlsQ/VDZuFM0ZBAAJ
https://groups.google.com/forum/?oldui=1#!searchin/kivy-users/$24TERM$20ffpyplayer/kivy-users/U6kDTME8uus/AMhA4Xa-BQAJ
https://groups.google.com/forum/?oldui=1#!searchin/kivy-users/$24TERM/kivy-users/aU4zCRZ6t88/YI2rZzi6AQAJ
