### ISSUE TITLE
NDK Missing

### ISSUE THREAD

**Issue by SimState** [kivy/buildozer#1250]
### Versions

* Python:
* OS:
* Buildozer:

### Description

running buildozer.spec

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = MyApp

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.myapp

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,kivymd,openpyxl,random,time,os

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path = 

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian "dpkg", programma di gestione dei pacchetti versione 1.19.7 (armhf).
Questo è software libero; consultare la GNU General Public Licence versione 2
o successiva per le condizioni di copia. NON c'è alcuna garanzia.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/pi/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-11-openjdk-armhf/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-armhf/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /media/pi/98E80E72E80E4F46/EsperimentiAPP/repofold/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /media/pi/98E80E72E80E4F46/EsperimentiAPP/repofold/.buildozer/android/platform/python-for-android
* master 5a94d074 [origin/master] Merge pull request #2244 from Chronolife-team/native_services_upstream
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'toml\''
# Cwd None
# Apache ANT found at /home/pi/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/pi/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 19c
# Android NDK is missing, downloading
# Downloading https://dl.google.com/android/repository/android-ndk-r19c-linux-x86.zip
Traceback (most recent call last):
  File "/home/pi/.local/bin/buildozer", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/__init__.py", line 1010, in run_command
    self.target.run_commands(args)
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/__init__.py", line 170, in prepare_for_build
    self.target.install_platform()
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/targets/android.py", line 671, in install_platform
    self._install_android_ndk()
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/targets/android.py", line 463, in _install_android_ndk
    cwd=self.buildozer.global_platform_dir)
  File "/home/pi/.local/lib/python3.7/site-packages/buildozer/__init__.py", line 643, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib/python3.7/urllib/request.py", line 1824, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.7/tempfile.py", line 620, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file

```

**Comment by joshuapaul2005** [comment]
do `buildozer distclean` in the terminal and it will clean SDK,ndk and ant, and after that you type 'buildozer android debug' it will download sdk,ndk and ant and then it will compile your app as normal

**Comment by jleaders** [comment]
I have a simialr issue, it appears to be that the NDK URL is broken
`https://dl.google.com/android/ndk/android-ndk-r10.3.2-linux-x86_64.tar.bz2`

**Comment by misl6** [comment]
@jleaders 
Yeah, `https://dl.google.com/android/ndk/android-ndk-r10.3.2-linux-x86_64.tar.bz2` is definitely too old 😀 

@SimState looks like you're using `buildozer` on a RPi. Unfortunately, that's not supported as Google doesn't provide a `linux-arm` version of the NDK.

**Comment by HeaTTheatR** [comment]
Exactly the same problem I have on Mac OS. At the moment, this problem has not been solved.

**Comment by misl6** [comment]
> Exactly the same problem I have on Mac OS. Unfortunately the problem is still not solved.

https://github.com/kivy/buildozer/pull/1427 included a fix for that targets this issue.

Is still happening on `buildozer>=1.4.0` ? Can you open a new issue with the full traceback from `buildozer` ?

**Comment by HeaTTheatR** [comment]
@misl6 

In the master version of the Bulldozer, the link to the NDK has changed - Downloading https://dl.google.com/android/repository/android-ndk-r23b-darwin .zip
It's working now.

**Comment by misl6** [comment]
> @misl6
> 
> Unfortunately, it still doesn't work. After the Bulldozer downloads the NDK, it will not unzip the package:
> 
> ![Снимок экрана 2022-08-30 в 20 23 33](https://user-images.githubusercontent.com/16930280/187503286-b65873ad-8dad-4afb-9bbf-7a013e395655.png)
> 
> Therefore, the build fails with an error:
> 
> ```
> macbookair@MacBooks-MacBook-Air KitchenSink % buildozer android debug
> # Check configuration tokens
> # Ensure build layout
> # Create directory /Users/macbookair/Projects/Dev/KivyMD/KitchenSink/.buildozer
> # Create directory /Users/macbookair/Projects/Dev/KivyMD/KitchenSink/.buildozer/applibs
> # Create directory /Users/macbookair/Projects/Dev/KivyMD/KitchenSink/.buildozer/android/platform
> # Create directory /Users/macbookair/Projects/Dev/KivyMD/KitchenSink/.buildozer/android/app
> # Check configuration tokens
> # Read available permissions from api-versions.xml
> # Preparing build
> # Check requirements for android
> # Search for Git (git)
> #  -> found at /usr/local/git/bin/git
> # Search for Cython (cython)
> #  -> found at /opt/local/Library/Frameworks/Python.framework/Versions/3.6/bin/cython
> # Search for Java compiler (javac)
> #  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac
> # Search for Java keytool (keytool)
> #  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/keytool
> # Install platform
> # Run ['git', 'clone', '-b', 'develop', '--single-branch', 'https://github.com/kivy/python-for-android.git', 'python-for-android']
> # Cwd /Users/macbookair/Projects/Dev/KivyMD/KitchenSink/.buildozer/android/platform
> Cloning into 'python-for-android'...
> # Run ['/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10; sys_platform!="nt"', 'pep517<0.7.0', 'toml']
> # Cwd None
> # Apache ANT found at /Users/macbookair/.buildozer/android/platform/apache-ant-1.9.4
> # Android SDK found at /Users/macbookair/.buildozer/android/platform/android-sdk
> # Recommended android's NDK version by p4a is: 23b
> # Android NDK is missing, downloading
> # Downloading https://dl.google.com/android/repository/android-ndk-r23b-darwin.zip
> # Unpacking Android NDK
> # Run ['unzip', '-q', '/Users/macbookair/.buildozer/android/platform/android-ndk-r23b-darwin.zip']
> # Cwd /Users/macbookair/.buildozer/android/platform
> # Rename /Users/macbookair/.buildozer/android/platform/android-ndk-r23b to /Users/macbookair/.buildozer/android/platform/android-ndk-r23b
> # Android NDK installation done.
> # Installing/updating SDK platform tools if necessary
> # Check configuration tokens
> # sdkmanager path "/Users/macbookair/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled
> ```
> 
> Buildozer - `1.4.1.dev.0 ![Снимок экрана 2022-08-30 в 20 22 20](https://user-images.githubusercontent.com/16930280/187503052-a21d1dd5-8a80-467d-853e-ea92446255d3.png)

NDK looks good here, seems that the SDK is now failing. (Maybe a previous failure or something bad with the zip?)
[ Feel free to ping me on Discord ]

**Comment by HeaTTheatR** [comment]
@misl6 Yes, it looks like a temporary failure on the Internet, thanks.

**Comment by RichardKnipe** [comment]
> I had a similar issue, it appeared to be that the NDK URL was broken, so I had to update my `buildozer.spec` to the latest recommended NDK version The old URL: `https://dl.google.com/android/ndk/android-ndk-r10.3.2-linux-x86_64.tar.bz2`

Hi

Sorry if this is a noob question..., but where in the buildozer.spec file do you change this line? I can't seem to find a URL connected to "NDK" in the spec file. Or do you need an entirely new spec file created using the latest version of the NDK? And if so, how do you do this?
