### ISSUE TITLE
buildozer fails installing Android NDK

### ISSUE THREAD

**Issue by tomfowle** [kivy/buildozer#1268]
My system is MacOS  10.11.6
Python 3.8

When I issue the command 'buildozer android debug' the process aborts at 

```
# Android NDK is missing, downloading
# Downloading https://dl.google.com/android/repository/android-ndk-r19c-darwin-x86_64.zip
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1759, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1968, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1917, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 965, in send
    self.sock.sendall(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1205, in sendall
    v = self.send(byte_view[count:])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1174, in send
    return self._sslobj.write(data)
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:2457)

```

This problem is similar to [(https://github.com/kivy/kivy/issues/5784)] but the solution there is for python 2.7.

All advice welcomed.

**Comment by nian0** [comment]
我的解决方法是在buildozer库里的应该是__init__.py的文件里添加一个
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
不一定会解决你的问题，但你可以试试

**Comment by dlech** [comment]
I made the `ssl.SSLCertVerificationError` go away by running `open /Applications/Python\ 3.10/Install\ Certificates.command`. However, I then ran into #1112.

**Comment by kwebber3** [comment]
after installing python2 and rerunning it remains the same.

'''# Install platform
# Apache ANT found at $/android/platform/apache-ant-1.9.4
# Android SDK found at $/.buildozer/android/platform/android-sdk-20
# Android NDK found at $/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Run './distribute.sh -l'
# Cwd $/android/platform/python-for-android
Available modules: android apsw audiostream bidi boost c_igraph cherrypy click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope
# Remove directory and subdirectory $/.buildozer/applibs
# Create directory $/.buildozer/applibs
# Run 'virtualenv --python=python2.7 ./venv'
# Cwd $/.buildozer
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python2.7'
# Command failed: virtualenv --python=python2.7 ./venv
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
'''
