### ISSUE TITLE
 ModuleNotFoundError: No module named 'array'

### ISSUE THREAD

**Issue by nihaokuan** [kivy/buildozer#1286]
This is my debug logs,I don't know the cause of the problem, please help me!

[WARNING] [Config      ] Upgrading configuration in progress.
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/data/user/0/org.arrayissue.arrayissue/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
[INFO   ] Python: v3.8.1 (default, Feb  4 2021, 10:42:24)
[Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
[INFO   ] Python: Interpreter at ""
[INFO   ] Factory: 184 symbols loaded
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/mnt/e/nhk/scrapy_somesoft/mykivy/.buildozer/android/app/main.py", line 1, in <module>
[WARNING] stderr:   File "/mnt/e/nhk/scrapy_somesoft/mykivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/arrayissue/kivy/app.py", line 327, in <module>
[WARNING] stderr:   File "/mnt/e/nhk/scrapy_somesoft/mykivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/arrayissue/kivy/uix/widget.py", line 244, in <module>
[WARNING] stderr:   File "/mnt/e/nhk/scrapy_somesoft/mykivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/arrayissue/kivy/graphics/__init__.py", line 89, in <module>
[WARNING] stderr:   File "kivy/graphics/instructions.pyx", line 1, in init kivy.graphics.instructions
[WARNING] stderr:   File "kivy/graphics/vbo.pyx", line 1, in init kivy.graphics.vbo
[WARNING] stderr:   File "kivy/graphics/compiler.pyx", line 1, in init kivy.graphics.compiler
[WARNING] stderr:   File "kivy/graphics/shader.pyx", line 1, in init kivy.graphics.shader
[WARNING] stderr:   File "kivy/graphics/texture.pyx", line 1, in init kivy.graphics.texture
[WARNING] stderr: ModuleNotFoundError: No module named 'array'

**Comment by RobertFlatt** [comment]
Reading between the lines, the apk was built on an NTFS volume mounted on a Linux OS.
Is something like that correct?

If it is, try copying the project to a native volume and building there.

Its not that what you are doing couldn't work. But there may be situations with other OS mounts where Python gets confused about the OS it is on. And the message here is a confused Python. I don't know the specific issue that causes this. And of course other things may work, but that does not help you with this issue.

Anyway something to try.
