### ISSUE TITLE
Keep on gettting version error

### ISSUE THREAD

**Issue by Tooblippe** [kivy/buildozer#129]
# Package the application

Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/**init**.py", line 957, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/**init**.py", line 193, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 451, in build_package
    version = self.buildozer.get_version()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/**init**.py", line 655, in get_version
    ' (looking for `{1}`)'.format(fn, regex))
Exception: Unable to find capture version in ./main.py
 (looking for `__version__ = ['"](.*)'['"]`)

**Comment by Slim1991** [comment]
I have the same issue

**Comment by kuprel** [comment]
Should be __version__ = '0.1'

**Comment by kuprel** [comment]
Should be \__version__ = '0.1'
