### ISSUE TITLE
unable to complete packaging apk in kivy

### ISSUE THREAD

**Issue by Code69Fact** [kivy/buildozer#1301]
Unzipping /home/ankush/.gradle/wrapper/dists/gradle-6.4.1-all/ihamk9lkfdnk0vct06i4nheil/gradle-6.4.1-all.zip to /home/ankush/.gradle/wrapper/dists/gradle-6.4.1-all/ihamk9lkfdnk0vct06i4nheil
[DEBUG]:   	Exception in thread "main" java.util.zip.ZipException: error in opening zip file

LogLevel:2

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:157)
	at org.gradle.wrapper.Install.access$400(Install.java:26)
	at org.gradle.wrapper.Install$1.call(Install.java:67)
	at org.gradle.wrapper.Install$1.call(Install.java:44)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:44)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)

**Comment by Code69Fact** [comment]
Please solve this issue i will we very grateful.
