### ISSUE TITLE
Error while create apk

### ISSUE THREAD

**Issue by shojaeialireza** [kivy/buildozer#1344]
Hello, I want to create apk from my kivy project. But I see this error
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 33, in <module>
    sys.exit(load_entry_point('buildozer==1.2.0.dev0', 'console_scripts', 'buildozer')())
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/__init__.py", line 170, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/targets/android.py", line 670, in install_platform
    self._install_android_ndk()
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/targets/android.py", line 460, in _install_android_ndk
    self.buildozer.download(url,
  File "/usr/local/lib/python3.9/dist-packages/buildozer-1.2.0.dev0-py3.9.egg/buildozer/__init__.py", line 654, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib/python3.9/urllib/request.py", line 1847, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.9/tempfile.py", line 613, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file

**Comment by sqwatato** [comment]
Did it say Android Ndk not found, Downloading Ndk or something like that before the error? If it is, I suggest trying to download the Ndk manually from https://developer.android.com/ndk/downloads/older_releases. I'm assuming in above this error it says suggested Ndk version 19b or 19c. Just go to the link and download the 19c Ndk.  Unzip the file and move the folder into the directory where you have buildozer installed. Move it into .buildozer/android/platform. Easiest if you do it through finder. If you can't find the folder, to Cmd+Shift+Period to show hidden files

Then in the buildozer spec file, search for
```
# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =
```
and replace it with the path to the Ndk.
Don't forget to take out the hashtag.
It should look something like this:
```
# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path =/Users/name/folder/folder/folder/.buildozer/android/platform/android-ndk-r19c
```
Tell me if you need more help.
Btw I haven't successfully done it yet. I just ran into this error while trying and wanted to help.
