### ISSUE TITLE
Error creating apk on Macos Big Sur

### ISSUE THREAD

**Issue by nestor71** [kivy/buildozer#1345]
### Versions

* Python:  3.8
* OS: macOS Big Sur 11.5.1
* Buildozer: 1.2.0 installed via pip 

### Description

I can't create the apk with macOS, I attach the error log and the buildozer.spec file

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = Kivy

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,kivymd

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
# Command failed: /Users/nestor/PycharmProjects/Kivy/venv/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy,kivymd --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/nestor/Desktop/Progetti_Python_Visual_Studio_Code/Kivy/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     USER = 'nestor'
#     __CFBundleIdentifier = 'com.microsoft.VSCode'
#     COMMAND_MODE = 'unix2003'
#     LOGNAME = 'nestor'
#     PATH = '/Users/nestor/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/nestor/PycharmProjects/Kivy/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nestor/opt/anaconda3/bin:/Users/nestor/opt/anaconda3/condabin:/Users/nestor/Library/Python/3.8/bin:/Users/nestor/Library/Python/3.8/bin'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.UvP9mmxXzx/Listeners'
#     SHELL = '/bin/zsh'
#     HOME = '/Users/nestor'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x4'
#     TMPDIR = '/var/folders/t5/37hxkhy14flg5xvd28vb47wr0000gn/T/'
#     XPC_SERVICE_NAME = '0'
#     XPC_FLAGS = '0x0'
#     ORIGINAL_XDG_CURRENT_DESKTOP = 'undefined'
#     SHLVL = '1'
#     PWD = '/Users/nestor/Desktop/Progetti_Python_Visual_Studio_Code/Kivy'
#     OLDPWD = '/Users/nestor/Desktop/Progetti_Python_Visual_Studio_Code/Kivy'
#     CONDA_EXE = '/Users/nestor/opt/anaconda3/bin/conda'
#     CONDA_PYTHON_EXE = '/Users/nestor/opt/anaconda3/bin/python'
#     CONDA_SHLVL = '1'
#     CONDA_PREFIX = '/Users/nestor/opt/anaconda3'
#     CONDA_DEFAULT_ENV = 'base'
#     CONDA_PROMPT_MODIFIER = '(base) '
#     PYTHONPATH = ':/Users/nestor/Library/Python/3.8/bin:/Users/nestor/Library/Python/3.8/bin'
#     TERM_PROGRAM = 'vscode'
#     TERM_PROGRAM_VERSION = '1.59.0'
#     LANG = 'it_IT.UTF-8'
#     COLORTERM = 'truecolor'
#     VSCODE_GIT_IPC_HANDLE = '/var/folders/t5/37hxkhy14flg5xvd28vb47wr0000gn/T/vscode-git-620f6c4282.sock'
#     GIT_ASKPASS = ('/Applications/Visual Studio '
 'Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh')
#     VSCODE_GIT_ASKPASS_NODE = ('/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper '
 '(Renderer).app/Contents/MacOS/Code Helper (Renderer)')
#     VSCODE_GIT_ASKPASS_MAIN = ('/Applications/Visual Studio '
 'Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js')
#     TERM = 'xterm-256color'
#     _CE_M = ''
#     _CE_CONDA = ''
#     VIRTUAL_ENV = '/Users/nestor/PycharmProjects/Kivy/venv'
#     PS1 = '(venv) (base) %n@%m %1~ %# '
#     _ = '/Users/nestor/PycharmProjects/Kivy/venv/bin/buildozer'
#     PACKAGES_PATH = '/Users/nestor/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/nestor/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/nestor/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by myk1709** [comment]
I am facing the same issue at my end as well

OS : MacOS Big Sur 11.5.2
python : 3.9.6
Buildozer : 1.2.0

### Command used

```
buildozer android clean debug
```

### below are buildozer.specs

```
[app]

# (str) Title of your application
title = My App

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,txt,json

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,pyjnius

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = all

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 2.0.0

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = arm64-v8a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```



### below are the logs

```
[INFO]:    -> running python3 setup.py install -O2 --root=/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-...(and 47 more)
[INFO]:    <- directory context /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android                                               
[INFO]:    # Biglinking object files
[WARNING]: Context's python recipe found, skipping biglink (will this work?)
[INFO]:    # Postbuilding recipes
[INFO]:    Postbuilding hostpython3 for arm64-v8a
[INFO]:    Postbuilding libffi for arm64-v8a
[INFO]:    Postbuilding openssl for arm64-v8a
[INFO]:    Postbuilding sdl2_image for arm64-v8a
[INFO]:    Postbuilding sdl2_mixer for arm64-v8a
[INFO]:    Postbuilding sdl2_ttf for arm64-v8a
[INFO]:    Postbuilding sqlite3 for arm64-v8a
[INFO]:    Postbuilding python3 for arm64-v8a
[INFO]:    Postbuilding sdl2 for arm64-v8a
[INFO]:    Postbuilding setuptools for arm64-v8a
[INFO]:    Postbuilding six for arm64-v8a
[INFO]:    Postbuilding pyjnius for arm64-v8a
[INFO]:    Copying pyjnius java class to classes build dir
[INFO]:    -> directory context /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/other_builds/pyjnius-sdl2/arm64-v8a__ndk_target_21/pyjnius
[INFO]:    -> running cp -a jnius/src/org /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/javaclasses/myapp
[INFO]:    <- directory context /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android
[INFO]:    Postbuilding android for arm64-v8a
[INFO]:    Postbuilding kivy for arm64-v8a
[INFO]:    # Installing pure Python modules
[INFO]:    *** PYTHON PACKAGE / PROJECT INSTALL STAGE ***
[INFO]:    The requirements (certifi) don't have recipes, attempting to install them with pip
[INFO]:    If this fails, it may mean that the module has compiled components and needs a recipe.
[INFO]:    -> directory context /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build
[INFO]:    -> running python3 -m venv venv
           working: Error: Command '['/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/venv/bin/python3', ...(and 83 more)  Exception in thread background thread for pid 45001:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 -m venv venv

  STDOUT:
Error: Command '['/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.


  STDERR:

Traceback (most recent call last):                                                                                                                                                                       
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1276, in <module>
    main()
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 725, in __init__
    getattr(self, command)(args)
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 603, in build_recipes
    run_pymodules_install(
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 769, in run_pymodules_install
    shprint(host_python, '-m', 'venv', 'venv')
  File "/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 953, in next
    self.wait()
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/mayanksharma/Library/Python/3.9/lib/python/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 -m venv venv

  STDOUT:
Error: Command '['/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a/build/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.


  STDERR:

# Command failed: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy,pyjnius --arch arm64-v8a --copy-libs --color=always --storage-dir="/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py/.buildozer/android/platform/build-arm64-v8a" --ndk-api=21
# ENVIRONMENT:
#     TERM_PROGRAM = 'Apple_Terminal'
#     SHELL = '/bin/zsh'
#     TERM = 'xterm-256color'
#     TMPDIR = '/var/folders/7x/8rl9xdgd3nn6vvs8_2wdbln00000gn/T/'
#     TERM_PROGRAM_VERSION = '440'
#     TERM_SESSION_ID = '631F190E-540E-4EB5-8ED3-7EA1001825BE'
#     USER = 'mayanksharma'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.EKA0OFQOSK/Listeners'
#     PATH = '/Users/mayanksharma/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/mayanksharma/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Python/3.9/bin:/Users/mayanksharma/Developer/flutter/bin:/Users/mayanksharma/Library/Python/3.9/bin'
#     LaunchInstanceID = 'A5EA16C3-A0BA-4B99-9A9C-6E42681623FA'
#     __CFBundleIdentifier = 'com.apple.Terminal'
#     PWD = '/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py'
#     XPC_FLAGS = '0x0'
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/mayanksharma'
#     LOGNAME = 'mayanksharma'
#     SECURITYSESSIONID = '186a6'
#     OLDPWD = '/Users/mayanksharma/Desktop/Python-new/00-course-2-udemy/app-5-mobileapp.py'
#     LC_CTYPE = 'UTF-8'
#     _ = '/Users/mayanksharma/Library/Python/3.9/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x2'
#     PACKAGES_PATH = '/Users/mayanksharma/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/mayanksharma/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/mayanksharma/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by misl6** [comment]
We're tracking it on `python-for-android`, see: https://github.com/kivy/python-for-android/issues/2568
