### ISSUE TITLE
No rule to make target 'build_libs'

### ISSUE THREAD

**Issue by code1010111** [kivy/buildozer#1378]
* Python: 3.7
* OS: ALT Linux
* Buildozer: 1.2.0.dev0
### Description

// I try to build "Hello World" apk file like new user.

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]
title = My Application
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.arch = armeabi-v7a
android.allow_backup = True
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0
ios.codesign.allowed = false
[buildozer]
log_level = 2
warn_on_root = 1
```

### Logs

```
[DEBUG]:        patching file Makefile
[DEBUG]:   -> running make build_libs
[DEBUG]:        make: *** No rule to make target 'build_libs'.  Stop.
Exception in thread background thread for pid 413968:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make build_libs

  STDOUT:
make: *** No rule to make target 'build_libs'.  Stop.


  STDERR:


Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1276, in <module>
    main()
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 725, in __init__
    getattr(self, command)(args)
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 215, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/openssl/__init__.py", line 133, in build_arch
    shprint(sh.make, 'build_libs', _env=env)
  File "/home/zah/PycharmProjects/p4a/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 953, in next
    self.wait()
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3/site-packages/sh-1.14.2-py3.7.egg/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make build_libs

  STDOUT:
make: *** No rule to make target 'build_libs'.  Stop.
```

**Comment by RobertFlatt** [comment]
Try with the default buildozer.spec  If that does not work.....

This forum is for development issues, please direct usage questions to the User Groups
https://groups.google.com/g/kivy-users
https://discord.gg/7PjCsVqA
