### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by magowiz** [kivy/buildozer#1457]
### Versions

* Python:  3.10.4
* OS: Ubuntu 22.04
* Buildozer: 1.3.0

### Description

even if libbz2-dev is installed, python gets compiled without _bz2 module, the whole build of buildozer succeeds but when app is launched it crashes and in logs claims about missing `_bz2` module

### buildozer.spec
Command: 
```sh
buildozer --verbose android debug 
```

Spec file:
```
[app]
title = Travel Lint
package.name = travel_lint
package.domain = net.magowiz
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,md,rst,txt,json,ini
source.exclude_dirs = tests, bin, .buildozer, .pytest_cache, ~, htmlcov, kivymd_example,
                      features
source.exclude_patterns = *.spec, .coverage*, pylintrc, *.sh, requirements.txt,
                          pytest.ini, token.json
version.regex = __version__ = ['"](.*)['"]
version.filename = main.py
requirements = python3, kivy==2.0.0, kivymd, Pillow, pygments, html2bbcode, m2rr,
               docutils==0.18.1, mistune==0.8.4, sdl2_ttf==2.0.15, httplib2, pyparsing,
               uritemplate, google-api-python-client,google, six==1.12.0,
               google-auth-httplib2, google-auth-oauthlib, google-api-core,
               google-auth, requests, urllib3, chardet, certifi, idna,
               cachetools, pyasn1, pyasn1_modules, rsa, requests_oauthlib,
               oauthlib, dropbox, stone, country_list, geopy, forex_python, simplejson,
               countryinfo, pyowm, geojson
presplash.filename = logo.png
icon.filename = logo.png
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = INTERNET, STORAGE
android.accept_sdk_license = True
android.arch = armeabi-v7a
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0
[buildozer]
log_level = 2
warn_on_root = 1
```

### Logs

```
07-11 21:32:09.855 15567 15657 I python  :  Traceback (most recent call last):
07-11 21:32:09.855 15567 15657 I python  :    File "/home/magowiz/MEGA/projects/holiday/.buildozer/android/app/main.py", line 33, in <module>
07-11 21:32:09.855 15567 15657 I python  :    File "/home/magowiz/MEGA/projects/holiday/.buildozer/android/app/lib/weather/weather_getter.py", line 3, in <module>
07-11 21:32:09.855 15567 15657 I python  :    File "/home/magowiz/MEGA/projects/holiday/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/travel_lint/armeabi-v7a/pyowm/__init__.py", line 4, in <module>
07-11 21:32:09.856 15567 15657 I python  :    File "/home/magowiz/MEGA/projects/holiday/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/travel_lint/armeabi-v7a/pyowm/owm.py", line 14, in <module>
07-11 21:32:09.856 15567 15657 I python  :    File "/home/magowiz/MEGA/projects/holiday/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/travel_lint/armeabi-v7a/pyowm/commons/cityidregistry.py", line 4, in <module>
07-11 21:32:09.856 15567 15657 I python  :    File "<frozen zipimport>", line 259, in load_module
07-11 21:32:09.856 15567 15657 I python  :    File "/home/magowiz/MEGA/projects/holiday/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/bz2.py", line 19, in <module>
07-11 21:32:09.856 15567 15657 I python  :  ModuleNotFoundError: No module named '_bz2'
07-11 21:32:09.857 15567 15657 I python  : Python for android ended.
07-11 21:32:10.073 15567 15657 D RefBase : #03 pc 0018fabc  /data/app/~~mr9nKN78bpwQ3iMz5gl-IQ==/net.magowiz.travel_lint-tFIgg3I4YMwrR0YJKEFTow==/lib/arm/libpython3.8.so (Py_Exit+28)
```

**Comment by magowiz** [comment]
It happens the same even if I clean `.buildozer` folder and run the entire process using `kivy/buildozer` docker image. Is there a way to include `_bz2` module in python inside generated apk?
