### ISSUE TITLE
error in 

### ISSUE THREAD

**Issue by py928** [kivy/buildozer#1460]

**Comment by py928** [comment]
[INFO]:    Will compile for the following archs: armeabi-v7a, arm64-v8a
[INFO]:    Found Android API target in $ANDROIDAPI: 27
[INFO]:    Available Android APIs are (27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /root/.buildozer/android/platform/android-ndk-r19c
[INFO]:    Found NDK version 19c
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1294, in <module>
    main()
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 728, in __init__
    getattr(self, command)(args)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 144, in wrapper_func
    user_ndk_api=self.ndk_api)
  File "/content/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 423, in prepare_build_environment
    self.ccache = sh.which("ccache")
  File "/usr/local/lib/python3.7/dist-packages/sh.py", line 1524, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.7/dist-packages/sh.py", line 788, in __init__
    self.wait()
  File "/usr/local/lib/python3.7/dist-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.7/dist-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/which ccache

  STDOUT:


  STDERR:

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/python-for-android/pull/2637

ATM, targeting the `develop` branch of `python-for-android` from your `buildozer.spec` is the suggested workaround.

**Comment by KINGMOHIT** [comment]
It's gives value error: read of closed file
