### ISSUE TITLE
error in p4a

### ISSUE THREAD

**Issue by USER4247** [kivy/buildozer#1499]
I had been using buildozer in ubuntu vm , but I ran into this issue . This has never happened before

# Install platform
# Run ['git', 'config', '--get', 'remote.origin.url']
# Cwd /home/xero/camera/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run ['git', 'branch', '-vv']
# Cwd /home/xero/camera/.buildozer/android/platform/python-for-android
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 33, in <module>
    sys.exit(load_entry_point('buildozer==1.4.1.dev0', 'console_scripts', 'buildozer')())
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/__init__.py", line 1024, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/target.py", line 93, in run_commands
    func(args)
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/target.py", line 103, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/__init__.py", line 172, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/targets/android.py", line 692, in install_platform
    self._install_p4a()
  File "/usr/local/lib/python3.10/dist-packages/buildozer-1.4.1.dev0-py3.10.egg/buildozer/targets/android.py", line 751, in _install_p4a
    )[0].split()[1]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by misl6** [comment]
Can you please send the output of the following steps?
```
cd  /home/xero/camera/.buildozer/android/platform/python-for-android
git branch -vv
```

**Comment by Julian-O** [comment]
No reply for 12 months. Closing as Can't Repro
