### ISSUE TITLE
Change the path to libjvm.so

### ISSUE THREAD

**Issue by e-lunev** [kivy/buildozer#1514]
SystemError: Error calling dlopen(b'/usr/java/jre1.8.0_333/jre/lib/amd64/server/libjvm.so': b'/usr/java/jre1.8.0_333/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'

I need to change on /usr/java/jre1.8.0_333/lib/amd64/server/libjvm.so

How can I do it?

**Comment by misl6** [comment]
Hi @e-lunev ,

Can you please share the full log?

**Comment by e-lunev** [comment]
Traceback (most recent call last):
  File "/home/kali/Desktop/android.py", line 1, in <module>
    from jnius import autoclass
  File "/home/kali/.local/lib/python3.10/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/home/kali/.local/lib/python3.10/site-packages/jnius/reflect.py", line 14, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/usr/lib/python3/dist-packages/six.py", line 872, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/usr/java/jre1.8.0_333/jre/lib/amd64/server/libjvm.so': b'/usr/java/jre1.8.0_333/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'

**Comment by misl6** [comment]
When this error is showing up?

**Comment by e-lunev** [comment]
> Когда появляется эта ошибка?

python android.py



from jnius import autoclass
PythonActivity = autoclass('org.renpy.android.PythonActivity')
activity = PythonActivity.mActivity
Context = autoclass('android.content.Context')
vibrator = activity.getSystemService(Context.VIBRATOR_SERVICE)
vibrator.vibrate(10000)  # аргумент указывается в миллисекундах

**Comment by EduardoAlves1901** [comment]
Hello, 
I'm also getting this error. Any news about this?

Thanks in advance.

**Comment by Julian-O** [comment]
Hasty closure. Reopining.
