### ISSUE TITLE
Building cchardet 

### ISSUE THREAD

**Issue by krypterro** [kivy/buildozer#1590]
### Versions

* Python: 3.9.7
* OS: Linux 20.04 / Android 13
* Buildozer: 1.5

### Description

Trying the create an APK for Android 11, 12, and 13, but can't get Buildozer to build a working library for cchardet, even with a recipe.
I've tried each architecture, the APK installs on multiple test phones, but crashes with the cchardet module error below.

### buildozer.spec

Command:
```
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = Pure ChatGPT

# (str) Package name
package.name = purechat

# (str) Package domain (needed for android/ios packaging)
package.domain = org.purechat

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin, venv

# (list) List of exclusions using pattern matching
# Do not prefix with './'
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3==3.9.7, aiohttp==3.8.4, aiosignal==1.3.1, async-timeout==4.0.2, attrs==22.2.0, certifi==2022.12.7, charset-normalizer==3.1.0, docutils==0.19, frozenlist==1.3.3, idna==3.4, Kivy==2.0.0, Kivy-Garden==0.1.5, kivymd==1.1.1, loguru==0.6.0, multidict==6.0.4, openai==0.27.4, Pillow==8.4.0, Pygments==2.14.0, requests==2.28.2, tqdm==4.65.0, urllib3==1.26.15, yarl==1.8.2, cchardet

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/data/icon.png

# (list) Supported orientations
# Valid options are: landscape, portrait, portrait-reverse or landscape-reverse
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

```

### Logs

```
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-04-06 (installed at "/data/user/0/org.purechat.purechat/files/app/_python_bundle/site-packages/kivymd/__init__.pyc")
04-10 04:56:23.339 14574 14595 I python  :  Traceback (most recent call last):
04-10 04:56:23.339 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/requests/compat.py", line 11, in <module>
04-10 04:56:23.340 14574 14595 I python  :  ModuleNotFoundError: No module named 'chardet'
04-10 04:56:23.341 14574 14595 I python  :  
04-10 04:56:23.341 14574 14595 I python  :  During handling of the above exception, another exception occurred:
04-10 04:56:23.341 14574 14595 I python  :  
04-10 04:56:23.341 14574 14595 I python  :  Traceback (most recent call last):
04-10 04:56:23.342 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/app/main.py", line 33, in <module>
04-10 04:56:23.342 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/openai/__init__.py", line 9, in <module>
04-10 04:56:23.343 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/openai/api_resources/__init__.py", line 1, in <module>
04-10 04:56:23.343 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/openai/api_resources/audio.py", line 4, in <module>
04-10 04:56:23.344 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/openai/api_requestor.py", line 22, in <module>
04-10 04:56:23.345 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/requests/__init__.py", line 45, in <module>
04-10 04:56:23.345 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/requests/exceptions.py", line 9, in <module>
04-10 04:56:23.346 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/requests/compat.py", line 13, in <module>
04-10 04:56:23.347 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/charset_normalizer/__init__.py", line 24, in <module>
04-10 04:56:23.347 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/charset_normalizer/api.py", line 5, in <module>
04-10 04:56:23.348 14574 14595 I python  :    File "/home/zino/PyApps/pure/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/purechat/armeabi-v7a/charset_normalizer/cd.py", line 9, in <module>
04-10 04:56:23.348 14574 14595 I python  :  ImportError: dlopen failed: "/data/data/org.purechat.purechat/files/app/_python_bundle/site-packages/charset_normalizer/md.so" is 64-bit instead of 32-bit
04-10 04:56:23.348 14574 14595 I python  : Python for android ended.
04-10 04:56:23.730  1611  3216 I WindowManager: WIN DEATH: Window{3211d83 u0 org.purechat.purechat/org.kivy.android.PythonActivity}
04-10 04:56:23.732  1611  7716 W ActivityManager: Force removing ActivityRecord{c91e5cd u0 org.purechat.purechat/org.kivy.android.PythonActivity t29}: app died, no saved state
04-10 04:56:23.742  1611  1944 W InputDispatcher: channel '3211d83 org.purechat.purechat/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-10 04:56:23.742  1611  1944 E InputDispatcher: channel '3211d83 org.purechat.purechat/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-10 04:56:23.742  1611  3216 W InputDispatcher: Attempted to unregister already unregistered input channel '3211d83 org.purechat.purechat/org.kivy.android.PythonActivity (server)'
04-10 04:56:23.749  1611  3216 V WindowManager: Focus changed from Window{3211d83 u0 org.purechat.purechat/org.kivy.android.PythonActivity} to null
04-10 04:56:23.759   806  2027 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{5aaa993 token=Token{7b17e82 ActivityRecord{c91e5cd u0 org.purechat.purechat/org.kivy.android.PythonActivity t29}}}#0
```

**Comment by krypterro** [comment]
Also, the recipe:
recipes/cchardet/__init__.py
`
from pythonforandroid.recipe import CompiledComponentsPythonRecipe

class CChardetRecipe(CompiledComponentsPythonRecipe):
    version = "2.1.7"  # Replace with the desired version of cchardet
    url = "https://files.pythonhosted.org/packages/source/c/cchardet/cchardet-{version}.tar.gz"
    depends = ["setuptools"]
    call_hostpython_via_targetpython = False
    site_packages_name = "cchardet"

recipe = CChardetRecipe()

`

**Comment by RobertFlatt** [comment]
https://github.com/Android-for-Python/Android-for-Python-Users#64-bit-instead-of-32-bit

**Comment by Julian-O** [comment]
This appears to be a support issue that has been answered.

We try to use GitHub Issues only to track work for developers to do to fix bugs and add new features to Buildozer.

This issue is being closed, because it doesn't describe a bug in Buildozer.

If you have further support questions, please don't post them here. Instead, there is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.
