### ISSUE TITLE
Link for Android NDK is broken, ValueError: read of closed file - android-ndk-r25b-linux-x86_64.zip

### ISSUE THREAD

**Issue by damascene** [kivy/buildozer#1618]
![image](https://github.com/kivy/buildozer/assets/411046/5e3e9863-1264-451e-ba56-1a1ba1c98fd9)

### Versions

* Python:
* OS: `buildozer  latest 31bac91f0bcc   8 days ago     1.2GB
* Buildozer:

### Description

I'm trying to use Docker version of `Buildozer` but the link for Android NDK seems broken `404`.
```
https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip
```

### buildozer.spec
Command:
```sh
docker run -v /home/my_user/buildozer_cache/:/home/user/.buildozer -v $(pwd):/home/user/hostcwd kivy/buildozer android debug
```

Spec file:
```
[app]
title = Test App
package.name = test_app
package.domain = com.gitlab.uak
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf,mo,atlas
source.include_patterns = data/*
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py
requirements =  python3, kivy
icon.filename = %(source.dir)s/data/icon.png
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.api = 33
android.skip_update = False
android.accept_sdk_license = True
android.archs = arm64-v8a, armeabi-v7a
android.allow_backup = True
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0
ios.codesign.allowed = false
[buildozer]
log_level = 2
warn_on_root = 1

```

### Logs

```
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'sh>=1.10, <2.0; sys_platform!="nt"\' \'build\' \'toml\' \'packaging\''
# Cwd None
WARNING: You are using pip version 21.1.1; however, version 23.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
# Apache ANT found at /home/user/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/user/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 25b
# Android NDK is missing, downloading
# Downloading https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip
Traceback (most recent call last):
  File "/home/user/.local/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 170, in prepare_for_build
    self.target.install_platform()
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/targets/android.py", line 670, in install_platform
    self._install_android_ndk()
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/targets/android.py", line 460, in _install_android_ndk
    self.buildozer.download(url,
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 654, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib/python3.8/urllib/request.py", line 1851, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.8/tempfile.py", line 613, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
```

**Comment by damascene** [comment]
Maybe related to this line:
https://github.com/kivy/buildozer/blob/5fda03158160116d4d9e068abc0ee7ff11a8bb1d/buildozer/targets/android.py#L422

Seems Android changed link format?
```
https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip 
https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
```

**Comment by misl6** [comment]
Hi @damascene !

This issue has been fixed via https://github.com/kivy/buildozer/pull/1427

`buildozer` docker image which was available on dockerhub is unmaintained, and usage is currently discouraged.
