### ISSUE TITLE
Problem while buildozer android debug 

### ISSUE THREAD

**Issue by eseymenler** [kivy/buildozer#1654]
Hi everyone, 
I made a django website and i want to make mobile app for my website. So i installed buildozer and made debug but i get this error. I found the solution both web and chatgpt but, it failed. So, how can i fix this? 

[DEBUG]:   -> running download.sh
[DEBUG]:   	fatal: destination path 'external/jpeg' already exists and is not an empty directory.
Exception in thread background thread for pid 94275:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_128: 

  RAN: /Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/jni/SDL2_image/external/download.sh

  STDOUT:
fatal: destination path 'external/jpeg' already exists and is not an empty directory.

  STDERR:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 496, in build_recipes
    recipe.prebuild_arch(arch)
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/sdl2_image/__init__.py", line 21, in prebuild_arch
    shprint(sh.Command("./download.sh"))
  File "/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 915, in next
    self.wait()
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/emre/Library/Python/3.9/lib/python/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_128: 

  RAN: /Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/jni/SDL2_image/external/download.sh

  STDOUT:
fatal: destination path 'external/jpeg' already exists and is not an empty directory.

  STDERR:

# Command failed: ['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=myapp', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/Users/emre/Desktop/xxx/ahasta/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     TERM_PROGRAM = 'Apple_Terminal'
#     SHELL = '/bin/zsh'
#     TERM = 'xterm-256color'
#     TMPDIR = '/var/folders/ww/c9bgnnld2ls15t10kwpmh0yc0000gn/T/'
#     TERM_PROGRAM_VERSION = '447'
#     TERM_SESSION_ID = '14742E09-78BC-4B25-ACFC-6EEA6AF5599C'
#     USER = 'emre'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.w8SLadkAtt/Listeners'
#     PATH = '/Users/emre/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/emre/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin'
#     LaunchInstanceID = 'BDCF75F2-CB5B-4A48-BBC9-E52532741200'
#     __CFBundleIdentifier = 'com.apple.Terminal'
#     PWD = '/Users/emre/desktop/xxx/ahasta'
#     XPC_FLAGS = '0x0'
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '1'
#     HOME = '/Users/emre'
#     LOGNAME = 'emre'
#     SECURITYSESSIONID = '186b3'
#     OLDPWD = '/Users/emre/desktop/xxx/ahasta'
#     HOMEBREW_PREFIX = '/opt/homebrew'
#     HOMEBREW_CELLAR = '/opt/homebrew/Cellar'
#     HOMEBREW_REPOSITORY = '/opt/homebrew'
#     MANPATH = '/opt/homebrew/share/man::'
#     INFOPATH = '/opt/homebrew/share/info:'
#     CONDA_EXE = '/Users/emre/miniconda3/bin/conda'
#     _CE_M = ''
#     _CE_CONDA = ''
#     CONDA_PYTHON_EXE = '/Users/emre/miniconda3/bin/python'
#     CONDA_SHLVL = '0'
#     LANG = 'tr_TR.UTF-8'
#     _ = '/Library/Frameworks/Python.framework/Versions/3.9/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x23:0x18'
#     PACKAGES_PATH = '/Users/emre/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/emre/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/emre/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by eseymenler** [comment]
i fixed it.  The problem is  STDOUT:
fatal: destination path 'external/jpeg' already exists and is not an empty directory.

I deleted this file and it started again, and then i get cython problem. And then i downgrade the cython version pip install cython==0.29.33 , so it passed this problem, and then i got new error, main.py error, i then i made a new empty file as a name main.py to the main directory. At least it created the apk file. 
Yes, i made it :)
