### ISSUE TITLE
automatic installation of android sdk fails due to unicode parsing error

### ISSUE THREAD

**Issue by ToddG** [kivy/buildozer#166]
Machine
==============================
```bash
[todd@dino ~]$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

Buildozer Version
==============================
```bash
commit c163a14417d8ab2a117a875efb6bb89410b8994f
Merge: 043c7c1 41dae4d
Author: Mathieu Virbel <mat@kivy.org>
Date:   Sat Nov 22 17:25:18 2014 +0100

    Merge pull request #163 from olymk2/master
    
    fix build error and allow redirecting build folder
```

REPRO
==============================
```bash
# create a test project
mkdir test01
cd test01
buildozer init

#create a test main.py
```

main.py
```python
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```

```bash
# build
[todd@dino test01]$ buildozer --verbose android debug deploy run 2>&1 | tee build.logex
```
ERROR
==============================
Fails to install the android sdk with:
```bash
 UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1178: ordinal not in range(128)
```

Workaround
==============================
```bash
cd /home/todd/.buildozer/android/platform/android-sdk-21/tools/
android update sdk -u
```

Full Log File
==============================
```bash
[39m[0m[36m# Check configuration tokens[39m[0m
[39m[0m[36m# Ensure build layout[39m[0m
[39m[0m[36m# Check configuration tokens[39m[0m
[39m[0m[36m# Preparing build[39m[0m
[39m[0m[36m# Check requirements for android[39m[0m
[39m[0m[30m[2m# Run 'dpkg --version'[39m[0m
[39m[0m[30m[2m# Cwd None[39m[0m
Debian `dpkg' package management program version 1.17.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
[39m[0m[30m[2m# Search for Git (git)[39m[0m
[39m[0m[30m[2m#  -> found at /usr/bin/git[39m[0m
[39m[0m[30m[2m# Search for Cython (cython)[39m[0m
[39m[0m[30m[2m#  -> found at /usr/local/bin/cython[39m[0m
[39m[0m[30m[2m# Search for Java compiler (javac)[39m[0m
[39m[0m[30m[2m#  -> found at /media/RHINO/opt/java/java6/jdk1.6.0_45/bin/javac[39m[0m
[39m[0m[30m[2m# Search for Java keytool (keytool)[39m[0m
[39m[0m[30m[2m#  -> found at /media/RHINO/opt/java/java6/jdk1.6.0_45/bin/keytool[39m[0m
[39m[0m[36m# Install platform[39m[0m
[39m[0m[36m# Apache ANT found at /home/todd/.buildozer/android/platform/apache-ant-1.8.4[39m[0m
[39m[0m[36m# Android SDK found at /home/todd/.buildozer/android/platform/android-sdk-21[39m[0m
[39m[0m[36m# Android NDK found at /home/todd/.buildozer/android/platform/android-ndk-r9c[39m[0m
[39m[0m[30m[2m# Run '/home/todd/.buildozer/android/platform/android-sdk-21/tools/android list sdk -u -e'[39m[0m
[39m[0m[30m[2m# Cwd /home/todd/.buildozer/android/platform[39m[0m
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-9.xml
  Validate XML: https://dl-ssl.google.com/android/repository/repository-8.xml
  Parse XML:    https://dl-ssl.google.com/android/repository/repository-8.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/addon-6.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon-6.xml
  Parse XML:    https://dl-ssl.google.com/android/repository/addon-6.xml
  Fetching URL: https://dl-ssl.google.com/glass/gdk/addon.xml
  Validate XML: https://dl-ssl.google.com/glass/gdk/addon.xml
  Parse XML:    https://dl-ssl.google.com/glass/gdk/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Packages available for installation or update: 23
----------
id: 1 or "tools"
     Type: Tool
     Desc: Android SDK Tools, revision 24.0.1
----------
id: 2 or "platform-tools"
     Type: PlatformTool
     Desc: Android SDK Platform-tools, revision 20
----------
id: 3 or "build-tools-19.1.0"
     Type: BuildTool
     Desc: Android SDK Build-tools, revision 19.1
----------
id: 4 or "doc-19"
     Type: Doc
     Desc: Documentation for Android SDK, API 19, revision 2
----------
id: 5 or "android-19"
     Type: Platform
     Desc: Android SDK Platform 4.4.2
           Revision 3
----------
id: 6 or "android-18"
     Type: Platform
     Desc: Android SDK Platform 4.3
           Revision 2
----------
id: 7 or "android-17"
     Type: Platform
     Desc: Android SDK Platform 4.2.2
           Revision 2
----------
id: 8 or "android-16"
     Type: Platform
     Desc: Android SDK Platform 4.1.2
           Revision 4
----------
id: 9 or "android-15"
     Type: Platform
     Desc: Android SDK Platform 4.0.3
           Revision 3
----------
id: 10 or "sample-19"
     Type: Sample
     Desc: Samples for SDK API 19, revision 5
----------
id: 11 or "sample-18"
     Type: Sample
     Desc: Samples for SDK API 18, revision 1
----------
id: 12 or "sample-17"
     Type: Sample
     Desc: Samples for SDK API 17, revision 1
----------
id: 13 or "sample-16"
     Type: Sample
     Desc: Samples for SDK API 16, revision 1
----------
id: 14 or "sample-15"
     Type: Sample
     Desc: Samples for SDK API 15, revision 2
----------
id: 15 or "sample-14"
     Type: Sample
     Desc: Samples for SDK API 14, revision 2
----------
id: 16 or "sample-13"
     Type: Sample
     Desc: Android SDK Samples for Android API 13, revision 1
----------
id: 17 or "sample-12"
     Type: Sample
     Desc: Android SDK Samples for Android API 12, revision 1
----------
id: 18 or "sample-11"
     Type: Sample
     Desc: Android SDK Samples for Android API 11, revision 1
----------
id: 19 or "sample-10"
     Type: Sample
     Desc: Android SDK Samples for Android API 10, revision 1
----------
id: 20 or "sample-8"
     Type: Sample
     Desc: Android SDK Samples for Android API 8, revision 1
----------
id: 21 or "sample-7"
     Type: Sample
     Desc: Android SDK Samples for Android API 7, revision 1
----------
id: 22 or "addon-google_gdk-google-19"
     Type: Addon
     Desc: Glass Development Kit Preview, Android API 19, revision 11
           By Google Inc.
           Preview of the Glass Development Kit
           Requires SDK Platform Android API 19
----------
id: 23 or "extra-android-support"
     Type: Extra
     Desc: Android Support Library, revision 19.1
           By Android
           Install path: extras/android/support
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-9.xml
  Validate XML: https://dl-ssl.google.com/android/repository/repository-8.xml
  Parse XML:    https://dl-ssl.google.com/android/repository/repository-8.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/addon-6.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon-6.xml
  Parse XML:    https://dl-ssl.google.com/android/repository/addon-6.xml
  Fetching URL: https://dl-ssl.google.com/glass/gdk/addon.xml
  Validate XML: https://dl-ssl.google.com/glass/gdk/addon.xml
  Parse XML:    https://dl-ssl.google.com/glass/gdk/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Packages available for installation or update: 23
----------
id: 1 or "tools"
     Type: Tool
     Desc: Android SDK Tools, revision 24.0.1
----------
id: 2 or "platform-tools"
     Type: PlatformTool
     Desc: Android SDK Platform-tools, revision 20
----------
id: 3 or "build-tools-19.1.0"
     Type: BuildTool
     Desc: Android SDK Build-tools, revision 19.1
----------
id: 4 or "doc-19"
     Type: Doc
     Desc: Documentation for Android SDK, API 19, revision 2
----------
id: 5 or "android-19"
     Type: Platform
     Desc: Android SDK Platform 4.4.2
           Revision 3
----------
id: 6 or "android-18"
     Type: Platform
     Desc: Android SDK Platform 4.3
           Revision 2
----------
id: 7 or "android-17"
     Type: Platform
     Desc: Android SDK Platform 4.2.2
           Revision 2
----------
id: 8 or "android-16"
     Type: Platform
     Desc: Android SDK Platform 4.1.2
           Revision 4
----------
id: 9 or "android-15"
     Type: Platform
     Desc: Android SDK Platform 4.0.3
           Revision 3
----------
id: 10 or "sample-19"
     Type: Sample
     Desc: Samples for SDK API 19, revision 5
----------
id: 11 or "sample-18"
     Type: Sample
     Desc: Samples for SDK API 18, revision 1
----------
id: 12 or "sample-17"
     Type: Sample
     Desc: Samples for SDK API 17, revision 1
----------
id: 13 or "sample-16"
     Type: Sample
     Desc: Samples for SDK API 16, revision 1
----------
id: 14 or "sample-15"
     Type: Sample
     Desc: Samples for SDK API 15, revision 2
----------
id: 15 or "sample-14"
     Type: Sample
     Desc: Samples for SDK API 14, revision 2
----------
id: 16 or "sample-13"
     Type: Sample
     Desc: Android SDK Samples for Android API 13, revision 1
----------
id: 17 or "sample-12"
     Type: Sample
     Desc: Android SDK Samples for Android API 12, revision 1
----------
id: 18 or "sample-11"
     Type: Sample
     Desc: Android SDK Samples for Android API 11, revision 1
----------
id: 19 or "sample-10"
     Type: Sample
     Desc: Android SDK Samples for Android API 10, revision 1
----------
id: 20 or "sample-8"
     Type: Sample
     Desc: Android SDK Samples for Android API 8, revision 1
----------
id: 21 or "sample-7"
     Type: Sample
     Desc: Android SDK Samples for Android API 7, revision 1
----------
id: 22 or "addon-google_gdk-google-19"
     Type: Addon
     Desc: Glass Development Kit Preview, Android API 19, revision 11
           By Google Inc.
           Preview of the Glass Development Kit
           Requires SDK Platform Android API 19
----------
id: 23 or "extra-android-support"
     Type: Extra
     Desc: Android Support Library, revision 19.1
           By Android
           Install path: extras/android/support

[39m[0m[30m[2m# Run (expect) '/home/todd/.buildozer/android/platform/android-sdk-21/tools/android update sdk -u -a -t tools,platform-tools'[39m[0m
[39m[0m[30m[2m# Cwd None[39m[0m
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-9.xml
  Validate XML: https://dl-ssl.google.com/android/repository/repository-8.xml
  Parse XML:    https://dl-ssl.google.com/android/repository/repository-8.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/addon-6.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon-6.xml
  Parse XML:    https://dl-ssl.google.com/android/repository/addon-6.xml
  Fetching URL: https://dl-ssl.google.com/glass/gdk/addon.xml
  Validate XML: https://dl-ssl.google.com/glass/gdk/addon.xml
  Parse XML:    https://dl-ssl.google.com/glass/gdk/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
  Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
-------------------------------
License id: android-sdk-license-5be876d5
Used by: 
 - Android SDK Tools, revision 24.0.1
  - Android SDK Platform-tools, revision 20
-------------------------------
To get started with the Android SDK, you must agree to the following terms and conditions.

This is the Android SDK License Agreement (the "License Agreement").

1. Introduction

1.1 The Android SDK (referred to in the License Agreement as the "SDK" and specifically including the Android system files, packaged APIs, and SDK library files and tools , if and when they are made available) is licensed to you subject to the terms of the License Agreement. The License Agreement forms a legally binding contract between you and Google in relation to your use of the SDK.

1.2 "Android" means the Android software stack for devices, as made available under the Android Open Source Project, which is located at the following URL: http://source.android.com/, as updated from time to time.

1.3 "Google" means Google Inc., a Delaware corporation with principal place of business at 1600 Amphitheatre Parkway, Mountain View, CA 94043, United States.

2. Accepting the License Agreement

2.1 In order to use the SDK, you must first agree to the License Agreement. You may not use the SDK if you do not accept the License Agreement.

2.2 By clicking to accept and/or using the SDK, you hereby agree to the terms of the License Agreement.

2.3 You may not use the SDK and may not accept the License Agreement if you are a person barred from receiving the SDK under the laws of the United States or other countries including the country in which you are resident or from which you use the SDK.

2.4 If you will use the SDK internally within your company or organization you agree to be bound by the License Agreement on behalf of your employer or other entity, and you represent and warrant that you have full legal authority to bind your employer or such entity to the License Agreement. If you do not have the requisite authority, you may not accept the Liceny
se Agreement or use the SDK on behalf of your employer or other entity.

3. SDK License from Google

3.1 Subject to the terms of the License Agreement, Google grants you a royalty-free, non-assignable, non-exclusive, non-sublicensable, limited, revocable license to use the SDK, personally or internally within your company or organization, solely to develop and distribute applications to run on the Android platform.

3.2 You agree that Google or third parties own all legal right, title and interest in and to the SDK, including any Intellectual Property Rights that subsist in the SDK. "Intellectual Property Rights" means any and all rights under patent law, copyright law, trade secret law, trademark law, and any and all other proprietary rights. Google reserves all rights not expressly granted to you.

3.3 You may not use the SDK for any purpose not expressly permitted by the License Agreement. Except to the extent required by applicable third party licenses, you may not: (a) copy (except for backup purposes), modify, adapt, redistribute, decompile, reverse engineer, disassemble, or create derivative works of the SDK or any part of the SDK; or (b) load any part of the SDK onto a mobile handset or any other hardware device except a personal computer, combine any part of the SDK with other software, or distribute any software or device incorporating a part of the SDK.

3.4 You agree that you will not take any actions that may cause or result in the fragmentation of Android, including but not limited to distributing, participating in the creation of, or promoting in any way a software development kit derived from the SDK.

3.5 Use, reproduction and distribution of components of the SDK licensed under an open source software license are governed solely by the terms of that open source software license and not the License Agreement. You agree to remain a licensee in good standing in regard to such open source software licenses under all the rights granted and to refrain from any actions that may terminate, suspend, or breach such rights.

3.6 You agree that the form and nature of the SDK that Google provides may change without prior notice to you and that future versions of the SDK may be incompatible with applications developed on previous versions of the SDK. You agree that Google may stop (permanently or temporarily) providing the SDK (or any features within the SDK) to you or to users generally at Google's sole discretion, without prior notice to you.

3.7 Nothing in the License Agreement gives you a right to use any of Google's trade names, trademarks, service marks, logos, domain names, or other distinctive brand features.

3.8 You agree that you will not remove, obscure, or alter any proprietary rights notices (including copyright and trademark notices) that may be affixed to or contained within the SDK.

4. Use of the SDK by You

4.1 Google agrees that nothing in the License Agreement gives Google any right, title or interest from you (or your licensors) under the License Agreement in or to any software applications that you develop using the SDK, including any intellectual property rights that subsist in those applications.

4.2 You agree to use the SDK and write applications only for purposes that are permitted by (a) the License Agreement, and (b) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions (including any laws regarding the export of data or software to and from the United States or other relevant countries).

4.3 You agree that if you use the SDK to develop applications, you will protect the privacy and legal rights of users. If users provide you with user names, passwords, or other login information or personal information, you must make the users aware that the information will be available to your application, and you must provide legally adequate privacy notice and protection for those users. If your application stores personal or sensitive information provided by users, it must do so securely. If users provide you with Google Account information, your application may only use that information to access the user's Google Account when, and for the limited purposes for which, each user has given you permission to do so.

4.4 You agree that you will not engage in any activity with the SDK, including the development or distribution of an application, that interferes with, disrupts, damages, or accesses in an unauthorized manner the servers, networks, or other properties or services of Google or any third party.

4.5 You agree that you are solely responsible for (and that Google has no responsibility to you or to any third party for) any data, content, or resources that you create, transmit or display through Android and/or applications for Android, and for the consequences of your actions (including any loss or damage which Google may suffer) by doing so.

4.6 You agree that you are solely responsible for (and that Google has no responsibility to you or to any third party for) any breach of your obligations under the License Agreement, any applicable third party contract or Terms of Service, or any applicable law or regulation, and for the consequences (including any loss or damage which Google or any third party may suffer) of any such breach.

5. Your Developer Credentials

5.1 You agree that you are responsible for maintaining the confidentiality of any developer credentials that may be issued to you by Google or which you may choose yourself and that you will be solely responsible for all applications that are developed under your developer credentials.

6. Privacy and Information

6.1 In order to continually innovate and improve the SDK, Google may collect certain usage statistics from the software including but not limited to a unique identifier, associated IP address, version number of the software, and information on which tools and/or services in the SDK are being used and how they are being used. Before any of this information is collected, the SDK will notify you and seek your consent. If you withhold consent, the information will not be collected.

6.2 The data collected is examined in the aggregate to improve the SDK and is maintained in accordance with Google's Privacy Policy located at http://www.google.com/policies/privacy/.

7. Third Party Applications

7.1 If you use the SDK to run applications developed by a third party or that access data, content or resources provided by a third party, you agree that Google is not responsible for those applications, data, content, or resources. You understand that all data, content or resources which you may access through such third party applications are the sole responsibility of the person from which they originated and that Google is not liable for any loss or damage that you may experience as a result of the use or access of any of those third party applications, data, content, or resources.

7.2 You should be aware the data, content, and resources presented to you through such a third party application may be protected by intellectual property rights which are owned by the providers (or by other persons or companies on their behalf). You may not modify, rent, lease, loan, sell, distribute or create derivative works based on these data, content, or resources (either in whole or in part) unless you have been specifically given permission to do so by the relevant owners.

7.3 You acknowledge that your use of such third party applications, data, content, or resources may be subject to separate terms between you and the relevant third party.

8. Using Google APIs

8.1 Google APIs

8.1.1 If you use any API to retrieve data from Google, you acknowledge that the data may be protected by intellectual property rights which are owned by Google or those parties that provide the data (or by other persons or companies on their behalf). Your use of any such API may be subject to additional Terms of Service. You may not modify, rent, lease, loan, sell, distribute or create derivative works based on this data (either in whole or in part) unless allowed by the relevant Terms of Service.

8.1.2 If you use any API to retrieve a user's data from Google, you acknowledge and agree that you shall retrieve data only with the user's explicit consent and only when, and for the limited purposes for which, the user has given you permission to do so.

9. Terminating the License Agreement

9.1 The License Agreement will continue to apply until terminated by either you or Google as set out below.

9.2 If you want to terminate the License Agreement, you may do so by ceasing your use of the SDK and any relevant developer credentials.

9.3 Google may at any time, terminate the License Agreement, with or without cause, upon notice to you.

9.4 The License Agreement will automatically terminate without notice or other action when Google ceases to provide the SDK or certain parts of the SDK to users in the country in which you are resident or from which you use the service.

9.5 When the License Agreement is terminated, the license granted to you in the License Agreement will terminate, you will immediately cease all use of the SDK, and the provisions of paragraphs 10, 11, 12 and 14 shall survive indefinitely.

10. DISCLAIMERS

10.1 YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SDK IS AT YOUR SOLE RISK AND THAT THE SDK IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND FROM GOOGLE.

10.2 YOUR USE OF THE SDK AND ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SDK IS AT YOUR OWN DISCRETION AND RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH USE. WITHOUT LIMITING THE FOREGOING, YOU UNDERSTAND THAT THE SDK MAY CONTAIN ERRORS, DEFECTS AND SECURITY VULNERABILITIES THAT CAN RESULT IN SIGNIFICANT DAMAGE, INCLUDING THE COMPLETraceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 961, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 95, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 157, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 394, in install_platform
    self._install_android_packages()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 350, in _install_android_packages
    self._android_update_sdk('tools,platform-tools')
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 309, in _android_update_sdk
    index = child.expect([EOF, '[y/n]: '])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/libs/pexpect.py", line 1311, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/libs/pexpect.py", line 1325, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/libs/pexpect.py", line 1378, in expect_loop
    c = self.read_nonblocking (self.maxread, timeout)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/libs/pexpect.py", line 837, in read_nonblocking
    self.logfile.write (s.decode(encoding='UTF-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1178: ordinal not in range(128)
```

**Comment by tito** [comment]
I remember fixing it. Please reopen if it's still happening.
