### ISSUE TITLE
No such file or directory: 'src/org/renpy/android/Configuration.java' when building apk

### ISSUE THREAD

**Issue by Sharas-** [kivy/buildozer#173]
In Version 0.27dev, when running
buildozer -v android debug
getting: 

Command failed: /usr/bin/python build.py --name 'kivy test' --version 0.0.1 --package org.test.kivy-test --private /var/src/.buildozer/android/app --sdk 24.0.2 --minsdk 8 --orientation sensor --window debug

full log: http://pastebin.com/TSpn4Evr
It is not because 32 bit android sdk tools on 64 bit os, i think. 
When I run build.py script manually I get:

Traceback (most recent call last):
 File "./.buildozer/android/platform/python-for-android/dist/kivy-test/build.py", line 497, in <module>
    make_package(args)
  File "./.buildozer/android/platform/python-for-android/dist/kivy-test/build.py", line 283, in make_package
    args=args)
  File "./.buildozer/android/platform/python-for-android/dist/kivy-test/build.py", line 71, in render
    f = file(dest, 'wb')
IOError: [Errno 2] No such file or directory: 'src/org/renpy/android/Configuration.java'

Although file Configuration.java exists under ./.buildozer/android/platform/python-for-android/dist/kivy-test/src/org/renpy/android/Configuration.java
##

**Comment by AndreMiras** [comment]
I believe this is fixed with all the refactoring we had since then
