### ISSUE TITLE
sudo buildozer Fails

### ISSUE THREAD

**Issue by FeralBytes** [kivy/buildozer#174]
Yes I know you are not susposed to run Buildozer as root. But it still should not crash with a traceback.
```
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.26', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.4/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/buildozer/__init__.py", line 946, in run_command
    self.check_root()
  File "/usr/local/lib/python3.4/dist-packages/buildozer/__init__.py", line 985, in check_root
    cont = input('Are you sure you want to continue [y/n]? ')
UnboundLocalError: local variable 'input' referenced before assignment
```
The lines that actually cause this error are 973-976:
```python
        try:  # ensure same result in python2 and python3
            input = raw_input
        except NameError:
            pass
```
I recommend lines 973-976 become:
```python
        try:  # ensure same result in python2 and python3
            input_func = raw_input
        except NameError:
            input_func = input
```
And line 985 becomes:
```python
cont = input_func('Are you sure you want to continue [y/n]? ')
```

**Comment by tito** [comment]
It's weird, both works on my installation with python 2 or 3...
