### ISSUE TITLE
Android build fails due to openssl 1.1.1 is desupported

### ISSUE THREAD

**Issue by TechLearner18** [kivy/buildozer#1762]
### Versions

* Python: 3.8.2
* OS: macOS Sonoma 14.2.1
* Buildozer: 1.5.0

### Description

Trying to create an android build using buildozer. Upon investigation found that openssl has deprecated version 1.1.1
here's the note from openssl site. How do we fix this and get the latest version?

Note: The latest stable version is the 3.2 series supported until 23rd November 2025. Also [available](https://www.openssl.org/support/contracts.html) is the 3.1 series supported until 14th March 2025, and the 3.0 series which is a Long Term Support (LTS) version and is supported until 7th September 2026. All older versions (including 1.1.1, 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used. Users of these older versions are encouraged to upgrade to 3.2 or 3.0 as soon as possible. Extended support for 1.1.1 and 1.0.2 to gain access to security fixes for those versions is available.

### buildozer.spec
Command:

buildozer android debug logcat

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

[INFO]:    Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1262, in <module>
    main()
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 680, in __init__
    getattr(self, command)(args)
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 99, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 158, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 482, in build_recipes
    recipe.download_if_necessary()
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 349, in download_if_necessary
    self.download()
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 399, in download
    self.download_file(self.versioned_url, filename)
  File "/Users/techlearner/kivyapp/pocketdict/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 203, in download_file
    urlretrieve(url, target, report_hook)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Download failed: HTTP Error 404: Not Found; retrying in 1 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 2 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 4 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 8 second(s)...# Command failed:

**Comment by misl6** [comment]
https://github.com/kivy/python-for-android/pull/2958 fixes it, please set `openssl==1.1.1w` as a workaround.
