### ISSUE TITLE
Cannot build android on mac due to openssl 

### ISSUE THREAD

**Issue by hemna** [kivy/buildozer#1872]
Trying to run 

buildozer -v android release

...

```
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1245, in <module>
    main()
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 17, in main
    from pythonforandroid.toolchain import ToolchainCL
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 25, in <module>
    check()
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/checkdependencies.py", line 69, in check
    check_and_install_default_prerequisites()
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py", line 404, in check_and_install_default_prerequisites
    prerequisite.install()
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py", line 60, in install
    self.darwin_installer()
  File "/Users/I530566/devel/mine/hamradio/kivy/AprsChat/.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py", line 285, in darwin_installer
    subprocess.check_output(["brew", "install", self.homebrew_formula_name])
  File "/Users/I530566/.pyenv/versions/3.12.7/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I530566/.pyenv/versions/3.12.7/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['brew', 'install', 'openssl@1.1']' returned non-zero exit status 1.
# This buildozer version requires a python-for-android version with AAB (Android App Bundle) support. Please update your pinned version accordingly.
# Check configuration tokens
```

**Comment by hemna** [comment]
```
❯ brew install -f openssl@1.1
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.
```

**Comment by THartmanOfTheRedwoods** [comment]
I am also running into this issue on mac. Same error, same reason. Any reason we can't use a more modern version of OpenSSL?

**Comment by THartmanOfTheRedwoods** [comment]
Jus FYI, I edited the following file:

.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py

I changed the openssl version as follows:

class OpenSSLPrerequisite(Prerequisite):
    name = "openssl"
    # homebrew_formula_name = "openssl@1.1"
    homebrew_formula_name = "openssl@3"

i.e. I simply updated the homebrew_formula_name to the current openssl version for homebrew, and my compile and build worked. I was able to build my app onto my device without any issue.

Obviously this is not a permanent fix @hemna, but it allowed me to get passed the mac build hurdle.

**Comment by kuzeyron** [comment]
As someone on [Discord](https://chat.kivy.org/) mentioned. Mac has disabled OpenSSL 1.1.
