### ISSUE TITLE
kivy examples seem to need __version__

### ISSUE THREAD

**Issue by stuaxo** [kivy/buildozer#236]
I tried building some and it dies because __version__ is missing

https://github.com/kivy/kivy/issues/3689

```
----------
id: 155 or "extra-google-simulators"
     Type: Extra
     Desc: Android Auto API Simulators, revision 1
           By Google Inc.
           Android Auto API testing simulators
           Install path: extras/google/simulators
----------
id: 156 or "extra-google-webdriver"
     Type: Extra
     Desc: Google Web Driver, revision 2
           By Google Inc.
           WebDriver
           Install path: extras/google/webdriver

# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Distribution compiled.
# Build the application #1
# Package the application
Traceback (most recent call last):
  File "/usr/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.31.dev0', 'console_scripts', 'buildozer')()
  File "/usr/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/buildozer/__init__.py", line 987, in run_command
    self.target.run_commands(args)
  File "/usr/lib/python2.7/dist-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/usr/lib/python2.7/dist-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/usr/lib/python2.7/dist-packages/buildozer/__init__.py", line 198, in build
    self.target.build_package()
  File "/usr/lib/python2.7/dist-packages/buildozer/targets/android.py", line 583, in build_package
    version = self.buildozer.get_version()
  File "/usr/lib/python2.7/dist-packages/buildozer/__init__.py", line 681, in get_version
    ' (looking for `{1}`)'.format(fn, regex))
Exception: Unable to find capture version in ./main.py
 (looking for `__version__ = ['"](.*)['"]`)

```

**Comment by stuaxo** [comment]
(tried no the audio, pictures and shader examples)

**Comment by dessant** [comment]
@stuaxo there was an undesired default in the spec file, see the commit above.

**Comment by stuaxo** [comment]
Awesome, thanks :)
