### ISSUE TITLE
Trouble building for older android versions

### ISSUE THREAD

**Issue by stuaxo** [kivy/buildozer#240]
I was trying to build for an older android version - so I used these settings:
```
# (int) Android API to use
android.api = 14

# (int) Minimum API required
android.minapi = 8

# (int) Android SDK version to use
android.sdk = 20
# (str) Android NDK version to use
android.ndk = 9
```

This was the output:
```
$ buildozer android debug run
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
# Apache ANT found at /home/stu/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/stu/.buildozer/android/platform/android-sdk-20
Traceback (most recent call last):
  File "/mnt/data/home/stu/.virtualenvs/3d/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.31.dev0', 'console_scripts', 'buildozer')()
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/__init__.py", line 987, in run_command
    self.target.run_commands(args)
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/target.py", line 95, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/__init__.py", line 162, in prepare_for_build
    self.target.install_platform()
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/targets/android.py", line 473, in install_platform
    self._install_android_ndk()
  File "/mnt/data/home/stu/projects/external/buildozer/buildozer/targets/android.py", line 271, in _install_android_ndk
    _version = re.search('(.+?)[a-z]', self.android_ndk_version).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

O/T - is there a page listing which settings work for various minimum sdk settings ?

**Comment by tito** [comment]
Hi, there is no such page, but feel free to start one. But over the time, some command might not work, as android ecosystem and requirements changes from times to times, and so there is no way to have a minimum requirement that will always work. (FYI, i was using the same as you before, and it stopped working on day.)

Currently, i'm just setting android.minapi = 14, and all the others variables are the defaults. (don't set it!)
