### ISSUE TITLE
buildozer help fail

### ISSUE THREAD

**Issue by pat1** [kivy/buildozer#285]
with git 0.32dev

```
buildozer help
# Check configuration tokens
Usage:
    buildozer [--profile <name>] [--verbose] [target] <command>...
    buildozer --version

Available targets:
  android            Android target, based on python-for-android project
Traceback (most recent call last):
  File "/usr/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.32dev', 'console_scripts', 'buildozer')()
  File "/usr/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 976, in run_command
    getattr(self, cmd)(*args)
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 1037, in cmd_help
    self.usage()
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 892, in usage
    doc = m.__doc__.strip().splitlines()[0].strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by kmonson** [comment]
I can confirm this.

**Comment by mikeyjkmo** [comment]
I'm also seeing this problem. I've just installed the latest dev version with
`pip install https://github.com/kivy/buildozer/archive/master.zip`

**Comment by kived** [comment]
The `android_new` module doesn't have a docstring. Everything else should work with buildozer, other than this usage message.

Docstrings should only be used for documenting code, not for usage messages and such. They are also stripped out of optimized builds, which is a good reason not to rely on them.
