### ISSUE TITLE
Py3: 'Buildozer' object has no attribute 'critical'

### ISSUE THREAD

**Issue by udiboy1209** [kivy/buildozer#297]
I built and installed buildozer in a venv successfully with python3. But when I run `buildozer android debug` I get this error

```
Traceback (most recent call last):
  File "/home/udiboy/.apps/virtualenv/kivy3/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.32.dev0', 'console_scripts', 'buildozer')()
  File "/home/udiboy/.apps/virtualenv/kivy3/lib/python3.4/site-packages/buildozer-0.32.dev0-py3.4.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/udiboy/.apps/virtualenv/kivy3/lib/python3.4/site-packages/buildozer-0.32.dev0-py3.4.egg/buildozer/__init__.py", line 986, in run_command
    self.target.run_commands(args)
  File "/home/udiboy/.apps/virtualenv/kivy3/lib/python3.4/site-packages/buildozer-0.32.dev0-py3.4.egg/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/home/udiboy/.apps/virtualenv/kivy3/lib/python3.4/site-packages/buildozer-0.32.dev0-py3.4.egg/buildozer/target.py", line 95, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/home/udiboy/.apps/virtualenv/kivy3/lib/python3.4/site-packages/buildozer-0.32.dev0-py3.4.egg/buildozer/__init__.py", line 162, in prepare_for_build
    self.target.install_platform()
  File "/home/udiboy/.apps/virtualenv/kivy3/lib/python3.4/site-packages/buildozer-0.32.dev0-py3.4.egg/buildozer/targets/android.py", line 472, in install_platform
    self.buildozer.critical(
AttributeError: 'Buildozer' object has no attribute 'critical'
```

**Comment by pythonic64** [comment]
I have the same issue with Python2. I have installed buildozer from [master branch](https://github.com/kivy/buildozer/commit/37f4dac9e7b5d953baa80577f426d616e4faa46a).

**Comment by udiboy1209** [comment]
I can confirm that. This isn't just a  Py3 issue.

**Comment by pythonic64** [comment]
Pull request for this issue https://github.com/kivy/buildozer/pull/288.

**Comment by kived** [comment]
PR #288 has been merged, so I'm closing this.
