### ISSUE TITLE
Building APK file results in an error: IOError: [Errno 2] No such file or directory: 'name_project/project.properties'

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/buildozer#306]
Building APK file results in an error (Ubuntu 14.10, 32-bit, Kivy 1.9.1):

Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.31', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/**init**.py", line 987, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/**init**.py", line 198, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 604, in build_package
    self._update_libraries_references(dist_dir)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 774, in _update_libraries_references
    with io.open(project_fn, 'w', encoding='utf-8') as fd:

IOError: [Errno 2] No such file or directory: /home/zavulon/Programming/Projects/Python2.7/Mobile/Kivy/HeaTDV4A/.buildozer/android/platform/python-for-android/dist/HeaTDV4A/project.properties

How do I fix this error?
##

**Comment by AndreMiras** [comment]
I also had this issue recently, I didn't investigate further, but I could workaround by creating the two missing sub-directories.
The error was:
```
# Captured version: 2017.1206
Traceback (most recent call last):
  File "/home/andre/.local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 669, in build_package
    self._update_libraries_references(dist_dir)
  File "/home/andre/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 866, in _update_libraries_references
    with io.open(project_fn, 'w', encoding='utf-8') as fd:
IOError: [Errno 2] No such file or directory: '/home/andre/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/project.properties'
```
Making the `mkdir -p .buildozer/android/platform/build/dists/pywallet/` made it.
Additional infos:
- buildozer==0.34
- python2 host and target
- `p4a.branch = master`

**Comment by AndreMiras** [comment]
I believe this is fixed with recent p4a updates.
Feel free to re-open otherwise

**Comment by hematogender** [comment]
Had this issue, too. The latest python, `p4a.branch = develop`, buildozer 1.2.0.
Fixed by `mkdir -p .buildozer/android/platform/build/dists/appname__arch`

**Comment by xXpeira12** [comment]
> Had this issue, too. The latest python, `p4a.branch = develop`, buildozer 1.2.0.
> Fixed by `mkdir -p .buildozer/android/platform/build/dists/appname__arch`

It can fix.
