### ISSUE TITLE
buildozer not working

### ISSUE THREAD

**Issue by deounix** [kivy/buildozer#350]
I'm trying to build android app with buildozer I'm working in ubuntu 12.04 64bit
I have installed every thing and when I'm trying to build my app with : buildozer android debug

I get this error :

first this error :

```
arm-linux-androideabi-gcc: error: kivy/graphics/opengl.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
 error: command 'ccache' failed with exit status 1
```

and at the end this error :

```
assets/private.mp3: /home/deounix/.buildozer/android/app/cloud-upload.png
Traceback (most recent call last):
  File "build.py", line 517, in <module>
    make_package(args)
  File "build.py", line 365, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
# Command failed: python build.py --name 'deounix test' --version 0.1 --package org.test.deounix --sdk 19 --minsdk 9 --private /home/deounix/.buildozer/android/app --orientation landscape debug
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

What is the problem here ?

**Comment by deounix** [comment]
This solve my problem on ubuntu 12.04

sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 zlib1g zlib1g:i386

**Comment by ericklxvi** [comment]
Try
# (int) Android SDK version to use 
android.sdk = 24
it works for me.
