### ISSUE TITLE
Cant compile apk with sqlite3 (using python3 crystax)

### ISSUE THREAD

**Issue by Kozubi** [kivy/buildozer#359]
Here is a part of the log

```
raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: "/bin/bash -c source venv/bin/activate && env CC=/bin/false CXX=/bin/false PYTHONPATH=/home/marcin/Desktop/ApkaGrazki/.buildozer/android/platform/build/build/python-installs/myapp pip install --target '/home/marcin/Desktop/ApkaGrazki/.buildozer/android/platform/build/build/python-installs/myapp' --no-deps -r requirements.txt"

  STDOUT:
The directory '/home/marcin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/marcin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting sqlite3 (from -r requirements.txt (line 1))
/home/marcin/Desktop/ApkaGrazki/.buildozer/android/platform/build/build/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/marcin/Desktop/ApkaGrazki/.buildozer/android/platform/build/build/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement sqlite3 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for sqlite3 (from -r requirements.txt (line 1))
```
##

**Comment by inclement** [comment]
It looks like we don't yet have a recipe for sqlite3 in the new toolchain, and it would need to be a little different for python3 anyway.

**Comment by nesergen** [comment]
Same problem.
```
[INFO]:    -> running virtualenv --python=python2.7 venv
('name is', None, <class 'pythonforandroid.recipes.six.SixRecipe'>)            
('name is', 'jnius', <class 'pythonforandroid.recipes.pyjnius.PyjniusRecipe'>)
('name is', None, <class 'pythonforandroid.recipes.kivy.KivyRecipe'>)
('path is', '/home/sergen/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/:/home/sergen/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/:/home/sergen/android-ndk-r9d:/home/sergen/android-studio/sdk/tools:/home/sergen/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/sergen/.pythonbrew/bin:/home/sergen/.pythonbrew/bin::/home/sergen/SDK_Android/tools:/home/sergen/SDK_Android/platform-tools:/usr/bin:/bin:/usr/local/bin:/home/sergen/android-ndk-r11c:/home/sergen/android-ndk-r9c:/home/sergen/android-ndk-r9d:/usr/games')
objs_paths are ['/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/collated_objects']
Copying libraries
[INFO]:    Creating a requirements.txt file for the Python modules
[INFO]:    Installing Python modules with pip
[INFO]:    If this fails with a message about /bin/false, this probably means the package cannot be installed with pip as it needs a compilation recipe.
[INFO]:    -> running bash -c source venv/bin/activa...(and 384 more)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sergen/Android/python-for-android-master_10-05-16/pythonforandroid/toolchain.py", line 755, in <module>
    main()
  File "/home/sergen/Android/python-for-android-master_10-05-16/pythonforandroid/toolchain.py", line 752, in main
    ToolchainCL()
  File "/home/sergen/Android/python-for-android-master_10-05-16/pythonforandroid/toolchain.py", line 341, in __init__
    getattr(self, args.command)(unknown)
  File "/home/sergen/Android/python-for-android-master_10-05-16/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/home/sergen/Android/python-for-android-master_10-05-16/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 579, in build_recipes
  File "pythonforandroid/build.py", line 620, in run_pymodules_install
  File "pythonforandroid/logger.py", line 173, in shprint
  File "/home/sergen/.local/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/home/sergen/.local/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/sergen/.local/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: "/bin/bash -c source venv/bin/activate && env CC=/bin/false CXX=/bin/false PYTHONPATH=/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/python-installs/trade_prog_SQL/lib/python2.7/site-packages pip install --target '/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/python-installs/trade_prog_SQL/lib/python2.7/site-packages' --no-deps -r requirements.txt"

  STDOUT:
Collecting plyer (from -r requirements.txt (line 1))
  Using cached plyer-1.2.4.tar.gz
Collecting sqlite3 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement sqlite3 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for sqlite3 (from -r requirements.txt (line 2))


  STDERR:

# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build create --dist_name=trade_prog_SQL --bootstrap=sdl2 --requirements=kivy,plyer,sqlite3,hostpython2 --arch armeabi-v7a --copy-libs
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by jboss38** [comment]
got same problem mate

**Comment by inclement** [comment]
There is now an sqlite3 recipe, so make sure your python-for-android is up to date. If it is, please open an issue with a full log on the python-for-android github page.
