### ISSUE TITLE
AttributeError: 'Context' object has no attribute 'hostpython' in recipe

### ISSUE THREAD

**Issue by D3f0** [kivy/buildozer#361]
After running:
`buildozer android_new debug deploy run`

I get

``` bash
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/local/Cellar/git/2.8.1/bin/git
# Search for Cython (cython)
#  -> found at /Users/nahuel/.virtualenvs/kivy/bin/cython
# Search for Java compiler (javac)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac
# Search for Java keytool (keytool)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/keytool
# Install platform
# Apache ANT found at /Users/nahuel/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /Users/nahuel/.buildozer/android/platform/android-sdk-20
# Android NDK found at /Users/nahuel/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run 'python -m pythonforandroid.toolchain --color=always --storage-dir=/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build create --dist_name=Znake --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs'
# Cwd /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /Users/nahuel/.virtualenvs/kivy/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
[INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_components'])
[INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe sdl2_image (depends on [])
[INFO]:    Loaded recipe sdl2_mixer (depends on [])
[INFO]:    Loaded recipe sdl2_ttf (depends on [])
[INFO]:    Loaded recipe pyjnius (depends on ['six', ('python2', 'python3crystax'), ('sdl2', 'sdl', 'webviewjni')])
[INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
[INFO]:    Found multiple valid recipe sets:
[INFO]:        ['six', 'sdl2', u'kivy', 'sdl2_ttf', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
[INFO]:        ['sdl2', 'six', 'sdl2_ttf', 'python3crystax', 'sdl2_mixer', 'sdl2_image', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['six', 'sdl2', u'kivy', 'sdl2_ttf', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name Znake and recipes (kivy)
[INFO]:    -> running cp -r /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/b...(and 143 more)
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is ['python2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/python2
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    python2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    sdl2_image download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    sdl2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/six
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    pyjnius download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    kivy download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    -> directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building python2 for armeabi-v7a
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 755, in <module>
    main()
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 752, in main
    ToolchainCL()
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 341, in __init__
    getattr(self, args.command)(unknown)
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 559, in build_recipes
    recipe.build_arch(arch)
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 44, in build_arch
    self.do_python_build(arch)
  File "/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 76, in do_python_build
    shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
AttributeError: 'Context' object has no attribute 'hostpython'

           working: Python-2.7.2.tar.bz2                                                                                                                                            


           working: SDL2_image-2.0.1.tar.gz                                                                                                                                         


           working: SDL2_mixer-2.0.1.tar.gz                                                                                                                                         


           working: SDL2_ttf-2.0.14.tar.gz                                                                                                                                          


           working: SDL2-2.0.4.tar.gz                                                                                                                                               


           working: six-1.9.0.tar.gz                                                                                                                                                


           working: master.zip                                                                                                                                                      


           working: master.zip                                                                                                                                                      


           working: Python-2.7.2.tar.bz2                                                                                                                                            


           working: SDL2_image-2.0.1.tar.gz                                                                                                                                         


           working: SDL2_mixer-2.0.1.tar.gz                                                                                                                                         


           working: SDL2_ttf-2.0.14.tar.gz                                                                                                                                          


           working: SDL2-2.0.4.tar.gz                                                                                                                                               


           working: six-1.9.0.tar.gz                                                                                                                                                


           working: master.zip                                                                                                                                                      


           working: master.zip                                                                                                                                                      

# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/Users/nahuel/workspace/python/kivy/osx_resize_issue/.buildozer/android/platform/build create --dist_name=Znake --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```
### Additional Info

Darwin greybird.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
### Virtualenv

``` ini
appdirs==1.4.0
appnope==0.1.0
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
buildozer==0.32
cairocffi==0.7.2
CairoSVG==1.0.20
certifi==2016.2.28
cffi==1.6.0
colorama==0.3.7
Cython==0.23
decorator==4.0.9
docutils==0.12
fancycompleter==0.4
functools32==3.2.3.post2
gnureadline==6.3.3
ipykernel==4.3.1
ipython==4.1.1
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.1.1
jupyter-core==4.0.6
Kivy==1.9.2.dev0
Kivy-Garden==0.1.4
MarkupSafe==0.23
mercurial==3.7.3
mistune==0.7.2
nbconvert==4.1.0
nbformat==4.0.1
notebook==4.1.0
ordereddict==1.1
paho-mqtt==1.1
path.py==8.1.2
pdbpp==0.8.3
pexpect==4.0.1
pickleshare==0.6
Pillow==3.2.0
ptyprocess==0.5.1
pycparser==2.14
pygame==1.9.2.dev1
Pygments==2.1.2
pyrepl==0.8.4
pyzmq==15.2.0
qtconsole==4.2.0
requests==2.10.0
sh==1.11
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
terminado==0.6
tornado==4.3
traitlets==4.1.0
Twisted==16.1.1
virtualenv==15.0.1
wmctrl==0.3
zope.interface==4.1.3
```
##

**Comment by pythonic64** [comment]
Add "python2" in requirements of your buildozer.spec file.

**Comment by BallisticPain** [comment]
That helped a ton thanks @pythonic64 !!!!

**Comment by inclement** [comment]
Should be fixed by https://github.com/kivy/python-for-android/pull/1064 .
