### ISSUE TITLE
Buildozer deployment dlopen failed libSDL2.so" has unexpected e_machine: 40.

### ISSUE THREAD

**Issue by tanayz** [kivy/buildozer#365]
I've tried to deploy my python app in a Genymotion Nexus 9 Android 6 API 23 using buildozer.
Below are the entries from my buildozer.spec and I've used the command 
`buildozer android_new debug deploy run logcat`

```
requirements = kivy,openssl,numpy,pil,hostpython2
android.permissions = INTERNET
# (int) Minimum API required
android.minapi = 19
```

However it throws an error in deployment,although the debug is successful 
System.err: dlopen failed: "/data/app/org.test.fstest-1/lib/arm/libSDL2.so" has unexpected e_machine: 40.
Any idea on that.

Below is the detailed logcat error
06-07 10:30:28.880  3313  3313 V PythonActivity: About to do super onCreate
06-07 10:30:28.881  3313  3313 V SDL     : Device: vbox86tp
06-07 10:30:28.881  3313  3313 V SDL     : Model: Google Nexus 9 - 6.0.0 - API 23 - 1536x2048
06-07 10:30:28.881  3313  3313 V SDL     : onCreate():null
06-07 10:30:28.883  3313  3313 W System.err: dlopen failed: "/data/app/org.test.fstest-1/lib/arm/libSDL2.so" has unexpected e_machine: 40
06-07 10:30:28.899  3313  3326 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-07 10:30:28.906  3313  3313 D         : HostConnection::get() New Host Connection established 0xe7f92600, tid 3313
06-07 10:30:28.911  3313  3313 V PythonActivity: Did super onCreate
06-07 10:30:28.911  3313  3313 V PythonActivity: Setting env vars for start.c and Python to use
06-07 10:30:28.911  3313  3313 E art     : No implementation found for void org.libsdl.app.SDLActivity.nativeSetEnv(java.lang.String, java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativeSetEnv and Java_org_libsdl_app_SDLActivity_nativeSetEnv__Ljava_lang_String_2Ljava_lang_String_2)
06-07 10:30:28.912  3313  3313 D AndroidRuntime: Shutting down VM
06-07 10:30:28.912  3313  3313 E AndroidRuntime: FATAL EXCEPTION: main
06-07 10:30:28.912  3313  3313 E AndroidRuntime: Process: org.test.fstest, PID: 3313
06-07 10:30:28.912  3313  3313 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void org.libsdl.app.SDLActivity.nativeSetEnv(java.lang.String, java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativeSetEnv and Java_org_libsdl_app_SDLActivity_nativeSetEnv__Ljava_lang_String_2Ljava_lang_String_2)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at org.libsdl.app.SDLActivity.nativeSetEnv(Native Method)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at org.kivy.android.PythonActivity.onCreate(PythonActivity.java:69)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-07 10:30:28.912  3313  3313 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-07 10:30:28.912  1679  1692 W ActivityManager:   Force finishing activity org.test.fstest/org.kivy.android.PythonActivity
06-07 10:30:29.215  1679  1692 I WindowManager: Screenshot max retries 4 of Token{54b9c9b ActivityRecord{211b8aa u0 org.test.fstest/org.kivy.android.PythonActivity t5 f}} appWin=Window{1171c4d u0 Starting org.test.fstest} drawState=4
06-07 10:30:29.216  1679  1679 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 299ms
06-07 10:30:29.222  1679  1696 W ViewRootImpl: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_UNKNOWN, scanCode=125, metaState=0, flags=0x8, repeatCount=17427, eventTime=3714602, downTime=2823559, deviceId=1, source=0x301 }
06-07 10:30:29.222  1679  1696 W ViewRootImpl: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_UNKNOWN, scanCode=125, metaState=0, flags=0x8, repeatCount=17428, eventTime=3714913, downTime=2823559, deviceId=1, source=0x301 }
06-07 10:30:29.244  1679  2908 I OpenGLRenderer: Initialized EGL, version 1.4
06-07 10:30:29.278  1679  2908 W EGL_emulation: eglSurfaceAttrib not implemented
06-07 10:30:29.278  1679  2908 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdb5d6dc0, error=EGL_SUCCESS
06-07 10:30:29.293  1679  1696 W ViewRootImpl: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_UNKNOWN, scanCode=125, metaState=0, flags=0x8, repeatCount=17429, eventTime=3714963, downTime=2823559, deviceId=1, source=0x301 }
06-07 10:30:29.716  1679  1695 W ActivityManager: Activity pause timeout for ActivityRecord{211b8aa u0 org.test.fstest/org.kivy.android.PythonActivity t5 f}
06-07 10:30:29.748  2307  2447 W EGL_emulation: eglSurfaceAttrib not implemented
06-07 10:30:29.748  2307  2447 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf0de8e0, error=EGL_SUCCESS
06-07 10:30:30.354  2307  2447 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
06-07 10:30:34.694  3313  3313 I Process : Sending signal. PID: 3313 SIG: 9
06-07 10:30:34.713  1679  2343 I WindowState: WIN DEATH: Window{150ff68 u0 org.test.fstest/org.kivy.android.PythonActivity}
06-07 10:30:34.713  1679  3074 D GraphicsStats: Buffer count: 4
06-07 10:30:34.718  1679  2908 E Surface : getSlotFromBufferLocked: unknown buffer: 0xde783ab0
06-07 10:30:34.718  1679  3074 I ActivityManager: Process org.test.fstest (pid 3313) has died
06-07 10:30:34.723  1679  2908 D OpenGLRenderer: endAllStagingAnimators on 0xda3fd580 (RippleDrawable) with handle 0xda738490
06-07 10:30:34.726  1679  1692 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@6e1da62 attribute=null, token = android.os.BinderProxy@1a72a3c
06-07 10:30:34.929  1679  1701 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
06-07 10:31:40.949    85    85 D Genyd   : Received Set Clipboard
06-07 10:31:40.949    85    85 D Genymotion: Received Set Clipboard

**Comment by selobu** [comment]
I have the same error, I compiled the apk by using

>>> buildozer android_new debug deploy

the when y ran the app shows me the error

"/data/app-lib/org.seisoft.com.tarjetasst-2/libSDL2.so" has unexpected e_machine: 40

I'm using crystax 10.3.2.

/========= buildozer.spec======/

[app]

# (str) Title of your application
title = Tarjetas SST

# (str) Package name
package.name = tarjetasst

# (str) Package domain (needed for android/ios packaging)
package.domain = org.seisoft.com

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
# source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
source.exclude_exts = spec, zip

# (list) List of directory to exclude (let empty to not exclude anything)
# source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = python3crystax==3.6, sqlite3, kivy==master, git+https://gitlab.com/kivymd/KivyMD.git, openssl

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
# garden_requirements = circularlayout, circulardatepicker

# (str) Presplash of the application
presplash.filename = %(source.dir)s/data/fondo_pantalla.png

# (str) Icon of the application
icon.filename = %(source.dir)s/data/bota.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) Permissions
android.permissions = INTERNET

# (int) Android API to use
android.api = 19

# (int) Minimum API required
#android.minapi = 19

# (int) Android SDK version to use
android.sdk = 20

# (str) Android NDK version to use
android.ndk = 10.3.2

# (bool) Use --private data storage (True) or --dir public storage (False)
# android.private_storage = False 

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = /media/sf_TarjetaSST/.buildozer/crystax

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir =

# (list) python-for-android whitelist
#android.p4a_whitelist =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

**Comment by dav01it** [comment]
Did you ran the app on a x86 android emulator? If yes the problem is you need to run on arm emulator or device. Python for android does not support x86 at the moment.

**Comment by inclement** [comment]
@dav01it python-for-android actually does support x86, just set `--arch=x86`.
