### ISSUE TITLE
Build for Android is Inconsistent with the Linux Version 

### ISSUE THREAD

**Issue by FluxIX** [kivy/buildozer#378]
When I run my application on Linux using `python2 -m {module name}` the application runs as expected, but when I compile for Android and attempt to run the application immediately fails with the following error:
```
I/python  (14091):  Traceback (most recent call last):
I/python  (14091):    File "{project path}/src/app/.buildozer/android/app/main.py", line 2, in <module>
I/python  (14091):    File "{project path}/src/app/.buildozer/android/app/_app.py", line 9, in <module>
I/python  (14091):  ImportError: No module named app.ui.first_screen
I/python  (14091): Python for android ended.
```

It appears the location of files to import are being moved during the compilation process.

**Comment by FluxIX** [comment]
It occurs to me this may be a Python for Android bug instead. If so I will file a bug report in the Python for Android project.

**Comment by FluxIX** [comment]
This wasn't an error with buildozer. It is instead an error with Python for Android (https://github.com/kivy/python-for-android/issues/840).
