### ISSUE TITLE
When will you add requests lib to recipes?

### ISSUE THREAD

**Issue by drakipovic** [kivy/buildozer#382]
I need to include requests lib to my kivy application and it's producing this error:

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian `dpkg' package management program version 1.17.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/dinek/anaconda2/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-oracle/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
# Install platform
# Apache ANT found at /home/dinek/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/dinek/.buildozer/android/platform/android-sdk-24
# Android NDK found at /home/dinek/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Run './distribute.sh -l'
# Cwd /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/python-for-android
Available modules: android apsw audiostream bidi boost cherrypy c_igraph click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope
# Remove directory and subdirectory /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/applibs
# Create directory /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/applibs
# Run 'bash -c "source venv/bin/activate && env"'
# Cwd /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer
bash: venv/bin/activate: No such file or directory
# Command failed: bash -c "source venv/bin/activate && env"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

I looked into recipes and there is not requests lib there.

**Comment by pythonic64** [comment]
Do you have virtualenv installed? 
Package "requests" is pure Python package and it doesn't need recipe.

**Comment by drakipovic** [comment]
I have virtualenv yes, I just can't find solution for this error.

**Comment by pythonic64** [comment]
Try using target "android_new" instead "android":
```buildozer android_new debug```
I think that auto-installing pure Python packages in only supported in "android_new" target.

**Comment by drakipovic** [comment]
With android_new I'm getting import error for urllib3, and that one I have. Can the issue be that I use anaconda for all my libs?

**Comment by inclement** [comment]
requests does not need a recipe.

I'm not sure what causes your first error with the old toolchain. Can you post the full error log with android_new?

**Comment by drakipovic** [comment]
Copying libraries
                                                                                               Traceback (most recent call last):              
  File "/home/dinek/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/dinek/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 792, in <module>
    main()
  File "/home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 789, in main
    ToolchainCL()
  File "/home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 464, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 145, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 188, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 581, in build_recipes
  File "pythonforandroid/build.py", line 600, in run_pymodules_install
  File "pythonforandroid/logger.py", line 173, in shprint
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/home/dinek/anaconda2/bin/virtualenv --python=python2.7 venv'

  STDOUT:
Running virtualenv with interpreter /home/dinek/anaconda2/bin/python2.7
New python executable in /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/build/build/venv/bin/python2.7
Not overwriting existing python script /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/build/build/venv/bin/python (you must use /home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/build/build/venv/bin/python2.7)
Installing setuptools, pip, wheel...
  Complete output from command /home/dinek/Document...d/venv/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/download.py", line 39, in <module>
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 61, in <module>
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 2332, in <module>
    main()
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/dinek/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/dinek/Document...d/venv/bin/python2.7 - setuptools pip wheel failed with error code 1


  STDERR:

# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/dinek/Documents/projekti/expense_report/photo_taker/.buildozer/android/platform/build create --dist_name=expensereport --bootstrap=sdl2 --requirements=kivy,plyer,requests --arch armeabi-v7a --copy-libs


Here it is.

**Comment by tito** [comment]
It's an issue with your local python, not buildozer itself. Look closely to the issue: we create a virtualenv and try to install requests in it. But pip in the virtualenv fail due to an import with urllib3.

I guess you can reproduce it locally by doing the same. Check with other anaconda people to see about it. Standard python works (osx/linux)
