### ISSUE TITLE
Buildozer android_new fails

### ISSUE THREAD

**Issue by Antozamm** [kivy/buildozer#388]
I run buildozer android_new debug
with requirements=kivy, python2
and get this error:

> [INFO]:    # Prebuilding recipes
> [INFO]:    Prebuilding hostpython2 for armeabi-v7a
> [INFO]:    -> running cp /home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/recipes/hostpython2/Setup /home/sleep/Android/c...(and 160 more)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/toolchain.py", line 792, in <module>
>     main()
>   File "/home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/toolchain.py", line 789, in main
>     ToolchainCL()
>   File "/home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/toolchain.py", line 464, in __init__
>     getattr(self, args.subparser_name.replace('-', '_'))(args)
>   File "/home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/toolchain.py", line 145, in wrapper_func
>     build_dist_from_args(ctx, dist, args)
>   File "/home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/toolchain.py", line 188, in build_dist_from_args
>     build_recipes(build_order, python_modules, ctx)
>   File "pythonforandroid/build.py", line 553, in build_recipes
>     recipe.prebuild_arch(arch)
>   File "/home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/recipes/hostpython2/__init__.py", line 26, in prebuild_arch
>     join(self.get_build_dir(), 'Modules', 'Setup'))
>   File "pythonforandroid/logger.py", line 173, in shprint
>     for line in output:
>   File "/home/sleep/.virtualenvs/test/local/lib/python2.7/site-packages/sh.py", line 565, in next
>     self.wait()
>   File "/home/sleep/.virtualenvs/test/local/lib/python2.7/site-packages/sh.py", line 500, in wait
>     self.handle_command_exit_code(exit_code)
>   File "/home/sleep/.virtualenvs/test/local/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
>     raise exc(self.ran, self.process.stdout, self.process.stderr)
> sh.ErrorReturnCode_1: 
> 
>   RAN: '/bin/cp /home/sleep/.buildozer/android/packages/python-for-android-master/pythonforandroid/recipes/hostpython2/Setup /home/sleep/Android/creating_kivy_code/apps_in_kivy_example_code/1-07_widget_sizes/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2/Modules/Setup'
> 
>   STDOUT:
> /bin/cp: cannot create regular file '/home/sleep/Android/creating_kivy_code/apps_in_kivy_example_code/1-07_widget_sizes/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2/Modules/Setup': No such file or directory
> 
> 
>   STDERR:

I don't know what to do next, please advice.

**Comment by twasanon** [comment]
I am having the same issue as well :/. looking for a solution to this too.

**Comment by Tungsteno74** [comment]
Try this:
`requirements =hostpython2, kivy`

You don't need python2 requirement. Is already included in the package.

For the next steps with _andoid_new_ target check this (if it will give you some errors):

https://github.com/kivy/buildozer/issues/313

**Comment by saqib1707** [comment]
Even after adding hostpython2 in the requirements , I am getting the same error as with python2 in  the requirements.I am attaching my buildozer.spec file for review.Here is the link for the traceback--
http://pastebin.com/H6j42K8r
