### ISSUE TITLE
python.host could not find platform independent libraries

### ISSUE THREAD

**Issue by gera2ld** [kivy/buildozer#390]
When trying to build with command:
```
buildozer android_new debug deploy run
```
I got error like this:
```
...
[INFO]:    -> running python.host setup.py install -O2
('name is', None, <class 'pythonforandroid.recipes.six.SixRecipe'>)
('path is', '/Users/gerald/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86/bin/:/Users/gerald/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/:/Users/gerald/.buildozer/android/platform/android-ndk-r9c:/Users/gerald/.buildozer/android/platform/android-sdk-20/tools:/Users/gerald/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/gerald/.pyenv/versions/2.7.12/bin:/usr/local/Cellar/pyenv/20160726/libexec:/Users/gerald/.pyenv/shims:/Users/gerald/.nvm/versions/node/v6.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin')
Traceback (most recent call last):
  File "/Users/gerald/.pyenv/versions/2.7.12/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/gerald/.pyenv/versions/2.7.12/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/gerald/Source/ponggame/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 792, in <module>
    main()
  File "/Users/gerald/Source/ponggame/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 789, in main
    ToolchainCL()
  File "/Users/gerald/Source/ponggame/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 464, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/gerald/Source/ponggame/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 145, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/gerald/Source/ponggame/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 188, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 561, in build_recipes
  File "pythonforandroid/recipe.py", line 788, in build_arch
  File "pythonforandroid/recipe.py", line 829, in install_python_package
  File "pythonforandroid/logger.py", line 173, in shprint
  File "/Users/gerald/.pyenv/versions/2.7.12/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/Users/gerald/.pyenv/versions/2.7.12/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/gerald/.pyenv/versions/2.7.12/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1:

  RAN: '/Users/gerald/Source/ponggame/.buildozer/android/platform/build/build/python-installs/ponggame/bin/python.host setup.py install -O2'

  STDOUT:
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site


  STDERR:

# Command failed: python -m pythonforandroid.toolchain create --dist_name=ponggame --bootstrap=sdl2 --requirements=kivy,python2 --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/gerald/Source/ponggame/.buildozer/android/platform/build
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

I tried running `/Users/gerald/Source/ponggame/.buildozer/android/platform/build/build/python-installs/ponggame/bin/python.host` directly, it has errors above too. Is that `python.host` broken?

**Comment by dzmitrykrukouski** [comment]
Try to add `python2` in application requirements.

**Comment by pythongiant** [comment]
has anyone solved this?

**Comment by inclement** [comment]
@pythongiant If you have this issue with p4a master, could you paste the full build log?

**Comment by pythongiant** [comment]
`srihari@srihari-LIFEBOOK-A555 ~/My Programs/AI $ buildozer android debug run
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.18.4 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10" "jinja2" "six"'
# Cwd None
# Apache ANT found at /home/srihari/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/srihari/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/srihari/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=ANRIT --bootstrap=sdl2 --requirements=kivy,textblob,plyer,pandas,datefinder,webbrowser,hostpython2,python2 --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/srihari/My Programs/AI/.buildozer/android/platform/build'
# Cwd /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
[INFO]:    No recipe named textblob; will attempt to install with pip
[INFO]:    Loaded recipe hostpython2 (depends on [], conflicts ['hostpython3'])
[INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_components'])
[INFO]:    No recipe named datefinder; will attempt to install with pip
[INFO]:    No recipe named webbrowser; will attempt to install with pip
[INFO]:    No recipe named pandas; will attempt to install with pip
[INFO]:    Loaded recipe python2 (depends on ['hostpython2'], conflicts ['python3crystax', 'python3'])
[INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('python2', 'python3crystax'), ('sdl2', 'pygame')])
[INFO]:    No recipe named plyer; will attempt to install with pip
[INFO]:    Loaded recipe sdl2_image (depends on [])
[INFO]:    Loaded recipe sdl2_mixer (depends on [])
[INFO]:    Loaded recipe sdl2_ttf (depends on [])
[INFO]:    Loaded recipe pyjnius (depends on [('sdl2', 'sdl', 'genericndkbuild'), ('python2', 'python3crystax'), 'six'])
[INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
[INFO]:    Found a single valid recipe set (this is good)
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name ANRIT and recipes (kivy, textblob, plyer, pandas, datefinder, webbrowser, hostpython2, python2)
[INFO]:    -> running cp -r /home/srihari/My Program...(and 150 more)
[INFO]:    -> directory context /home/srihari/My/build/bootstrap_builds/sdl2-python2
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    The requirements (datefinder, pandas, plyer, textblob, webbrowser) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/srihari/My/packages/hostpython2
[INFO]:    -> directory context /home/srihari/My/packages/hostpython2
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    hostpython2 download already cached, skipping                       
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/srihari/My/packages/sdl2_image
[INFO]:    -> directory context /home/srihari/My/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping                        
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/srihari/My/packages/sdl2_mixer
[INFO]:    -> directory context /home/srihari/My/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping                        
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/srihari/My/packages/sdl2_ttf
[INFO]:    -> directory context /home/srihari/My/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping                          
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/srihari/My/packages/python2
[INFO]:    -> directory context /home/srihari/My/packages/python2
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    python2 download already cached, skipping                           
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/srihari/My/packages/sdl2
[INFO]:    -> directory context /home/srihari/My/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/srihari/My/packages/six
[INFO]:    -> directory context /home/srihari/My/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping                               
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/srihari/My/packages/pyjnius
[INFO]:    -> directory context /home/srihari/My/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    pyjnius download already cached, skipping                           
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/srihari/My/packages/kivy
[INFO]:    -> directory context /home/srihari/My/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping                              
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    -> directory context /home/srihari/My/build/other_builds/hostpython2/desktop
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/srihari/My/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/srihari/My/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/srihari/My/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    -> directory context /home/srihari/My/build/other_builds/python2/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/srihari/My/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/srihari/My/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> directory context /home/srihari/My/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/srihari/My/build/other_builds/kivy-python2-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /home/srihari/My Programs/A...(and 180 more)
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython2 for armeabi-v7a
[INFO]:    -> directory context /home/srihari/My/build/other_builds/hostpython2/desktop/hostpython2
[INFO]:    hostpython already exists, skipping build
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python2 for armeabi-v7a
[INFO]:    Copying hostpython binary to targetpython folder
[INFO]:    -> running cp /home/srihari/My/build/othe...(and 112 more)
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/srihari/My/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /home/srihari/My/build/other_builds/six-python2/armeabi-v7a/six
[INFO]:    -> running python.host setup.py install -O2
Exception in thread background thread for pid 2603:                            
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/srihari/My/build/python-installs/ANRIT/bin/python.host setup.py install -O2

  STDOUT:
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>
    main()
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/build.py", line 565, in build_recipes
    recipe.build_arch(arch)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 806, in build_arch
    self.install_python_package(arch)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 846, in install_python_package
    *self.setup_extra_args)
  File "/home/srihari/My Programs/AI/.buildozer/android/platform/python-for-android-master/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/srihari/.local/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/srihari/My/build/python-installs/ANRIT/bin/python.host setup.py install -O2

  STDOUT:
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site


  STDERR:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=ANRIT --bootstrap=sdl2 --requirements=kivy,textblob,plyer,pandas,datefinder,webbrowser,hostpython2,python2 --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/srihari/My Programs/AI/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
`

**Comment by pythongiant** [comment]
@inclement to do you need the spec file too

**Comment by Zen-CODE** [comment]
I hit this error when building to a shared folder in VBox. In this scenario, some of the symlinks cannot be created. 
@gera2ld. What is your build destination and file system?

**Comment by wingchen** [comment]
any update on this one? I still see it.

**Comment by poorya-kh** [comment]
It's also my problem. I don't know what's behind this error ...
