### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by deounix** [kivy/buildozer#391]
I'm getting this error when I'm trying to build apk

```
assets/private.mp3: /home/kivy/.buildozer/android/app/sitecustomize.pyo
assets/private.mp3: /home/kivy/.buildozer/android/app/main.pyo
Traceback (most recent call last):
  File "build.py", line 517, in <module>
    make_package(args)
  File "build.py", line 365, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/local/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
# Command failed: python build.py --name HelloWorld --version 0.1 --package org.test.helloworld2 --sdk 19 --minsdk 9 --private /home/kivy/.buildozer/android/app --orientation sensor --window debug
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by dzmitrykrukouski** [comment]
Here #372  you can find a solution to this problem.
