### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by nesergen** [kivy/buildozer#395]
trying to build apk with buildozer and get the ERROR

```
@sergen-pc:~/PythonExp/kivy_exp/TRADE_sql$ buildozer android_new debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.18.4 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Apache ANT found at /home/sergen/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/sergen/android-studio/sdk
# Android NDK found at /home/sergen/android-ndk-r9d
# Check application requirements
# Check garden requirements
# Garden requirements already installed, pass
# Compile platform
# Run 'python -m pythonforandroid.toolchain --color=always --storage-dir=/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build create --dist_name=trade_prog_SQL --bootstrap=sdl2 --requirements=kivy,plyer,sqlite3,hostpython2 --arch armeabi-v7a --copy-libs'
# Cwd /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (17, 19, 21, 23)
[INFO]:    Requested API target 17 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
[INFO]:    No recipe named plyer; will attempt to install with pip
[INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe sqlite3 (depends on [])
[INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_components'])
[INFO]:    Loaded recipe hostpython2 (depends on [], conflicts ['hostpython3'])
[INFO]:    Loaded recipe pyjnius (depends on ['six', ('sdl2', 'sdl', 'genericndkbuild'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe sdl2_image (depends on [])
[INFO]:    Loaded recipe sdl2_mixer (depends on [])
[INFO]:    Loaded recipe sdl2_ttf (depends on [])
[INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
[INFO]:    Found multiple valid recipe sets:
[INFO]:        ['six', 'sdl2', u'kivy', 'sdl2_ttf', u'hostpython2', 'sdl2_mixer', 'sdl2_image', u'sqlite3', 'pyjnius', 'python2']
[INFO]:        ['sdl2', 'six', 'sdl2_ttf', u'hostpython2', 'python3crystax', 'sdl2_mixer', 'sdl2_image', u'sqlite3', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['six', 'sdl2', u'kivy', 'sdl2_ttf', u'hostpython2', 'sdl2_mixer', 'sdl2_image', u'sqlite3', 'pyjnius', 'python2']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name trade_prog_SQL and recipes (kivy, plyer, sqlite3, hostpython2)
[INFO]:    -> running cp -r /home/sergen/PythonExp/k...(and 222 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is [u'hostpython2', 'python2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', u'sqlite3', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The requirements (plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 75 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    -> running rm -f .mark-Python-2.7.2.tar.bz2
[INFO]:    Downloading hostpython2 from http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
Downloading hostpython2 from http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
- Do[INFO]:    -> running touch .mark-Python-2.7.2.tar.bz2
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 71 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    python2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 74 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 74 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 72 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 71 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/sqlite3
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    sqlite3 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 68 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
           working: SDL2-2.0.4.tar.gz                                [INFO]:    sdl2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 67 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 71 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    pyjnius download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/sergen/PythonEx...(and 68 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop
[INFO]:    -> running tar tf /home/sergen/PythonExp/...(and 94 more)
           working: Python-2.7.2/Mac/Demo/example1/dnslookup-1.py   [INFO]:    -> running mv Python-2.7.2 /home/sergen/P...(and 112 more)
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
           working: SDL2_ttf-2.0.14.tar.gz                                     [INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/sqlite3/armeabi-v7a
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /home/sergen/PythonExp/kivy...(and 252 more)
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sqlite3 for armeabi-v7a
[INFO]:    sqlite3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython2 for armeabi-v7a
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2
[INFO]:    -> running configure
           working: co[INFO]:    -> running make -j5tus                        
   [INFO]:    -> running mv Parser/pgen hostpgenexp/T...(and 211 more) 
[INFO]:    -> running mv python hostpython
[INFO]:    <- directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master
[INFO]:    Building python2 for armeabi-v7a
[INFO]:    -> running cp /home/sergen/PythonExp/kivy...(and 241 more)
[INFO]:    -> running cp /home/sergen/PythonExp/kivy...(and 239 more)
[INFO]:    -> directory context /home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a/python2
[INFO]:    -> running cp /home/sergen/PythonExp/kivy...(and 119 more)
[INFO]:    -> running gcc -dumpmachine
('path is', '/home/sergen/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/:/home/sergen/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/:/home/sergen/android-ndk-r9d:/home/sergen/android-studio/sdk/tools:/home/sergen/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/sergen/.pythonbrew/bin:/home/sergen/.pythonbrew/bin::/home/sergen/SDK_Android/tools:/home/sergen/SDK_Android/platform-tools:/usr/bin:/bin:/usr/local/bin:/home/sergen/android-ndk-r11c:/home/sergen/android-ndk-r9c:/home/sergen/android-ndk-r9d:/usr/games:/sbin/:/usr/sbin')
[INFO]:    -> running configure --host=arm-eabi --bu...(and 234 more)
          Traceback (most recent call last):iler cannot create executables     
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 792, in <module>
    main()
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 789, in main
    ToolchainCL()
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 464, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 145, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 188, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 561, in build_recipes
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 44, in build_arch
    self.do_python_build(arch)
  File "/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 124, in do_python_build
    _env=env)
  File "pythonforandroid/logger.py", line 173, in shprint
  File "/home/sergen/.local/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/home/sergen/.local/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/sergen/.local/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_77: 

  RAN: './configure --host=arm-eabi --build=x86_64-linux-gnu --prefix=/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a/python2/python-install --enable-shared --disable-toolbox-glue --disable-framework'

  STDOUT:
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... linux4
checking EXTRAPLATDIR... 
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for arm-eabi-gcc... arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/sergen/android-ndk-r9d/platforms/android-17/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a/python2':
configure: error: C compiler cannot create executables
See `config.log' for more details


  STDERR:

# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/sergen/PythonExp/kivy_exp/TRADE_sql/.buildozer/android/platform/build create --dist_name=trade_prog_SQL --bootstrap=sdl2 --requirements=kivy,plyer,sqlite3,hostpython2 --arch armeabi-v7a --copy-libs
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

```
[app]

# (str) Title of your application
title = Trade_SQL_v2

# (str) Package name
package.name = trade_prog_SQL

# (str) Package domain (needed for android/ios packaging)
package.domain = org.trade

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas, pyo

# (list) Source files to exclude (let empty to not exclude anything)
source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests, bin, fotos

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
#version.regex = __version__ = ['"](.*)'['"]
#version.filename = %(source.dir)s/main.py

# (str) Application versioning (method 2)
version = 1.0

# (list) Application requirements
requirements = kivy, plyer, sqlite3

# (list) Garden requirements
garden_requirements = xcamera

# (str) Presplash of the application
presplash.filename = /home/sergen/monkey.png

# (str) Icon of the application
icon.filename = /home/sergen/Картинки/Lime.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1


#
# Android specific
#

# (list) Permissions
android.permissions = WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE, ACCESS_CHECKIN_PROPERTIES, CAMERA,  EXPAND_STATUS_BAR

# (int) Android API to use
android.api = 17

# (int) Minimum API required (8 = Android 2.2 devices)
#android.minapi = 14

# (int) Android SDK version to use
#android.sdk = 22

# (str) Android NDK version to use
#android.ndk = 9

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = False

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = /home/sergen/android-ndk-r9d

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
android.sdk_path = /home/sergen/android-studio/sdk

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir = /home/sergen/Android/python-for-android-old_toolchain/

# (list) python-for-android whitelist
#android.p4a_whitelist =

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

#
# iOS specific
#

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2


# -----------------------------------------------------------------------------
# List as sections
#
# You can define all the "list" as [section:key].
# Each line will be considered as a option to the list.
# Let's take [app] / source.exclude_patterns.
# Instead of doing:
#
#     [app]
#     source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
# This can be translated into:
#
#     [app:source.exclude_patterns]
#     license
#     data/audio/*.wav
#     data/images/original/*
#


# -----------------------------------------------------------------------------
# Profiles
#
# You can extend section / key with a profile
# For example, you want to deploy a demo version of your application without
# HD content. You could first change the title to add "(demo)" in the name
# and extend the excluded directories to remove the HD content.
#
#     [app@demo]
#     title = My Application (demo)
#
#     [app:source.exclude_patterns@demo]
#     images/hd/*
#
# Then, invoke the command line with the "demo" profile:
#
#     buildozer --profile demo android debug
```

**Comment by Zen-CODE** [comment]
Hitting this too.

**Comment by Zen-CODE** [comment]
@nesergen. Fixed this by adding 'python2' to the requirements list. Does that fix it for you?

**Comment by nesergen** [comment]
Yes, after add python2 requirement compilation ends successfully.

**Comment by joshw378** [comment]
OSX 10.15.3 ,   buildozer.spec requirement just python2 , can not use both python2 python3
  RAN: /usr/bin/python2 -m Cython.Build.Cythonize ./jnius/jnius.pyx

  STDOUT:
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named Cython.Build

**Comment by Zen-CODE** [comment]
@joshw378 Yes. The toolchain now supports only python3.

**Comment by meetvaghasiya** [comment]
Hello @Zen-CODE  @joshw378  ,i got this error please help me solve this error

configure: error: in `/home/meet/App/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi':
configure: error: C compiler cannot create executables
See `config.log' for more details


  STDERR:

 Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/meet/App/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21

**Comment by Zen-CODE** [comment]
@meetvaghasiya. This ticket is closed, and the solution here is not relevant to your issue as you are using Python 3. If you are still experiencing this issue, please create a new ticket, detailing the OS you are using, the exact steps you followed and include the full error log (or a link to it).

Thanks
