### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by dmpayton** [kivy/buildozer#400]
I'm running into an issue trying to get a simple "hello world" app to build in the VirtualBox image. I've upgraded to the latest buildozer release on PyPI (v0.32), and have installed kivy from `kivy-team/kivy-nightly`.

```
kivy@kivy-VirtualBox:~/dev/chordinator$ buildozer android_new debug
# Check configuration tokens
# Ensure build layout
# Create directory /home/kivy/dev/chordinator/.buildozer
# Create directory /home/kivy/dev/chordinator/.buildozer/applibs
# Create directory /home/kivy/dev/chordinator/.buildozer/android/platform
# Create directory /home/kivy/dev/chordinator/.buildozer/android/app
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian `dpkg' package management program version 1.17.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'git clone -b master --single-branch https://github.com/kivy/python-for-android.git python-for-android-master'
# Cwd /home/kivy/dev/chordinator/.buildozer/android/platform
Cloning into 'python-for-android-master'...
# Apache ANT found at /home/kivy/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/kivy/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/kivy/.buildozer/android/platform/android-ndk-r9c
# Run '/home/kivy/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e'
# Cwd /home/kivy/.buildozer/android/platform
None
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.32', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 100, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 174, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 500, in install_platform
    self._install_android_packages()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 404, in _install_android_packages
    packages = self._android_list_sdk()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 333, in _android_list_sdk
    for x in available_packages.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

FWIW, `rm -rf .buildozer` and `buildozer android debug` results in the same error.

**Comment by timojuez** [comment]
Affects me

**Comment by meami** [comment]
Any solutions or work-arounds to this error yet? 

I guess it's to simple but Is it possible to just convert 'available_packages' to str(available_packages) ?
(in the android.py file wich contains that line of code)

**Comment by timojuez** [comment]
Thanks for your answer. The problem suddenly disappeared for me. Probably due to newer versions of some package on pip.

**Comment by kamachisundaram** [comment]
How to solve this issue. I am not able to get rid of this issue.

**Comment by doughazell** [comment]
Adding 'str(available_packages)' to 
'/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/targets/android.py:336'
on 'Ubuntu 16.04.3 LTS'
running 'Buildozer 0.34dev'
solved the same error for me during '$ buildozer android debug'

**Comment by iancrossfield** [comment]
I had a similar problem but in email/feedparser.py.  Changing the offending line to
`parts = str(data).splitlines(True) `
fixed it for me -- thanks to @doughazell for the suggestion.

**Comment by inclement** [comment]
Closing as stale, I recently rewrote the available_packages logic. Please open a new issue for any further problems.
