### ISSUE TITLE
dlopen failed: _clock.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by tamarintech** [kivy/buildozer#423]
I managed to get an APK built with python 3.5, but I can't seem to run it.  The generated API always produces this error:

Not really sure what to do to resolve this.

```11-23 02:44:16.016 10539 10566 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.myapp/files/app/.kivy/logs/kivy_16-11-23_3.txt
11-23 02:44:16.016 10539 10566 I python  : [INFO   ] [Kivy        ] v1.9.2-dev0
11-23 02:44:16.016 10539 10566 I python  : [INFO   ] [Python      ] v3.5.0 (default, Dec 24 2015, 05:56:40) 
11-23 02:44:16.016 10539 10566 I python  : [GCC 5.3 20151204]
11-23 02:44:16.016 10539 10566 I python  :  Traceback (most recent call last):
11-23 02:44:16.016 10539 10566 I python  :    File "main.py", line 2, in <module>
11-23 02:44:16.016 10539 10566 I python  :      import kivy_demo_module.kivy_ui
11-23 02:44:16.016 10539 10566 I python  :    File "./kivy_demo_module/kivy_ui.py", line 1, in <module>
11-23 02:44:16.016 10539 10566 I python  :      from kivy.app import App
11-23 02:44:16.016 10539 10566 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/kivy/app.py", line 319, in <module>
11-23 02:44:16.026 10539 10566 I python  :      from kivy.base import runTouchApp, stopTouchApp
11-23 02:44:16.026 10539 10566 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/kivy/base.py", line 29, in <module>
11-23 02:44:16.026 10539 10566 I python  :      from kivy.clock import Clock
11-23 02:44:16.026 10539 10566 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/kivy/clock.py", line 364, in <module>
11-23 02:44:16.026 10539 10566 I python  :      from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
11-23 02:44:16.026 10539 10566 I python  :  ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/crystax_python/site-packages/kivy/_clock.so" is 64-bit instead of 32-bit
```

**Comment by tamarintech** [comment]
Closing, no responses.
