### ISSUE TITLE
I fail in build of the application using shapely

### ISSUE THREAD

**Issue by asaitoc** [kivy/buildozer#441]
Can I ask a question here?
When I build kivy application using shapely, I fail in building libgeos for armeabi-v7a.
vector: No such file or directory

ubuntu 16.04, android-sdk=21, android-ndk=r13b
new toolchain

Will the library which I should install be short?

--- log -----------------------------------------------------------------------------

In file included from IndexedPointInAreaLocator.cpp:16:0:
../../../include/geos/algorithm/locate/IndexedPointInAreaLocator.h:22:33: fatal error: vector: No such file or directory
 #include <vector> // composition
                                 ^
In file included from SimplePointInAreaLocator.cpp:16:0:
../../../include/geos/algorithm/CGAlgorithms.h:25:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
compilation terminated.
Makefile:484: recipe for target 'IndexedPointInAreaLocator.lo' failed
make[5]: *** [IndexedPointInAreaLocator.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
Makefile:484: recipe for target 'SimplePointInAreaLocator.lo' failed
make[5]: *** [SimplePointInAreaLocator.lo] Error 1
make[5]: Leaving directory '/home/kivy/Documents/echizen-cyo/.buildozer/android/platform/build/build/other_builds/libgeos/armeabi-v7a/libgeos/src/algorithm/locate'

---------------------------------------------------------------------------------------

**Comment by asaitoc** [comment]
It was able to be settled by the following contents.

    pythonforandroid/recipes/libgeos/__init__.py	(before)

    def get_recipe_env(self, arch):
        env = super(LibgeosRecipe, self).get_recipe_env(arch)
        env['CXXFLAGS'] += ' -I{}/sources/cxx-stl/gnu-libstdc++/4.8/include'.format(self.ctx.ndk_dir)
        env['CXXFLAGS'] += ' -I{}/sources/cxx-stl/gnu-libstdc++/4.8/libs/{}/include'.format(
            self.ctx.ndk_dir, arch)
        env['CXXFLAGS'] += ' -L{}/sources/cxx-stl/gnu-libstdc++/4.8/libs/{}'.format(
            self.ctx.ndk_dir, arch)
        env['CXXFLAGS'] += ' -lgnustl_shared'
        env['LDFLAGS'] += ' -L{}/sources/cxx-stl/gnu-libstdc++/4.8/libs/{}'.format(
            self.ctx.ndk_dir, arch)
        return env

    ls -la /opt/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/

    drwxr-xr-x 3 root root 4096 10月 12 15:23 .
    drwxr-xr-x 8 root root 4096 10月 12 15:23 ..
    drwxr-xr-x 4 root root 4096 10月 12 15:23 4.9
    -rwxr-xr-x 1 root root 1248 10月 12 15:12 Android.mk

    pythonforandroid/recipes/libgeos/__init__.py	(after)

    def get_recipe_env(self, arch):
        env = super(LibgeosRecipe, self).get_recipe_env(arch)
        env['CXXFLAGS'] += ' -I{}/sources/cxx-stl/gnu-libstdc++/4.9/include'.format(self.ctx.ndk_dir)
        env['CXXFLAGS'] += ' -I{}/sources/cxx-stl/gnu-libstdc++/4.9/libs/{}/include'.format(
            self.ctx.ndk_dir, arch)
        env['CXXFLAGS'] += ' -L{}/sources/cxx-stl/gnu-libstdc++/4.9/libs/{}'.format(
            self.ctx.ndk_dir, arch)
        env['CXXFLAGS'] += ' -lgnustl_shared'
        env['LDFLAGS'] += ' -L{}/sources/cxx-stl/gnu-libstdc++/4.9/libs/{}'.format(
            self.ctx.ndk_dir, arch)
        return env


Because there was not a 4.8 directory in android-ndk-r13b/sorces/cxx-stl/gnu-libstdc++/, I switched to 4.9.


The build succeeded, but becomes the error that libgeos_c.so.1 and libgeos_c.so are not found, when running in android.


    logcat

    I/python  (12724): Run user program, change dir and execute entrypoint
    I/python  (12724): [WARNING] [Config      ] Older configuration version detected (0 instead of 16)
    I/python  (12724): [WARNING] [Config      ] Upgrading configuration in progress.
    I/python  (12724): [INFO   ] [Logger      ] Record log in /data/data/jp.co.hds.apps.echizen_cyo.akiyamap/files/app/.kivy/logs/kivy_16-12-26_0.txt
    I/python  (12724): [INFO   ] [Kivy        ] v1.9.2-dev0
    I/python  (12724): [INFO   ] [Python      ] v2.7.2 (default, Dec 26 2016, 10:26:39) 
    I/python  (12724): [GCC 4.9.x 20150123 (prerelease)]
    I/python  (12724): [INFO   ] [Factory     ] 193 symbols loaded
    I/python  (12724): [INFO   ] [Image       ] Providers: img_sdl2 (img_tex, img_dds, img_ffpyplayer, img_gif, img_pil ignored)
    I/python  (12724): [INFO   ] [OSC         ] using <thread> for socket
    I/python  (12724): [ERROR  ] [Input       ] AndroidJoystick is not supported by your version of linux
    I/python  (12724): Traceback (most recent call last):
    I/python  (12724):   File "/home/kivy/Documents/echizen-cyo/.buildozer/android/platform/build/dists/akiyamap/private/lib/python2.7/site-packages/kivy/input/providers/__init__.py", line 57, in <module>
    I/python  (12724):   File "/home/kivy/Documents/echizen-cyo/.buildozer/android/platform/build/dists/akiyamap/private/lib/python2.7/site-packages/kivy/input/providers/androidjoystick.py", line 28, in <module>
    I/python  (12724): ImportError: No module named pygame.joystick
    I/python  (12724): [INFO   ] [Window      ] Provider: sdl2
    I/python  (12724): [INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
    I/python  (12724): [INFO   ] [GL          ] OpenGL vendor <ARM>
    I/python  (12724): [INFO   ] [GL          ] OpenGL renderer <Mali-450 MP>
    I/python  (12724): [INFO   ] [GL          ] OpenGL parsed version: 2, 0
    I/python  (12724): [INFO   ] [GL          ] Texture max size <4096>
    I/python  (12724): [INFO   ] [GL          ] Texture max units <8>
    I/python  (12724): [INFO   ] [Window      ] auto add sdl2 input provider
    I/python  (12724): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
    I/python  (12724): [INFO   ] [Text        ] Provider: sdl2
    I/python  (12724):  No handlers could be found for logger "shapely.geos"
    I/python  (12724):  Traceback (most recent call last):
    I/python  (12724):    File "/home/kivy/Documents/echizen-cyo/.buildozer/android/app/main.py", line 46, in <module>
    I/python  (12724):    File "/home/kivy/Documents/echizen-cyo/.buildozer/android/platform/build/dists/akiyamap/private/lib/python2.7/site-packages/shapely/wkb.py", line 4, in <module>
    I/python  (12724):    File "/home/kivy/Documents/echizen-cyo/.buildozer/android/platform/build/dists/akiyamap/private/lib/python2.7/site-packages/shapely/geos.py", line 75, in <module>
    I/python  (12724):    File "/home/kivy/Documents/echizen-cyo/.buildozer/android/platform/build/dists/akiyamap/private/lib/python2.7/site-packages/shapely/geos.py", line 56, in load_dll
    I/python  (12724):  OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so', '/data/data/jp.co.hds.apps.echizen_cyo.akiyamap/files/app/lib/libgeos_c.so'].
    I/python  (12724): Python for android ended.


    ls -la /data/app/jp.co.hds.apps.echizen_cyo.akiyamap-1/lib/arm	(android adb shell)

    -rwxr-xr-x system   system     857708 1979-12-31 09:30 libSDL2.so
    -rwxr-xr-x system   system     382468 1979-12-31 09:30 libSDL2_image.so
    -rwxr-xr-x system   system     286676 1979-12-31 09:30 libSDL2_mixer.so
    -rwxr-xr-x system   system     402948 1979-12-31 09:30 libSDL2_ttf.so
    -rwxr-xr-x system   system    1678400 1979-12-31 09:30 libgeos-3.5.0.so
    -rwxr-xr-x system   system     187744 1979-12-31 09:29 libgeos_c.so
    -rwxr-xr-x system   system      22000 1979-12-31 09:30 libmain.so
    -rwxr-xr-x system   system    1808100 1979-12-31 09:30 libpython2.7.so
    -rwxr-xr-x system   system     545432 1979-12-31 09:30 libsqlite3.so
