### ISSUE TITLE
Bulldozer android_new fails when ffmpeg is added to the requirements: No C Compiler found!

### ISSUE THREAD

**Issue by Fisk24** [kivy/buildozer#463]
When ffmpeg is added to the requirements line buildozer fails like so:

[INFO]:    Building ffmpeg for armeabi-v7a
[INFO]:    -> directory context /home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg
[INFO]:    -> running bash init_update_libs.sh
[INFO]:    -> running bash android_build.sh                                                                                                                                                                       
Exception in thread background thread for pid 10373:                                                                                                                                                              
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1401, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2294, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1993, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 677, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bash android_build.sh

  STDOUT:
Auto-config: --arch=arm
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying crystax headers and libraries...
Copying Objective C/C++ runtime (gnustep-libobjc2 headers and libraries)...
Copying libpng headers and libraries...
Copying libjpeg headers and libraries...
Copying libtiff headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg/toolchain-android
Cleaning up...
Done.
/home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg/x264 /home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg
./configure
No working C compiler found.
Makefile:3: config.mak: No such file or directory
make: *** [Makefile:236: config.mak] Error 1
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all
Unknown option --disable-shared, ignored
No working C compiler found.

  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 871, in <module>
    main()
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 868, in main
    ToolchainCL()
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 494, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/build.py", line 564, in build_recipes
    recipe.build_arch(arch)
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/ffmpeg/__init__.py", line 28, in build_arch
    shprint(bash, 'android_build.sh', _env=env)
  File "/home/fisk/Projects/k621/.buildozer/android/platform/python-for-android-master/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/usr/lib/python3.6/site-packages/sh.py", line 725, in next
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 656, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 677, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bash android_build.sh

  STDOUT:
Auto-config: --arch=arm
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying crystax headers and libraries...
Copying Objective C/C++ runtime (gnustep-libobjc2 headers and libraries)...
Copying libpng headers and libraries...
Copying libjpeg headers and libraries...
Copying libtiff headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg/toolchain-android
Cleaning up...
Done.
/home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg/x264 /home/fisk/Projects/k621/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg
./configure
No working C compiler found.
Makefile:3: config.mak: No such file or directory
make: *** [Makefile:236: config.mak] Error 1
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all
Unknown option --disable-shared, ignored
No working C compiler found.

  STDERR:

Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/fisk/Projects/k621/.buildozer/android/platform/build create --dist_name=k621app --bootstrap=sdl2 --requirements=python3crystax,kivy,ffmpeg --arch armeabi-v7a --copy-libs

**Comment by Fisk24** [comment]
bump?

**Comment by inclement** [comment]
Closing as stale, ffmpeg is working in p4a master.
