### ISSUE TITLE
Buildozer can't download NDK

### ISSUE THREAD

**Issue by hunternet93** [kivy/buildozer#474]
Just did a fresh install of Buildozer git master, then got the following:

```
$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
# Android ANT is missing, downloading
# Apache ANT installation done.
# Android SDK is missing, downloading
# Unpacking Android SDK
# Android SDK installation done.
# Android NDK is missing, downloading
Traceback (most recent call last):
  File "/usr/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/__init__.py", line 1026, in run_command
    self.target.run_commands(args)
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/target.py", line 101, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/__init__.py", line 175, in prepare_for_build
    self.target.install_platform()
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/targets/android.py", line 499, in install_platform
    self._install_android_ndk()
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/targets/android.py", line 309, in _install_android_ndk
    cwd=self.buildozer.global_platform_dir)
  File "/usr/lib/python3.5/site-packages/buildozer-0.33.dev0-py3.5.egg/buildozer/__init__.py", line 671, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib64/python3.5/urllib/request.py", line 1760, in retrieve
    block = fp.read(bs)
  File "/usr/lib64/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
```

It appears Google's no longer providing NDK version r9c, at least according to the [download page](https://developer.android.com/ndk/downloads/older_releases.html).

Edit: I found a link to it: [https://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2](https://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2), downloading and extracting it manually worked OK.

**Comment by tito** [comment]
Fixed in master

**Comment by mahomahomaho** [comment]
this commit looks like reverted in the meandtime https://github.com/kivy/buildozer/commit/81b1a498dd4b124db1dc2bdddd0967549e650b93 - buildozer still tries to download from 

```
 # Android NDK is missing, downloading
 # Downloading http://dl.google.com/android/ndk/android-ndk-r13b-linux-x86_64.bin
```

**Comment by Cyxapic** [comment]
Help me please! Manually download NDK it start to compile and crash with:
```
[ERROR]:   Didn't find any valid dependency graphs.
[ERROR]:   This means that some of your requirements pull in conflicting dependencies.
[ERROR]:   Exiting.
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=govnodetector --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/san/prog/python/mob_dev/govnodetector/.buildozer/android/platform/build"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by fherbine** [comment]
Same issue @Cyxapic

**Comment by JonasT** [comment]
@Cyxapic @fherbine `Didn't find any valid dependency graphs` is a very complex error and just means your project dependencies have some issue (the `--requirements` option). What exactly it is really depends on what you specified as dependencies for your specific project

**Comment by nelson6e65** [comment]
I'm having the same issue of @hunternet93 on `Buildozer 0.37`.

**Comment by mmubarak0** [comment]
use a vpn
