### ISSUE TITLE
Buildozer Error

### ISSUE THREAD

**Issue by wilsonreuben** [kivy/buildozer#492]
Why am i getting this?

`Traceback (most recent call last):
  File "build.py", line 517, in <module>
    make_package(args)
  File "build.py", line 365, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
# Command failed: python build.py --name 'Naira Manager' --version 0.1 --package org.test.nairamanager --sdk 19 --minsdk 9 --private /home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/app --orientation sensor debug
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
`

**Comment by wilsonreuben** [comment]
fixed:
followed this => http://stackoverflow.com/questions/26277154/android-compile-error-using-buildozer
