### ISSUE TITLE
sh.CommandNotFound: cmake

### ISSUE THREAD

**Issue by Allloginsbusy** [kivy/buildozer#496]
I try to build .apk with opencv(command-buildozer -v androd debug) and have error-   sh.CommandNotFound: cmake 
Full log
[INFO]:    -> directory context /home/kivy/Desktop/Malishka/.buildozer/android/platform/build/build/other_builds/opencv/armeabi-v7a/opencv
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kivy/Desktop/Malishka/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>
    main()
  File "/home/kivy/Desktop/Malishka/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/home/kivy/Desktop/Malishka/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/kivy/Desktop/Malishka/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/kivy/Desktop/Malishka/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 565, in build_recipes
  File "/home/kivy/Desktop/Malishka/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/opencv/__init__.py", line 38, in build_arch
    shprint(sh.cmake,
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 3336, in __getattr__
    return self.__env[name]
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 3213, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: cmake

Without opencv it build a good .apk .
My buildozer.spec is usual and have only 
requirements = python2,kivy,sqlite3,numpy,opencv(and tried without python2)
and log = 2
What is a problem?

**Comment by tito** [comment]
"brew install cmake"

**Comment by zaheerkzz** [comment]
> "brew install cmake"

"pip install cmake" worked for me, thanks

**Comment by aicelen** [comment]
On wsl you can also run `sudo apt install cmake`.
