### ISSUE TITLE
Possibility of building in kivy virtual machine all locally

### ISSUE THREAD

**Issue by aminrasekh** [kivy/buildozer#513]
Is it possible to set up and version (freeze) the environment in kivy virtual machine such that builds can be done all locally (no internet connection) and thus consistently and reliably (independent of later dependencies updates, external changes, etc)?

We had set up a kivy virtual machine environment that worked all fine until just recently. Here is the virtual machine:  https://pylie.com/dl/PylieBoxV1.7z 

This build command used to work fine but now throws the error below.

kivy@kivy-VirtualBox:~/Desktop/Pylie/FlyPylie$ buildozer -v android debug

----
Some context: We use Kivy Virtual Machine in public educational programs for kids and teenagers. 
Given our students have limited technical knowledge and are diverse and distributed, we need a virtual machine environment in which buildozer can do build runs consistently and reliably. 

----

Traceback (most recent call last):
  File "build.py", line 517, in <module>
    make_package(args)
  File "build.py", line 365, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
Command failed: python build.py --name FlyPylie --version 1.2.0 --package org.yourname.pylie --sdk 19 --minsdk 9 --private /home/kivy/Desktop/Pylie/FlyPylie/.buildozer/android/app --icon /home/kivy/Desktop/Pylie/FlyPylie/./icon.png --orientation landscape debug

Buildozer failed to execute the last command
The error might be hidden in the log above this error
Please read the full log, and search for it before
raising an issue with buildozer itself.
 In case of a bug report, please add a full log with log_level = 2

spec file: [buildozer.zip](https://github.com/kivy/buildozer/files/1066625/buildozer.zip)

**Comment by aminrasekh** [comment]
I just noticed the Kivy Virtual Machine is completely updated in your website. I am using using now and if it meets the needs explained above I go ahead and close this issue.
