### ISSUE TITLE
Extraction of "Kivy2.7z" failed

### ISSUE THREAD

**Issue by jacebrowning** [kivy/buildozer#516]
```
$ python --version
Python 2.7.13

$ buildozer --version
# Check configuration tokens
Buildozer 0.33

$ buildozer osx clean
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Clean the platform build directory

$ buildozer osx debug
# Check configuration tokens
# Ensure build layout
# Create directory /Users/Browning/Programs/myapp/.buildozer/osx/platform
# Check configuration tokens
# Preparing build
# Check requirements for osx
# Check if kivy-sdk-packager exists
# kivy-sdk-packager does not exist, clone it
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127    0   127    0     0     26      0 --:--:--  0:00:04 --:--:--    38
100  195k    0  195k    0     0  28043      0 --:--:--  0:00:07 --:--:--  126k
Archive:  master.zip
2ec47b2cb92ef69a71b477f55ecb1408d6369764
   creating: kivy-sdk-packager-master/
  inflating: kivy-sdk-packager-master/.gitignore
  inflating: kivy-sdk-packager-master/LICENSE
...
  inflating: kivy-sdk-packager-master/win/kivy_win_sdk.py
  inflating: kivy-sdk-packager-master/win/readme
  inflating: kivy-sdk-packager-master/win/sdl2.py
# check if Kivy.app exists in local dir
# Downloading kivy...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    322      0 --:--:-- --:--:-- --:--:--   322
100   162  100   162    0     0    149      0  0:00:01  0:00:01 --:--:--   149
# Downloading Keka as dependency (to install Kivy)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.3M  100 18.3M    0     0  58768      0  0:05:27  0:05:27 --:--:-- 37478
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $DF59CA4E
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $D1456357
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $C038CF86
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
.....................................................................................................................................
          disk image (Apple_HFS : 4): verified   CRC32 $027A7CEA
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $C038CF86
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $AAE3D326
verified   CRC32 $6507BBBB
/dev/disk6              GUID_partition_scheme
/dev/disk6s1            Apple_HFS                       /Volumes/Keka
"disk6" unmounted.
"disk6" ejected.
# Extracting and installing Kivy...
```

Then a dialog appears:

<img width="511" alt="screen shot 2017-06-19 at 8 41 01 pm" src="https://user-images.githubusercontent.com/939501/27311576-cede9720-552f-11e7-98a0-94f57661e121.png">

After closing this dialog:

```
...
# Extracting and installing Kivy...
mv: rename Kivy2.app to Kivy.app: No such file or directory
Traceback (most recent call last):
  File "/Users/Browning/.pyenv/versions/2.7.13/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/targets/osx.py", line 238, in run_commands
    func(args)
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/targets/osx.py", line 251, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/__init__.py", line 173, in prepare_for_build
    self.target.check_requirements()
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/targets/osx.py", line 105, in check_requirements
    self.ensure_kivyapp()
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/targets/osx.py", line 99, in ensure_kivyapp
    self.download_kivy(kivy_app_dir, py_branch)
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/targets/osx.py", line 84, in download_kivy
    check_call(('mv', 'Kivy{}.app'.format(py_branch), 'Kivy.app'),cwd=cwd)
  File "/Users/Browning/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('mv', 'Kivy2.app', 'Kivy.app')' returned non-zero exit status 1
```

It seems that the downloaded Kivy app is named, "Kivy.app", not "Kivy2.app".

**Comment by tshirtman** [comment]
@akshayaurora  maybe?

**Comment by inclement** [comment]
Closing as stale.
