### ISSUE TITLE
App crashes on android when using plyer camera

### ISSUE THREAD

**Issue by mokhoo** [kivy/buildozer#522]
Hi all,

I am trying to build an apk package using buildozer. The app uses kivy plyer camera. The app starts normally on the phone and crashes when trying to access the camera. I couldn't find the exact cause, after some searching I realized that maybe it is related to the new python-for-android package. Below you can find the code.

main.py
```
from kivy.app import App #for the main app
from kivy.uix.floatlayout import FloatLayout #the UI layout
from kivy.uix.label import Label #a label to show information
from plyer import camera #object to read the camera

class UI(FloatLayout):#the app ui
	def __init__(self, **kwargs):
		super(UI, self).__init__(**kwargs)
		self.lblCam = Label(text="Click to take a picture!") #create a label at the center
		self.add_widget(self.lblCam) #add the label at the screen

	def  on_touch_down(self, e):
		camera.take_picture('/storage/sdcard0/example.jpg', self.done) #Take a picture and save at this location. After will call done() callback

	def done(self, e): #receive e as the image location
		self.lblCam.text = e; #update the label to the image location
        
class Camera(App): #our app
	def build(self):
		ui = UI()# create the UI
		return ui #show it

	def on_pause(self):
		#when the app open the camera, it will need to pause this script. So we need to enable the pause mode with this method
		return True

	def on_resume(self):
		#after close the camera, we need to resume our app.
		pass

Camera().run() #start our app
        

```

buildozer.spec:

```
  
[app]
title = Python Camera
package.name = camera
package.domain = com.wordpress.bytedebugger
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.3
requirements = python2,kivy, plyer
fullscreen = 1
android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE
[buildozer]
log_level = 2
```

The app originally from:
http://blog.rhesoft.com/2014/07/19/python-for-android-tutorial-2-taking-a-picture/

**Comment by benjamingeorgedanielryan** [comment]
I have this problem as well. The output from my android device shows an import error:
```
02-26 09:24:09.721  8150  8168 I python  :  Traceback (most recent call last):
02-26 09:24:09.721  8150  8168 I python  :    File "./plyer/utils.py", line 88, in _ensure_obj
02-26 09:24:09.721  8150  8168 I python  :      mod = __import__(module, fromlist='.')
02-26 09:24:09.722  8150  8168 I python  :    File "./plyer/platforms/android/camera.py", line 1, in <module>
02-26 09:24:09.722  8150  8168 I python  :      import android
02-26 09:24:09.722  8150  8168 I python  :  ImportError: No module named 'android'

```
Also, android/camera.py is the only module in plyer that has this import statement:
```
import android
import android.activity
```

Whether the module needs updating or android should be importable... I have no idea.

**Comment by benjamingeorgedanielryan** [comment]
I figured out a way to make the camera work. It's probably not a great solution so won't be making a pull request, but if you want it to work, you can simply comment out some lines in platforms/android/camera.py as shown here:

```
# import android
# import android.activity
from os import unlink
from jnius import autoclass, cast
from plyer.facades import Camera
from plyer.platforms.android import activity

Intent = autoclass('android.content.Intent')
# PythonActivity = autoclass('org.renpy.android.PythonActivity')
MediaStore = autoclass('android.provider.MediaStore')
Uri = autoclass('android.net.Uri')


class AndroidCamera(Camera):

    def _take_picture(self, on_complete, filename=None):
        assert(on_complete is not None)
        self.on_complete = on_complete
        self.filename = filename
        # android.unbind(on_activity_result=self._on_activity_result)
        # android.bind(on_activity_result=self._on_activity_result)
        intent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
        uri = Uri.parse('file://' + filename)
        parcelable = cast('android.os.Parcelable', uri)
        intent.putExtra(MediaStore.EXTRA_OUTPUT, parcelable)
        activity.startActivityForResult(intent, 0x123)

    def _take_video(self, on_complete, filename=None):
        assert(on_complete is not None)
        self.on_complete = on_complete
        self.filename = filename
        # android.activity.unbind(on_activity_result=self._on_activity_result)
        # android.activity.bind(on_activity_result=self._on_activity_result)
        intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
        uri = Uri.parse('file://' + filename)
        parcelable = cast('android.os.Parcelable', uri)
        intent.putExtra(MediaStore.EXTRA_OUTPUT, parcelable)

        # 0 = low quality, suitable for MMS messages,
        # 1 = high quality
        intent.putExtra(MediaStore.EXTRA_VIDEO_QUALITY, 1)
        activity.startActivityForResult(intent, 0x123)

    # def _on_activity_result(self, requestCode, resultCode, intent):
    #     if requestCode != 0x123:
    #         return
    #     android.activity.unbind(on_activity_result=self._on_activity_result)
    #     if self.on_complete(self.filename):
    #         self._unlink(self.filename)

    def _unlink(self, fn):
        try:
            unlink(fn)
        except Exception:
            pass


def instance():
    return AndroidCamera()
```
Only tested photos, not video. But with this change the camera shows up and saves the picture to the file system as expected. Only weird thing is the image won't show up when I search my phone's files via my laptop. But using the phones file explorer the image is certainly there. I'm no expert, I guess that's what the un-linking code is about, unfortunately it breaks things at the moment.

**Comment by inclement** [comment]
Thanks for the note, maybe the plyer recipe should depend on the android module, although it's not strictly a hard dependency.

**Comment by Shamsyuhada** [comment]
@benjamingeorgedanielryan adding "android" to the buildozer requirements --- do you mean in the buildozer.spec?

**Comment by benjamingeorgedanielryan** [comment]
@Shamsyuhada Yes, add to the requirements list in the buildozer.spec alongside python2, kivy etc in the example above.

**Comment by Shamsyuhada** [comment]
I can't seem to make it work. Can anyone give me the full buildozer.spec?

**Comment by blinhares** [comment]
i have the same problem but put "android" on the requirements don't work.

**Comment by vyasdeep668** [comment]
**I also have same problem, putting "android" in .spec file isn't working!!!! App crashes**

**Comment by AndreMiras** [comment]
This isn't a buildozer issue to me.
And @vyasdeep668 can't say anything without build log and run log

**Comment by codinghedgehog-python** [comment]
Is there any resolution to this ? I came here with the same problem. What do I need to provide to get some assistance ?

**Comment by inclement** [comment]
@codinghedgehog-python Please feel free to open a bug on the plyer repository, but it's unlikely anyone will pick it up soon. If you'd like help debugging it yourself, I suggest asking on the kivy discord channels.
