### ISSUE TITLE
Buildozer error while packaging

### ISSUE THREAD

**Issue by susheel-smrt** [kivy/buildozer#531]
I was trying to pack an app using buildozer and im getting this error..
new to buildozer.. pl. help

```
------------
Traceback (most recent call last):
File "/usr/local/bin/buildozer", line 11, in 
load_entry_point('buildozer==0.34.dev0', 'console_scripts', 'buildozer')()
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/scripts/client.py", line 13, in main
Buildozer().run_command(sys.argv[1:])
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/init.py", line 1058, in run_command
self.target.run_commands(args)
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/target.py", line 91, in run_commands
func(args)
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/target.py", line 103, in cmd_debug
self.buildozer.build()
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/init.py", line 212, in build
self.target.build_package()
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/targets/android.py", line 663, in build_package
self._update_libraries_references(dist_dir)
File "/usr/local/lib/python2.7/dist-packages/buildozer-0.34.dev0-py2.7.egg/buildozer/targets/android.py", line 852, in _update_libraries_references
with io.open(project_fn, 'w', encoding='utf-8') as fd:
IOError: [Errno 2] No such file or directory: '/home/susheel/susi-kivy/slider_v1/.buildozer/android/platform/build/dists/Alice control/project.properties'
```

**Comment by inclement** [comment]
I don't know what is wrong here. Just in case, try using a dist name that doesn't have a space in it.

**Comment by susheel-smrt** [comment]
IOError some directory missing.. what is it actually?

**Comment by inclement** [comment]
The error is as it says, python-for-android tries to write to a file but gets an IOError, probably because the directory is missing.

**Comment by susheel-smrt** [comment]
thank you inclement... I removed the spacing in package name and it pushed the application

**Comment by inclement** [comment]
Okay, closing this issue in favour of https://github.com/kivy/python-for-android/issues/1079
