### ISSUE TITLE
Buildozer Build Error

### ISSUE THREAD

**Issue by wilsonreuben** [kivy/buildozer#538]
I don't understand the error
Line 380 is NairaManagerApp().run() in my main module
Please what is the problem here: below mu Traceback error

```
08-03 18:33:11.651 24793 24848 I python  : [INFO   ] [Base        ] Leaving application in progress...
08-03 18:33:11.651 24793 24848 I python  :  Traceback (most recent call last):
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/app/main.py", line 380, in <module>
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 828, in run
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 339, in idle
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
08-03 18:33:11.651 24793 24848 I python  :    File "_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:6554)
08-03 18:33:11.651 24793 24848 I python  :    File "_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:6446)
08-03 18:33:11.651 24793 24848 I python  :    File "_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:6395)
08-03 18:33:11.651 24793 24848 I python  :    File "_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy/_clock.c:2837)
08-03 18:33:11.651 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/label.py", line 368, in texture_update
08-03 18:33:11.651 24793 24848 I python  :    File "texture.pyx", line 760, in kivy.graphics.texture.Texture.bind (kivy/graphics/texture.c:10696)
08-03 18:33:11.651 24793 24848 I python  :    File "texture.pyx", line 785, in kivy.graphics.texture.Texture.bind (kivy/graphics/texture.c:10453)
08-03 18:33:11.661 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
08-03 18:33:11.661 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/text/markup.py", line 123, in render
08-03 18:33:11.661 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/text/__init__.py", line 585, in _render_real
08-03 18:33:11.661 24793 24848 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/text/text_pygame.py", line 91, in _render_begin
08-03 18:33:11.661 24793 24848 I python  :  pygame.error: Width or height is too large
08-03 18:33:11.741  9671  9706 I System.out: stts calls detatch()
08-03 18:33:12.181 24793 24848 I python  : Python for android ended.```

**Comment by inclement** [comment]
Try building with the new toolchain, targeting the sdl2 bootstrap (which is the default).

I'll leave this open for now, but the old toolchain is not actively maintained, and will be officially deprecated entirely soon.

**Comment by wilsonreuben** [comment]
Thanks inclement, will do that and drop feedback

**Comment by wilsonreuben** [comment]
it worked with the new toolchain(android_new)

buildozer -v android_new debug deploy run logcat > my_log.txt

Thanks inclement
