### ISSUE TITLE
complie platform failed

### ISSUE THREAD

**Issue by pyatang** [kivy/buildozer#580]
OSX  12.13
```
# Check application requirements
# Check garden requirements
# Compile platform
# Command failed: /usr/local/opt/python/bin/python2.7 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# If the error is not obvious, please raise the log_level to 2
# and retry the latest command.
# In case of a bug report, please add a full log with log_level = 2
```
is there something wrong ?

**Comment by inclement** [comment]
```
# Buildozer failed to execute the last command
# If the error is not obvious, please raise the log_level to 2
# and retry the latest command.
# In case of a bug report, please add a full log with log_level = 2
```
Follow the instructions you pasted.

**Comment by pyatang** [comment]
oh,  and now get the bug report
`[INFO]:    Cythonize kivy/lib/vidcore_lite/egl.pyx
[INFO]:    -> running cython ./kivy/lib/vidcore_lite/egl.pyx
()
           working: kivy/lib/vidcore_lite/egl.pyx:619:17: cimp...(and 51 more) Exception in thread background thread for pid 7884:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: /usr/local/bin/cython ./kivy/lib/vidcore_lite/egl.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_DISPLAY_HANDLE_T disp
        bcm.DisplayHandle D
    disp = bcm.vc_dispmanx_display_open( device )
    if disp == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to display")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:608:17: cimported module has no attribute 'BCMDisplayException'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'


  STDERR:


Traceback (most recent call last):                                             
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 916, in <module>
    main()
  File "/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 913, in main
    ToolchainCL()
  File "/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 514, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 192, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 572, in build_recipes
  File "pythonforandroid/recipe.py", line 975, in build_arch
  File "pythonforandroid/recipe.py", line 1010, in build_cython_components
  File "/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/kivy/__init__.py", line 18, in cythonize_build
    super(KivyRecipe, self).cythonize_build(env, build_dir=build_dir)
  File "pythonforandroid/recipe.py", line 1055, in cythonize_build
  File "pythonforandroid/recipe.py", line 1046, in cythonize_file
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 720, in next
    self.wait()
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/cython ./kivy/lib/vidcore_lite/egl.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_DISPLAY_HANDLE_T disp
        bcm.DisplayHandle D
    disp = bcm.vc_dispmanx_display_open( device )
    if disp == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to display")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:608:17: cimported module has no attribute 'BCMDisplayException'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'


  STDERR:

# Command failed: /usr/local/opt/python/bin/python2.7 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/tanglongyang/Downloads/webapp/cgi-bin/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2`

**Comment by pyatang** [comment]
`Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'

STDERR:`

something details, maybe it will work

**Comment by pyatang** [comment]
It still happen when cython 0.26
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:608:17: cimported module has no attribute 'BCMDisplayException'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^

**Comment by inclement** [comment]
Did you clean everything before trying again with cython 0.26? It may be worth doing so.

**Comment by pyatang** [comment]
I delete  .buildozer and  buildozer.spec  then  buildozer init   && buildozer android debug deploy run
now it still occur the same question which i posted. - -

**Comment by akshayaurora** [comment]
In your buildozer.spec make sure 

```
p4a.branch = master
```

is set.
