### ISSUE TITLE
Buidozer 0.33  AttributeError: 'module' object has no attribute 'directory'

### ISSUE THREAD

**Issue by ccharoux** [kivy/buildozer#598]
Trying to build my 1st apk

``` Unpacking Android SDK
# Run 'tar xzf android-sdk_r20-linux.tgz'
# Cwd /home/kivy/.buildozer/android/platform
# Rename /home/kivy/.buildozer/android/platform/android-sdk-linux to /home/kivy/android/platform/android-sdk-20
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 101, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 176, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 468, in install_platform
    self._install_android_sdk()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 268, in _install_android_sdk
    cwd=self.buildozer.global_platform_dir)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 614, in file_rename
    self.error('Rename {0} to {1} fails becaues {2} is not a directory'.format(source, target, os.path.directory(target)))
AttributeError: 'module' object has no attribute 'directory'
```

**Comment by Strassboom** [comment]
Would you mind disclosing how you resolved this issue? I'm running into the same one, myself.
