### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/home/kivy/buildozer/.buildozer/android/platform/build/...

### ISSUE THREAD

**Issue by ccharoux** [kivy/buildozer#603]
I refreshed my linux yesterday.
The file changed by #597 buildozer/targets/android.py is the same as before
**_The bug is still there_**

[DEBUG]:   	BUILD SUCCESSFUL
[DEBUG]:   	Total time: 14 seconds
[INFO]:    <- directory context /home/kivy/buildozer/.buildozer/android/platform/python-for-android-new-toolchain
**_[INFO]:    # Copying APK to current directory
[INFO]:    # Found APK file: /home/kivy/buildozer/.buildozer/android/platform/build/dists/approche/bin/Approche-0.1-debug.apk
[DEBUG]:   -> running cp /home/kivy/buildozer/.buildozer/android/platform/build/dists/approche/bin/Approche-0.1-debug.apk ./
Traceback (most recent call last):_**
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.35.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.35.dev0-py2.7.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.35.dev0-py2.7.egg/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.35.dev0-py2.7.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.35.dev0-py2.7.egg/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.35.dev0-py2.7.egg/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.35.dev0-py2.7.egg/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
**IOError: [Errno 2] No such file or directory: u'/home/kivy/buildozer/.buildozer/android/platform/build/dists/approche/build/outputs/apk/approche-debug.apk'**

[log.txt](https://github.com/kivy/buildozer/files/1565530/log.txt)

**Comment by ccharoux** [comment]
I forced the fixed version of android.py (#597) in my buildozer/targets folder and the bug is still there

**Comment by ccharoux** [comment]
I am new on linux
could you tell me how to **get the buildozer package updated** in my virtual box linux machine
what command do i have to enter ?
**note**: no paswd for root in that machine
