### ISSUE TITLE
Cannot build apk

### ISSUE THREAD

**Issue by RickardHultgren** [kivy/buildozer#606]
Hello,
After running *buildozer android release* I got this message:

```
# Gradle project detected, copy files /home/rickard/ecrwth/.buildozer/android/platform/build/dists/ecrwth/src/main/java
# Asking for release but P4A_RELEASE_KEYALIAS is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYSTORE_PASSWD is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYSTORE is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYALIAS_PASSWD is missing--sign will not be passed
Traceback (most recent call last):
  File "/usr/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.34', 'console_scripts', 'buildozer')()
  File "/usr/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/lib/python2.7/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/lib/python2.7/site-packages/buildozer/target.py", line 140, in cmd_release
    self.buildozer.build()
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/lib/python2.7/site-packages/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/rickard/ecrwth/.buildozer/android/platform/build/dists/ecrwth/build/outputs/apk/ecrwth-release-unsigned.apk'

```

**Comment by RickardHultgren** [comment]
Is this a valid solution?

```

mkdir -p ~/ecrwth/.buildozer/android/platform/build/dists/ecrwth/build/outputs/apk/

cp ~/ecrwth/.buildozer/android/platform/python-for-android-new-toolchain/ecrwth-1.2.3-release-unsigned.apk
 ~/ecrwth/.buildozer/android/platform/build/dists/ecrwth/build/outputs/apk/ecrwth-release-unsigned.apk
```

**Comment by AndreMiras** [comment]
@RickardHultgren yes it's a workaround. Please give https://github.com/kivy/buildozer/pull/691 a try and tell us if it fixes the issue.

**Comment by inclement** [comment]
Closing as probably fixed in buildozer master, seems to work for me. Please reopen if necessary.
