### ISSUE TITLE
Build error when building Kivy app

### ISSUE THREAD

**Issue by TomParkinson95** [kivy/buildozer#624]
```
# Android packages installation done.
# Read available permissions from api-versions.xml
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/build'
# Cwd /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found multiple valid dependency orders:
[INFO]:        ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:        ['hostpython3crystax', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:        ['hostpython2', 'pygame_bootstrap_components', 'python2', 'sdl', 'six', 'pygame', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name myapp and recipes (kivy)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> running cp -r /media/sf_Kivy_VM_Shared...(and 186 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/build/bootstrap_builds/sdl2_gradle-python2
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Recipe build order is ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    # Downloading recipes
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 29 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/hostpython2
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    -> running rm -f .mark-Python-2.7.2.tar.bz2
[INFO]:    Downloading hostpython2 from https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
- Download 98.9[INFO]:    -> running touch .mark-Python-2.7.2.tar.bz2          
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 28 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> running rm -f .mark-SDL2_image-2.0.1.tar.gz
[INFO]:    Downloading sdl2_image from https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
- Download 99.4[INFO]:    -> running touch .mark-SDL2_image-2.0.1.tar.gz      
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 28 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> running rm -f .mark-SDL2_mixer-2.0.1.tar.gz
[INFO]:    Downloading sdl2_mixer from https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
- Download 99.69[INFO]:    -> running touch .mark-SDL2_mixer-2.0.1.tar.gz      
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 26 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> running rm -f .mark-SDL2_ttf-2.0.14.tar.gz
[INFO]:    Downloading sdl2_ttf from https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
- Dow[INFO]:    -> running touch .mark-SDL2_ttf-2.0.14.tar.gz                  
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 25 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/python2
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    -> running rm -f .mark-Python-2.7.2.tar.bz2
[INFO]:    Downloading python2 from https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
-[INFO]:    -> running touch .mark-Python-2.7.2.tar.bz2                        
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 22 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> running rm -f .mark-SDL2-2.0.4.tar.gz
[INFO]:    Downloading sdl2 from https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
- Downlo[INFO]:    -> running touch .mark-SDL2-2.0.4.tar.gz                    
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 21 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> running rm -f .mark-six-1.9.0.tar.gz
[INFO]:    Downloading six from https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> running touch .mark-six-1.9.0.tar.gz
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 25 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> running rm -f .mark-master.zip
[INFO]:    Downloading pyjnius from https://github.com/kivy/pyjnius/archive/master.zip
- Download[INFO]:    -> running touch .mark-master.zip                        
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /media/sf_Kivy_VM_Shar...(and 22 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> running rm -f .mark-1.10.0.zip
[INFO]:    Downloading kivy from https://github.com/kivy/kivy/archive/1.10.0.zip
- [INFO]:    -> running touch .mark-1.10.0.zip                                
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
           w[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/build/other_builds/hostpython2/desktop
[INFO]:    -> running tar tf /media/sf_Kivy_VM_Shared...(and 48 more)
           working: Python-2.7.2/Mac/Demo/example0.html                        [INFO]:    -> running mv Python-2.7.2 /media/sf_Kivy...(and 67 more)
[INFO]:    <- directory context /media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /media/sf_Kivy_VM_Shared/hello/build/bootstrap_builds/sdl2_gradle-python2/jni
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 559, in build_recipes
  File "pythonforandroid/recipe.py", line 520, in prepare_build_dir
  File "pythonforandroid/recipe.py", line 422, in unpack
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1245, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 633, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: <exception str() failed>
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/media/sf_Kivy_VM_Shared/hello world/.buildozer/android/platform/build
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```
```

**Comment by TomParkinson95** [comment]
So you guys know, I am using this on the official Kivy-Buildozer virtual machine, and I updated the buildozer version before hand and made my buildozer.spec file before hand as well.

**Comment by inclement** [comment]
Closing as stale, I don't think this issue is occurring any more.
