### ISSUE TITLE
java.lang.ClassNotFoundException: sun.misc.BASE64Encoder	

### ISSUE THREAD

**Issue by CoelhoNL** [kivy/buildozer#639]
I have this error when i try to make a simple app with buildozer

````
leo@debian:~/PycharmProjects/Aprendendo_Kivy/android$ buildozer -v android debug deploy run logcat > my_log.txt
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[WARNING]: NDK version was set as r10.3.2, but checking the NDK dir claims it is 10.3.2.
[WARNING]: The build will try to continue, but it may fail and you should check that your setting is correct.
[WARNING]: If the NDK dir result is correct, you don't need to manually set the NDK ver.
[INFO]:    Using Crystax NDK r10.3.2
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	hkivy: includes recipes (hostpython3crystax, sdl2_image, sdl2_mixer, sdl2_ttf, python3crystax, sdl2, six, pyjnius, kivy), built for archs (armeabi-v7a)
[INFO]:    hkivy has compatible recipes, using this one
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Getting Android API version from user argument
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[WARNING]: NDK version was set as r10.3.2, but checking the NDK dir claims it is 10.3.2.
[WARNING]: The build will try to continue, but it may fail and you should check that your setting is correct.
[WARNING]: If the NDK dir result is correct, you don't need to manually set the NDK ver.
[INFO]:    Using Crystax NDK r10.3.2
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	hkivy: includes recipes (hostpython3crystax, sdl2_image, sdl2_mixer, sdl2_ttf, python3crystax, sdl2, six, pyjnius, kivy), built for archs (armeabi-v7a)
[INFO]:    hkivy has compatible recipes, using this one
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	hkivy: includes recipes (hostpython3crystax, sdl2_image, sdl2_mixer, sdl2_ttf, python3crystax, sdl2, six, pyjnius, kivy), built for archs (armeabi-v7a)
[INFO]:    hkivy has compatible recipes, using this one
[INFO]:    -> directory context /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy
[INFO]:    Selecting java build tool:
[INFO]:    Detected highest available build tools version to be 23.0.1
[INFO]:        Building with ant, as the highest build-tools-version is only 23.0.1
[DEBUG]:   -> running ant debug
[DEBUG]:   	Buildfile: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/build.xml
[DEBUG]:   	
[DEBUG]:   	-set-mode-check:
[DEBUG]:   	
[DEBUG]:   	-set-debug-files:
[DEBUG]:   	
[DEBUG]:   	-check-env:
[DEBUG]:   	 [checkenv] Android SDK Tools Revision 24.0.2
[DEBUG]:   	 [checkenv] Installed at /home/leo/.buildozer/android/platform/android-sdk-20
[DEBUG]:   	
[DEBUG]:   	-setup:
[DEBUG]:   	     [echo] Project Name: HKivy-0.1
[DEBUG]:   	  [gettype] Project Type: Application
[DEBUG]:   	
[DEBUG]:   	-set-debug-mode:
[DEBUG]:   	
[DEBUG]:   	-debug-obfuscation-check:
[DEBUG]:   	
[DEBUG]:   	-pre-build:
[DEBUG]:   	
[DEBUG]:   	-build-setup:
[DEBUG]:   	[getbuildtools] Using latest Build Tools: 23.0.1
[DEBUG]:   	     [echo] Resolving Build Target for HKivy-0.1...
[DEBUG]:   	[gettarget] Project Target:   Android 4.4.2
[DEBUG]:   	[gettarget] API level:        19
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Creating output directories if needed...
[DEBUG]:   	    [mkdir] Created dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/rsObj
[DEBUG]:   	    [mkdir] Created dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/rsLibs
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Resolving Dependencies for HKivy-0.1...
[DEBUG]:   	[dependency] Library dependencies:
[DEBUG]:   	[dependency] No Libraries
[DEBUG]:   	[dependency]
[DEBUG]:   	[dependency] ------------------
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Building Libraries with 'debug'...
[DEBUG]:   	   [subant] No sub-builds to iterate on
[DEBUG]:   	
[DEBUG]:   	-code-gen:
[DEBUG]:   	[mergemanifest] Found modified input file
[DEBUG]:   	[mergemanifest] Merging AndroidManifest files into one.
[DEBUG]:   	[mergemanifest] Manifest merger disabled. Using project manifest only.
[DEBUG]:   	     [echo] Handling aidl files...
[DEBUG]:   	     [aidl] No AIDL files to compile.
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Handling RenderScript files...
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Handling Resources...
[DEBUG]:   	     [aapt] Found modified input file
[DEBUG]:   	     [aapt] Generating resource IDs...
[DEBUG]:   	     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Handling BuildConfig class...
[DEBUG]:   	[buildconfig] Generating BuildConfig class.
[DEBUG]:   	
[DEBUG]:   	-pre-compile:
[DEBUG]:   	
[DEBUG]:   	-compile:
[DEBUG]:   	    [javac] Compiling 3 source files to /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/classes
[DEBUG]:   	    [javac] warning: [options] source value 1.6 is obsolete and will be removed in a future release
[DEBUG]:   	    [javac] warning: [options] target value 1.6 is obsolete and will be removed in a future release
[DEBUG]:   	    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[DEBUG]:   	    [javac] 3 warnings
[DEBUG]:   	
[DEBUG]:   	-post-compile:
[DEBUG]:   	
[DEBUG]:   	-obfuscate:
[DEBUG]:   	
[DEBUG]:   	-dex:
[DEBUG]:   	      [dex] input: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/classes
[DEBUG]:   	      [dex] Found modified input file
[DEBUG]:   	      [dex] Converting compiled files and external libraries into /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/classes.dex...
[DEBUG]:   	
[DEBUG]:   	-crunch:
[DEBUG]:   	   [crunch] Crunching PNG Files in source dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/src/main/res
[DEBUG]:   	   [crunch] To destination dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/res
[DEBUG]:   	   [crunch] Processing image to cache: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/src/main/res/drawable/icon.png => /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/res/drawable/icon.png
[DEBUG]:   	   [crunch]   (processed image to cache entry /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/res/drawable/icon.png: 126% size of source)
[DEBUG]:   	   [crunch] Crunched 1 PNG files to update cache
[DEBUG]:   	
[DEBUG]:   	-package-resources:
[DEBUG]:   	     [aapt] Creating full resource package...
[DEBUG]:   	     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
[DEBUG]:   	     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
[DEBUG]:   	
[DEBUG]:   	-package:
[DEBUG]:   	[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[DEBUG]:   	[apkbuilder] Creating HKivy-0.1-debug-unaligned.apk and signing it with a debug key...
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED
[DEBUG]:   	/home/leo/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:962: The following error occurred while executing this line:
[DEBUG]:   	/home/leo/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:973: The following error occurred while executing this line:
[DEBUG]:   	/home/leo/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:312: java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
[DEBUG]:   		at com.android.sdklib.internal.build.SignedJarBuilder.<init>(SignedJarBuilder.java:177)
[DEBUG]:   		at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:446)
[DEBUG]:   		at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:394)
[DEBUG]:   		at com.android.ant.ApkBuilderTask.execute(ApkBuilderTask.java:334)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at java.base/java.util.Vector.forEach(Vector.java:1362)
[DEBUG]:   		at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at java.base/java.util.Vector.forEach(Vector.java:1362)
[DEBUG]:   		at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
[DEBUG]:   		at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at java.base/java.util.Vector.forEach(Vector.java:1362)
[DEBUG]:   		at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
[DEBUG]:   		at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at java.base/java.util.Vector.forEach(Vector.java:1362)
[DEBUG]:   		at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[DEBUG]:   		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[DEBUG]:   		at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[DEBUG]:   		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG]:   		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG]:   		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[DEBUG]:   		at org.apache.tools.ant.Task.perform(Task.java:346)
[DEBUG]:   		at org.apache.tools.ant.Target.execute(Target.java:448)
[DEBUG]:   		at org.apache.tools.ant.Target.performTasks(Target.java:469)
[DEBUG]:   		at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[DEBUG]:   		at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
[DEBUG]:   		at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[DEBUG]:   		at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[DEBUG]:   		at org.apache.tools.ant.Main.runBuild(Main.java:849)
[DEBUG]:   		at org.apache.tools.ant.Main.startAnt(Main.java:228)
[DEBUG]:   		at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
[DEBUG]:   		at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
[DEBUG]:   	Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
[DEBUG]:   		at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1385)
[DEBUG]:   		at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1334)
[DEBUG]:   		at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1089)
[DEBUG]:   		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[DEBUG]:   		... 68 more
[DEBUG]:   	
[DEBUG]:   	Total time: 1 second
Exception in thread background thread for pid 6482:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leo/.local/lib/python3.5/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/leo/.local/lib/python3.5/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/leo/.local/lib/python3.5/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/leo/.buildozer/android/platform/apache-ant-1.10.2/bin/ant debug

  STDOUT:
Buildfile: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.0.2
 [checkenv] Installed at /home/leo/.buildozer/android/platform/android-sdk-20

-setup:
     [echo] Project Name: HKivy-0.1
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.1
     [echo] Resolving Build Target for HKivy-0.1...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/rsObj
    [mkdir] Created dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for HKivy-0.1...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Found modified input file
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found modified input file
     [aapt] Generating resource IDs...
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 3 source files to /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/classes
    [javac] warning: [options] source value 1.6 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.6 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] 3 warnings

-post-compile:

-obfuscate:

-dex:
      [dex] input: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/classes
      [dex] Found modified input file
      [dex] Converting compiled files and external libraries into /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/classes.dex...

-crunch:
   [crunch] Crunching PNG Files in source dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/src/main/res
   [crunch] To destination dir: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/res
   [crunch] Processing image to cache: /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/src/main/res/drawable/icon.png => /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/res/drawable/icon.png
   [crunch]   (processed image to cache entry /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy/bin/res/drawable/icon.png: 126% size of source)
   [crunch] Crunched 1 PNG files to update cache

-package-resources:
     [aapt] Creating full resource package...
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')

-package:
[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[apkbuilder] Creating HKivy-0.1-debug-unaligned.apk and signing it with a debug key...

BUILD FAILED
/home/leo/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:962: The following error occurred while executing this line:
/home/leo/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:973: The following error occurred while executing this line:
/home/leo/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:312: java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at com.android.sdklib.internal.build.SignedJarBuilder.<init>(SignedJarBuilder.java:177)
	at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:446)
	at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:394)
	at com.android.ant.ApkBuilderTask.execute(ApkBuilderTask.java:334)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at java.base/java.util.Vector.forEach(Vector.java:1362)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at java.base/java.util.Vector.forEach(Vector.java:1362)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at java.base/java.util.Vector.forEach(Vector.java:1362)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at java.base/java.util.Vector.forEach(Vector.java:1362)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:346)
	at org.apache.tools.ant.Target.execute(Target.java:448)
	at org.apache.tools.ant.Target.performTasks(Target.java:469)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:849)
	at org.apache.tools.ant.Main.startAnt(Main.java:228)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1385)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1334)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 68 more

Total time: 1 second


  STDERR:


[INFO]:    STDOUT (last 20 lines of 170):
		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)	
	at org.apache.tools.ant.Task.perform(Task.java:346)	
	at org.apache.tools.ant.Target.execute(Target.java:448)	
	at org.apache.tools.ant.Target.performTasks(Target.java:469)	
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)	
	at org.apache.tools.ant.Project.executeTarget(Project.java:1370)	
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)	
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)	
	at org.apache.tools.ant.Main.runBuild(Main.java:849)	
	at org.apache.tools.ant.Main.startAnt(Main.java:228)	
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)	
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)	
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder	
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1385)	
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1334)	
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1089)	
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)	
	... 68 more	
	
Total time: 1 second
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/leo/PycharmProjects/Aprendendo_Kivy/android/.buildozer/android/platform/build/dists/hkivy && /home/leo/.buildozer/android/platform/apache-ant-1.10.2/bin/ant debug

[WARNING]: ERROR: /home/leo/.buildozer/android/platform/apache-ant-1.10.2/bin/ant failed!

**Comment by andre-57** [comment]
the same problem 
```
BUILD FAILED
/home/andre/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:958: The following error occurred while executing this line:
/home/andre/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:969: The following error occurred while executing this line:
/home/andre/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:312: java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

```

**Comment by ahmedfgad** [comment]
How to solve it

**Comment by AndreMiras** [comment]
Not OS X user here, but I could reproduce this issue in a [macOS Sierra Vagrant VM](https://github.com/AndrewDryga/vagrant-box-osx).

I had Java JDK 10 installed via:
```sh
brew cask install java
```
Proof:
```sh
brew cask list --versions | grep java
java 10.0.1,10:fb4372174a714e6b8c52526dc134031e
```
To fix it I had to uninstall and downgrade to Java8.
```sh
brew cask uninstall java
brew cask install java8
```
Proof that the correct version is now installed:
```sh
brew cask list --versions | grep -i java                                                                                                                                                                                   
java8 1.8.0_172-b11,a58eab1ec242421181065cdc37240b08

java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

Additional info:
```sh
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.2 (16C67)
      Kernel Version: Darwin 16.3.0
      Boot Volume: vagrant-box-osx
      Boot Mode: Normal
      Computer Name: vagrant
      User Name: vagrant (vagrant)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 55 minutes
```
```sh
cython --version
Cython version 0.25.2
```
```sh
pip freeze
appdirs==1.4.3
buildozer==0.34
colorama==0.3.9
Cython==0.25.2
Jinja2==2.10
MarkupSafe==1.0
pexpect==4.6.0
ptyprocess==0.5.2
sh==1.12.4
six==1.11.0
virtualenv==16.0.0
```

Feel free to reopen the ticket if downgrading to Java8 doesn't fix it for you.
If you reopen please share relevant info (e.g. `java-version` output).

**Comment by IonutArhire** [comment]
I'm on linux mint 19.

I solved this problem by installing java8 (didn't even uninstall openjdk) and then setting the java environment variables (I think these variables are the solution to the problem). I followed this guide which is for linux mint but I think it should also work for related OS'es: https://forums.linuxmint.com/viewtopic.php?t=249735
