### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by atckun** [kivy/buildozer#649]
```
 File "/home/sadikmaxlk/.local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.5/dist-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.5/dist-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python3.5/dist-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python3.5/dist-packages/buildozer-0.35.dev0-py3.5.egg/buildozer/targets/android.py", line 822, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sadikmaxlk/Desktop/pythonKivy/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/myapp-debug.apk'

```

**Comment by zhaomh1998** [comment]
I believe it's a bug on buildozer. For my case I found my apk in
<Project Folder>/.buildozer/android/platform/build/dists/<appname>/bin

So look in
/home/sadikmaxlk/Desktop/pythonKivy/.buildozer/android/platform/build/dists/myapp/bin

**Comment by guysoft** [comment]
There is a line missing here that helps understand what is going on.
P4A is renaming the file based on the version number, and then buildozer does not find it:

```
INFO]:    # Add version number to APK
[INFO]:    # APK renamed to myapp-0.1-debug.apk
[DEBUG]:   -> running cp /buildozer/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/debug/myapp-debug.apk myapp-0.1-debug.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No compiled python is present to zip, skipping.
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/targets/android.py", line 871, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/buildozer/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/myapp-debug.apk'
```

**Comment by guysoft** [comment]
The error is coming from here:
https://github.com/kivy/buildozer/blob/master/buildozer/targets/android.py#L863

**Comment by guysoft** [comment]
There is a change in #700 that clams to fix it. Will try ton install buildozer from master and see if it works

**Comment by guysoft** [comment]
This issue can be closed, the solution is already merged to master.

The following fixed it for me:
```
pip3 install https://github.com/kivy/buildozer/archive/master.zip
```

**Comment by inclement** [comment]
Closing as stale, I think this is fixed.
