### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/home/samurai-girl/python2/.buildozer/android/platform/build/dists/test/build/outputs/apk/test-debug.apk'

### ISSUE THREAD

**Issue by samurai-girl** [kivy/buildozer#662]
Hi, Please assist with below error. Looks like the build is successful but for some reason its failing to deploy to my phone. Tried this with both Python 2.7 and Python 3.5 with same result. Thanks

[DEBUG]:   	BUILD SUCCESSFUL
[DEBUG]:   	Total time: 17 seconds
[INFO]:    <- directory context /home/samurai-girl/python2/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Copying APK to current directory
[INFO]:    # Found APK file: /home/samurai-girl/python2/.buildozer/android/platform/build/dists/test/bin/Test-0.1-debug.apk
[DEBUG]:   -> running cp /home/samurai-girl/python2/.buildozer/android/platform/build/dists/test/bin/Test-0.1-debug.apk ./
Traceback (most recent call last):
  File "/home/samurai-girl/.local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/home/samurai-girl/.local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/samurai-girl/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/home/samurai-girl/.local/lib/python2.7/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/samurai-girl/.local/lib/python2.7/site-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/home/samurai-girl/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/home/samurai-girl/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/samurai-girl/python2/.buildozer/android/platform/build/dists/test/build/outputs/apk/test-debug.apk'

**Comment by inclement** [comment]
Closing as fixed.
