### ISSUE TITLE
Post build fails because copying built apk fails

### ISSUE THREAD

**Issue by insumo-w** [kivy/buildozer#671]
```[DEBUG]:   	-post-build:
[DEBUG]:   	   [delete] Deleting directory /home/user/new/.buildozer/android/platform/build/dists/myapp/tmp-src
[DEBUG]:   	
[DEBUG]:   	debug:
[DEBUG]:   	
[DEBUG]:   	BUILD SUCCESSFUL
[DEBUG]:   	Total time: 4 seconds
[INFO]:    <- directory context /home/user/new/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Copying APK to current directory
[INFO]:    # Found APK file: /home/user/new/.buildozer/android/platform/build/dists/myapp/bin/MyApplication-0.1-debug.apk
[DEBUG]:   -> running cp /home/user/new/.buildozer/android/platform/build/dists/myapp/bin/MyApplication-0.1-debug.apk ./
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.34', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/user/new/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/myapp-debug.apk'
user@t220:~/new$ 
```

-----------------------------

**It finds the a apk here...

/home/user/new/.buildozer/android/platform/build/dists/myapp/bin/MyApplication-0.1-debug.apk ./

which actually copies to {buildozer} and not {buildozer}/bin ?

But also copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest)) points to a location which doesn't exist...

u'/home/user/new/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/myapp-debug.apk'**

_temp workaround. I manually copied the apk to {buildozer}/bin and modified the state.db in order to push application to device._

**Comment by Davincible** [comment]
I also had this issue in my buildozerVM but since I did a fresh install on a clean ubuntu 18 I haven't had the issue.

**Comment by AndreMiras** [comment]
This is a kinda known issue #312, #597, #599, #603, #606, #613, #632, #636, #647, #649, #662.
Another way to work around is to have a very up to date Android SDK.

**Comment by inclement** [comment]
Closing as fixed in buildozer master.
