### ISSUE TITLE
Python 3 + Numpy + Kivy compilation problem

### ISSUE THREAD

**Issue by Groupustule** [kivy/buildozer#698]
Hi all,

I have created a program in Python 3+ that uses kivy and the matrix dot product from numpy. 
My app works perfectly on Windows (I coded using Eclipse) but when I try to compile it for Android using buildozer, I get an error (see below). I do not understand why buildozer won't compile my program as an apk. Also I do not understand why I should add "hostpython2" within the requirements since I coded in python 3+ (I tried without, it still returns an error). I am using Virtualbox version 5.2.16 to emulate Linux on Windows 10 (64bits). It is the latest version but I also tried 5.0.26 without success following an old post recommendations. 

Note that I learnt to code by myself (from scratch) 3 months ago only and my understanding of how to use Linux is really really basic, so please go easy on me... I can follow detailed instructions though (and yes I have been reading and trying A LOT of other potential solutions before posting this request)! ;)

Help me please.

**Here are the last lines from the Terminal:**

Compiling_ /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/xml/sax/xmlreader.py ...
[INFO]:    Selecting java build tool:
[INFO]:    Detected highest available build tools version to be 19.1.0
[INFO]:        Building with ant, as the highest build-tools-version is only 19.1.0
[INFO]:    -> running ant debug
           working: /home/kivy/.buildozer/android/platform/Exception in thread background thread for pid 27999:g error occurred while executing this line:                                                                
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: /home/kivy/.buildozer/android/platform/apache-ant-1.9.4/bin/ant debug

  STDOUT:
Buildfile: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 22.6.2
 [checkenv] Installed at /home/kivy/.buildozer/android/platform/android-sdk-20

-setup:
     [echo] Project Name: AlphaBetaConverter-0.1
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:
     [copy] Copying 25 files to /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/tmp-src

-build-setup:
[getbuildtools] Using latest Build Tools: 19.1.0
     [echo] Resolving Build Target for AlphaBetaConverter-0.1...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/res
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/rsObj
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/rsLibs
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/gen
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/classes
    [mkdir] Created dir: /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for AlphaBetaConverter-0.1...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 26 source files to /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/tmp-src/org/kivy/android/PythonService.java:108: error: multi-catch statement is not supported in -source 1.5
    [javac]             } catch (NoSuchMethodException | IllegalAccessException |
    [javac]                                            ^
    [javac]   (use -source 7 or higher to enable multi-catch statement)
    [javac] 1 error
    [javac] 3 warnings

BUILD FAILED
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 8 seconds

  STDERR:

[INFO]:    STDOUT (last 20 lines of 79):
		
-pre-compile:	
	
-compile:	
    [javac] Compiling 26 source files to /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/bin/classes	
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release	
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release	
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.	
    [javac] /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp/tmp-src/org/kivy/android/PythonService.java:108: error: multi-catch statement is not supported in -source 1.5	
    [javac]             } catch (NoSuchMethodException | IllegalAccessException |	
    [javac]                                            ^	
    [javac]   (use -source 7 or higher to enable multi-catch statement)	
    [javac] 1 error	
    [javac] 3 warnings	
	
BUILD FAILED	
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:720: The following error occurred while executing this line:	
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.	
	
Total time: 8 seconds
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/kivy/Desktop/MyApp/.buildozer/android/platform/build/dists/myapp && /home/kivy/.buildozer/android/platform/apache-ant-1.9.4/bin/ant debug

[WARNING]: ERROR: /home/kivy/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/kivy/Desktop/MyApp/.buildozer/android/platform/build apk --bootstrap=sdl2 --dist_name myapp --name AlphaBetaConverter --version 0.1 --package com.mydomain.myapp --android_api 19 --minsdk 9 --private /home/kivy/Desktop/MyApp/.buildozer/android/app --icon /home/kivy/Desktop/MyApp/./App_logo.png --orientation portrait --copy-libs
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
kivy@kivyvm:~/Desktop/MyApp$

**Comment by AndreMiras** [comment]
Apply the fix from the linked ticket. Basically you need to update the file it's complaining about. Changing it's content as mentioned here https://github.com/kivy/buildozer/issues/625#issuecomment-398546396
The Dockerfile just show an example of updating it from the command line with a sed command. But you can edit it with your text editor.

**Comment by Groupustule** [comment]
Ok, I am reading through it now thank you!
I still want to understand what happened even though I managed yesterday night to finally compile my apk by removing the numpy dependy (it still gives an error - a new one - when I put numpy as a requirement though). I will try the new Kivy VM before posting again about this new error.

Thanks again!

**Comment by Groupustule** [comment]
Hi again AndreMiras,
After reading all the solutions you gave me I am confronted with 2 problems:
1) I do not know how to "Build with:  docker build --tag=buildozer ." I tried putting "docker build --tag=buildozer ." into the terminal but it returns "bash: docker: command not found";

2) I tried changing "~/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml", but I cannot find such a path anywhere on my VirtualBox...

I am using the VirtualBox (from: https://kivy.org/#download) that was meant to be preloaded with everything. I have now tried so many things without success... 

Do you have any suggestion please?

**Comment by AndreMiras** [comment]
You don't necessarily need to use the Dockerfile even though you cold. It was just an example on how to workaround the error.
If you read the logs you shared first in this ticket, it gives the exact path of the file you need to update.
```
BUILD FAILED
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.
```
So if you get this error again, simply edit that file changing it with the value mentioned in both #625 and Dockerfile.

Regarding the error you got `bash: docker: command not found`, it's a pretty common/trivial one, but this bug tracker is not a chat or a forum to help with this kind of things. You may get better luck on IRC.

**Comment by Groupustule** [comment]
Nothing I have tried worked... I don't get what I am doing wrong this is so frustrating :(
