### ISSUE TITLE
SDL_JAVA_PACKAGE_PATH error?

### ISSUE THREAD

**Issue by cashclickermg** [kivy/buildozer#714]
### Versions

* Python: 3.5.3
* OS: XUBUNTU 18.04 (Downloaded Buildozer VM)
* Kivy: 1.90.0 (not used)
* Cython: 0.28.5

### Description

When i build the apk with
```sh
requirements = kivy
```
then it **compiles**, but crashes on Android because of the missing pygame (=1.9.4).

When i build it with
```sh
requirements = pygame
```
there is an error

### Logs

```
[INFO]:    -> running ndk-build V=1
Exception in thread background thread for pid 29139:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/kivy/.buildozer/android/platform/android-ndk-r9c/ndk-build V=1

  STDOUT:
/home/kivy/Desktop/Test_APP/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni/sdl/Android.mk:8: *** Please define SDL_JAVA_PACKAGE_PATH to the path of your Java package with dots replaced with underscores, for example "com_example_SanAngeles".  Stop.


  STDERR:


[INFO]:    STDOUT:
	/home/kivy/Desktop/Test_APP/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni/sdl/Android.mk:8: *** Please define SDL_JAVA_PACKAGE_PATH to the path of your Java package with dots replaced with underscores, for example "com_example_SanAngeles".  Stop.
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/kivy/Desktop/Test_APP/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni && /home/kivy/.buildozer/android/platform/android-ndk-r9c/ndk-build V=1

[WARNING]: ERROR: /home/kivy/.buildozer/android/platform/android-ndk-r9c/ndk-build failed!
```

**and i dont understand what i have to define here:**

```sh
Please define SDL_JAVA_PACKAGE_PATH to the path of your Java package with dots replaced with underscores, for example "com_example_SanAngeles".  Stop.
```

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]
title = testapp1
package.name = testapp1
package.domain = org.test.app1

source.dir = .
build_dir = /build/testapp1

source.include_exts = py,png,jpg,kv,atlas

version = 0.1

requirements = pygame

orientation = landscape
fullscreen = 1

android.branch = master

[buildozer]
log_level = 2

warn_on_root = 1

```

Please help :)
Thanks

**Comment by cashclickermg** [comment]
Short update:
`requirements = kivy` now doesnt work anymore :)
Thx

**Comment by tito** [comment]
Use latest buildozer and python-for-android master, with requirements kivy it works. If pygame doesn't work, report to kivy/python-for-android, not buildozer.
