### ISSUE TITLE
I can't package my app the way i always did.

### ISSUE THREAD

**Issue by yunus-ceyhan** [kivy/buildozer#733]
I have packed my apps successfully so many times so far. But this time it gives that error at the beginning even only with the "hello world" app. i'm not doing anything different than i did before.

Installation on  Ubuntu 16.04 (64bit);

```
    1  apt-get install python-pip -y&& pip install --upgrade pip
    2  pip install --upgrade buildozer
    3  pip install --upgrade cython==0.21
    4  dpkg --add-architecture i386
    5  apt-get update
    6  apt-get install build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 python2.7 python2.7-dev openjdk-8-jdk unzip zlib1g-dev zlib1g:i386
    7  cd test
    8  buildozer init
    9  cd test
   10  buildozer android debug
```

**Error** 

```
root@ubuntu-s-1vcpu-2gb-fra1-01:~# cd test
root@ubuntu-s-1vcpu-2gb-fra1-01:~/test# buildozer android debug
# Check configuration tokens
Buildozer is running as root!
This is not recommended, and may lead to problems later.
Are you sure you want to continue [y/n]? y
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 176, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 467, in install_platform
    self._install_p4a()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 524, in _install_p4a
    deps = re.findall("^install_reqs = (\[[^\]]*\])", setup, re.DOTALL | re.MULTILINE)[0]
IndexError: list index out of range

```

**Comment by AndreMiras** [comment]
dup of https://github.com/kivy/buildozer/issues/731

**Comment by yunus-ceyhan** [comment]
Thank you so much.

**Comment by AndreMiras** [comment]
Fixed in https://github.com/kivy/buildozer/pull/736
