### ISSUE TITLE
Docker doesn't build

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/buildozer#751]
When I try to build docker image, by command:

```docker build -t buildozer . ```

then it fails with following error:

```
----------------------------------------
  Failed building wheel for buildozer
  Running setup.py clean for buildozer
Failed to build buildozer
Installing collected packages: Cython, ptyprocess, pexpect, virtualenv, buildozer
  Running setup.py install for buildozer: started
    Running setup.py install for buildozer: finished with status 'done'
Successfully installed Cython-0.25.2 buildozer-0.35 pexpect-4.6.0 ptyprocess-0.6.0 virtualenv-16.1.0
Removing intermediate container 50a4b9b28ceb
 ---> 718711a77565
Step 15/18 : RUN cd /tmp/ && buildozer init && buildozer android adb -- version && cd -
 ---> Running in 123ae72395cc
File buildozer.spec created, ready to customize!
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
Traceback (most recent call last):
  File "/home/user/.local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.35', 'console_scripts', 'buildozer')()
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 942, in cmd_adb
    self.install_platform()
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 467, in install_platform
    self._install_p4a()
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 524, in _install_p4a
    deps = re.findall("^install_reqs = (\[[^\]]*\])", setup, re.DOTALL | re.MULTILINE)[0]
IndexError: list index out of range
The command '/bin/sh -c cd /tmp/ && buildozer init && buildozer android adb -- version && cd -' returned a non-zero code: 1

```

It's because more recent python-for-android changed way to specify install_regs , and buildozer changed it in master branch, but not in this 0.35 ver which went to pypi. 

So either, Dockerfile should be adapted to install buildozer from git+https://github.com/kivy/buildozer , or recent version of buildozer should go to Pypi.

**Comment by mahomahomaho** [comment]
In fact, it's problem with current buildozer v 0.35 - if you try to do 

1. pip install buildozer
2. buildozer init
3. buildozer android debug

then it will fail with the same error. So I think that newer buildozer should go to pypi

**Comment by AndreMiras** [comment]
Fixed with recent rework on the Docker image. Also now the image is built as part of the continuous integration, see #848.
Plus we now publish the Docker image to DockerHub so you don't have to build it yourself
