### ISSUE TITLE
'# Android NDK is missing, downloading' - Android NDK is installed

### ISSUE THREAD

**Issue by drjoms** [kivy/buildozer#769]
### Versions

* Python:
python --version
Python 3.6.5
eselect  python list
Available Python interpreters, in order of preference:
  [1]   python3.6
  [2]   python2.7
  [3]   python3.4
  [4]   python3.5 (fallback)

* OS:
uname -a
Linux (none)dimko's Desktop 4.17.0-gentoo #6 SMP PREEMPT Sat Dec 8 22:29:46 GMT 2018 x86_64 AMD Ryzen 5 1600 Six-Core Processor AuthenticAMD GNU/Linux

* Kivy:
dev-python/Kivy
      Latest version available: 1.10.1
      Latest version installed: 1.10.1

* Cython:
  dev-python/cython
      Latest version available: 0.25.2
      Latest version installed: 0.25.2

### Description
 /home/dimko/.local/bin/buildozer android debug deploy run
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
# Apache ANT found at /home/dimko/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/dimko/.buildozer/android/platform/android-sdk-20
# Android NDK is missing, downloading
Traceback (most recent call last):
  File "/home/dimko/.local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/__init__.py", line 176, in prepare_for_build
    self.target.install_platform()
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/targets/android.py", line 507, in install_platform
    self._install_android_ndk()
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/targets/android.py", line 319, in _install_android_ndk
    cwd=self.buildozer.global_platform_dir)
  File "/home/dimko/.local/lib64/python3.6/site-packages/buildozer/__init__.py", line 687, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib64/python3.6/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/usr/lib64/python3.6/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file

stuff never worked, i am trying to get it to work for a first time.

trying to use simple app i foudn on internet (50 lines or so)from Kivy to work on android.

**Comment by fr3nzy** [comment]
@drjoms add the extracted folder to the `android.ndk_path` line in your `buildozer.spec` file, if you haven;t already figured it out :)

**Comment by drjoms** [comment]
yeah someone suggested that and it helped.

There is another problem now, cant download android sdk files newer than 
version 20, and buildozer fails because of it.

It's documented in another email send to group.

but thanks!

Dmitri

**Comment by homdx** [comment]
@mahomahomaho 
Error with:
buildozer.spec
```
android.api = 28
android.minapi = 21
android.sdk = 24
android.ndk = 17c
```
Log:
```
   creating: android-ndk-r17c/sources/android/renderscript/                                                                                                                                                                                   
  inflating: android-ndk-r17c/sources/android/renderscript/NOTICE                                                                                                                                                                             
  inflating: android-ndk-r17c/sources/android/renderscript/Android.mk                                                                                                                                                                         
  inflating: android-ndk-r17c/sources/android/renderscript/repo.prop                                                                                                                                                                          
  inflating: android-ndk-r17c/CHANGELOG.md                                                                                                                                                                                                    
  inflating: android-ndk-r17c/ndk-stack                                                                                                                                                                                                       
# Command failed: unzip /home/user/.buildozer/android/platform/android-ndk-r17c-linux-x86_64.zip
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by BlackD77** [comment]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
# Command failed: /Users/divyanshjain/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by Julian-O** [comment]
Code now supports different URL formats when version>=23.

Closing as complete.
