### ISSUE TITLE
Buildozer 0.37 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 

### ISSUE THREAD

**Issue by homdx** [kivy/buildozer#782]
I use this env in docker provided by @JonasT
https://github.com/JonasT/p4a-build-spaces

./p4aspaces shell p4a-py3-api28ndk21

#buildozer init
```
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 122, in __init__
    self.config.read(filename)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1665: ordinal not in range(128)
```
Buildozer 0.37

**Comment by AndreMiras** [comment]
Looks like https://github.com/kivy/buildozer/pull/789 can you confirm @homdx ?

**Comment by homdx** [comment]
Great!!! It's are fixed
Thanks to @guysoft

```
./p4aspaces shell p4a-py3-api28ndk21
Sending build context to Docker daemon  7.168kB
Step 1/31 : FROM ubuntu
 ---> 1d9c17228a9e
Step 2/31 : ENV SDK_TOOLS="sdk-tools-linux-4333796.zip"
 ---> Using cache
 ---> 304f2f432153
Step 3/31 : ENV NDK_DL="https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip"
 ---> Using cache
 ---> addbf4f66f6c
Step 4/31 : ENV NDKVER=r17c
 ---> Using cache
 ---> 8e9d71d8b0fa
Step 5/31 : ENV NDKDIR=/ndk/
 ---> Using cache
 ---> 4892c51ff6e3
Step 6/31 : ENV NDKAPI=21
 ---> Using cache
 ---> 6c5180f8ab9f
Step 7/31 : ENV ANDROIDAPI=28
 ---> Using cache
 ---> c8a247d4c724
Step 8/31 : ENV PIP=pip3
 ---> Using cache
 ---> b683e2395d0a
Step 9/31 : RUN apt update --fix-missing && apt upgrade -y
 ---> Using cache
 ---> 71e84b073390
Step 10/31 : RUN apt update && apt install -y zip python3 python-pip python python3-virtualenv python-virtualenv python3-pip curl wget lbzip2 bsdtar && dpkg --add-architecture i386 && apt update && apt install -y build-essential libstdc++6:i386 zlib1g-dev zlib1g:i386 openjdk-8-jdk libncurses5:i386 && apt install -y libtool automake autoconf unzip pkg-config git ant gradle rsync
 ---> Using cache
 ---> 299e690a724d
Step 11/31 : RUN mkdir /sdk-install/
 ---> Using cache
 ---> c47430017158
Step 12/31 : RUN cd /sdk-install && wget https://dl.google.com/android/repository/${SDK_TOOLS}
 ---> Using cache
 ---> 64f25dc52c8b
Step 13/31 : RUN cd /sdk-install && unzip ./sdk-tools-*.zip && chmod +x ./tools//bin/sdkmanager
 ---> Using cache
 ---> 9a14bcf6c15c
Step 14/31 : RUN yes | /sdk-install/tools/bin/sdkmanager --licenses
 ---> Using cache
 ---> 3a08a672ffd6
Step 15/31 : RUN /sdk-install/tools/bin/sdkmanager --update
 ---> Using cache
 ---> 653039d19cf4
Step 16/31 : RUN /sdk-install/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
 ---> Using cache
 ---> 47285998d950
Step 17/31 : RUN mkdir -p /tmp/ndk/ && cd /tmp/ndk/ && wget ${NDK_DL} && unzip -q android-ndk*.zip && mv android-*/ /ndk/
 ---> Using cache
 ---> fd677f3f47a5
Step 18/31 : RUN apt install -y libffi-dev libssl-dev
 ---> Using cache
 ---> d916e7d7cf2e
Step 19/31 : RUN $PIP install -U Cython
 ---> Using cache
 ---> dd00e531fd75
Step 20/31 : RUN apt install -y cmake
 ---> Using cache
 ---> 08394cbfc5d6
Step 21/31 : RUN $PIP install -U 'https://github.com/kivy/python-for-android/archive/master.zip'  # p4a build 031d8731-5001-4124-8bee-c227203d78a2
 ---> Using cache
 ---> 363cbb6742ba
Step 22/31 : RUN mkdir -p /tmp/test-app/ && cd /tmp/test-app && git clone https://github.com/kivy/python-for-android/ .
 ---> Using cache
 ---> 616ae7946e20
Step 23/31 : RUN cp -R /tmp/test-app/testapps/testapp_keyboard/ /root/testapp-sdl2-keyboard/
 ---> Using cache
 ---> e0d94d0095d5
Step 24/31 : RUN cp -R /tmp/test-app/testapps/testapp_flask/ /root/testapp-webview-flask/
 ---> Using cache
 ---> a8b6a59b5b94
Step 25/31 : RUN cp -R /tmp/test-app/testapps/testapp_nogui/ /root/testapp-service_only-nogui/
 ---> Using cache
 ---> 7c5b69fe53c7
Step 26/31 : RUN mkdir /root/output
 ---> Using cache
 ---> 8ae823b13775
Step 27/31 : VOLUME /root/output
 ---> Using cache
 ---> c2233da6f4c8
Step 28/31 : WORKDIR /root/
 ---> Using cache
 ---> 326b24a8c592
Step 29/31 : RUN echo 'bash' > /tmp/launchcmd.txt
 ---> Using cache
 ---> 5c47b6b76c64
Step 30/31 : RUN echo '#!/usr/bin/python3\nimport json\nimport os\nprint("echo \"\"")\nprint("echo \"To build a kivy demo app, use this command:\"")\nif os.environ["PIP"] == "pip2":\n    print("echo \"cd ~/testapp-sdl2-keyboard && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --requirements=kivy,python2 --private .\"")\n    print("shopt -s expand_aliases")\n    print("alias testbuild=\"cd ~/testapp-sdl2-keyboard && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --requirements=kivy,python2 --private . && cp *.apk ~/output\"")\n    print("alias testbuild_webview=\"cd ~/testapp-webview-flask && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --bootstrap webview --requirements=python2,flask --private . && cp *.apk ~/output\"")\n    print("alias testbuild_service_only=\"cd ~/testapp-service_only-nogui && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --bootstrap service_only --requirements=pyjnius,python2 --private . && cp *.apk ~/output\"")\nelse:\n    print("echo \"cd ~/testapp-sdl2-keyboard && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --requirements=kivy,python3 --private .\"")\n    print("shopt -s expand_aliases")\n    print("alias testbuild=\"cd ~/testapp-sdl2-keyboard && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --requirements=kivy,python3 --private . && cp *.apk ~/output\"")\n    print("alias testbuild_webview=\"cd ~/testapp-webview-flask && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --bootstrap webview --requirements=python3,flask --private . && cp *.apk ~/output\"")\n    print("alias testbuild_service_only=\"cd ~/testapp-service_only-nogui && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --bootstrap service_only --requirements=pyjnius,python3 --private . && cp *.apk ~/output\"")\nwith open("/tmp/launchcmd.txt", "r") as f:\n    import shlex\n    args = shlex.split(f.read().strip())\n    print("CMD=()")\n    i = -1\n    for arg in args:\n        i += 1\n        print("CMD[" + str(i) + "]=" + shlex.quote(arg))\nprint("export ANDROIDAP='$ANDROIDAPI'" +\n    " ANDROIDNDKVER='$NDKVER'" +\n    " NDKAPI='$NDKAPI'" +\n    " GRADLE_OPTS=\"-Xms1724m -Xmx5048m -Dorg.gradle.jvmargs='"'"'-Xms1724m -Xmx5048m'"'"'\""+\n    " JAVA_OPTS=\"-Xms1724m -Xmx5048m\"" +\n    " ANDROIDSDK=/sdk-install/ ANDROIDNDK=\"'$NDKDIR'\"")' > /tmp/cmdline.py
 ---> Using cache
 ---> de55452f1c79
Step 31/31 : CMD ["bash", "-c", "python3 /tmp/cmdline.py > /tmp/launch.sh; source /tmp/launch.sh; exec \"${CMD[@]}\""]
 ---> Using cache
 ---> c42aa0f1d565
Successfully built c42aa0f1d565
Successfully tagged p4atestenv-p4a-py3-api28ndk21:latest

To build a kivy demo app, use this command:
cd ~/testapp-sdl2-keyboard && p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --requirements=kivy,python3 --private .
root@e4ee32fc258a:~# git clone https://github.com/guysoft/buildozer.git
Cloning into 'buildozer'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 2979 (delta 19), reused 27 (delta 15), pack-reused 2940
Receiving objects: 100% (2979/2979), 995.61 KiB | 2.10 MiB/s, done.
Resolving deltas: 100% (1843/1843), done.
root@e4ee32fc258a:~# cd buildozer && git checkout encoding
Branch 'encoding' set up to track remote branch 'encoding' from 'origin'.
Switched to a new branch 'encoding'
root@e4ee32fc258a:~/buildozer# python setup.py build && python setup.py install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/buildozer
copying buildozer/__main__.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/jsonstore.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/sitecustomize.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/target.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/__init__.py -> build/lib.linux-x86_64-2.7/buildozer
creating build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/__init__.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/ios.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/osx.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/android.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/android_new.py -> build/lib.linux-x86_64-2.7/buildozer/targets
creating build/lib.linux-x86_64-2.7/buildozer/libs
copying buildozer/libs/__init__.py -> build/lib.linux-x86_64-2.7/buildozer/libs
copying buildozer/libs/_structures.py -> build/lib.linux-x86_64-2.7/buildozer/libs
copying buildozer/libs/version.py -> build/lib.linux-x86_64-2.7/buildozer/libs
creating build/lib.linux-x86_64-2.7/buildozer/scripts
copying buildozer/scripts/__init__.py -> build/lib.linux-x86_64-2.7/buildozer/scripts
copying buildozer/scripts/client.py -> build/lib.linux-x86_64-2.7/buildozer/scripts
copying buildozer/scripts/remote.py -> build/lib.linux-x86_64-2.7/buildozer/scripts
running egg_info
creating buildozer.egg-info
writing requirements to buildozer.egg-info/requires.txt
writing buildozer.egg-info/PKG-INFO
writing top-level names to buildozer.egg-info/top_level.txt
writing dependency_links to buildozer.egg-info/dependency_links.txt
writing entry points to buildozer.egg-info/entry_points.txt
writing manifest file 'buildozer.egg-info/SOURCES.txt'
reading manifest file 'buildozer.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*COPYING'
writing manifest file 'buildozer.egg-info/SOURCES.txt'
copying buildozer/default.spec -> build/lib.linux-x86_64-2.7/buildozer
running install
running bdist_egg
running egg_info
writing requirements to buildozer.egg-info/requires.txt
writing buildozer.egg-info/PKG-INFO
writing top-level names to buildozer.egg-info/top_level.txt
writing dependency_links to buildozer.egg-info/dependency_links.txt
writing entry points to buildozer.egg-info/entry_points.txt
reading manifest file 'buildozer.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*COPYING'
writing manifest file 'buildozer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/buildozer
copying build/lib.linux-x86_64-2.7/buildozer/__main__.py -> build/bdist.linux-x86_64/egg/buildozer
copying build/lib.linux-x86_64-2.7/buildozer/jsonstore.py -> build/bdist.linux-x86_64/egg/buildozer
copying build/lib.linux-x86_64-2.7/buildozer/sitecustomize.py -> build/bdist.linux-x86_64/egg/buildozer
copying build/lib.linux-x86_64-2.7/buildozer/target.py -> build/bdist.linux-x86_64/egg/buildozer
copying build/lib.linux-x86_64-2.7/buildozer/__init__.py -> build/bdist.linux-x86_64/egg/buildozer
creating build/bdist.linux-x86_64/egg/buildozer/targets
copying build/lib.linux-x86_64-2.7/buildozer/targets/__init__.py -> build/bdist.linux-x86_64/egg/buildozer/targets
copying build/lib.linux-x86_64-2.7/buildozer/targets/ios.py -> build/bdist.linux-x86_64/egg/buildozer/targets
copying build/lib.linux-x86_64-2.7/buildozer/targets/osx.py -> build/bdist.linux-x86_64/egg/buildozer/targets
copying build/lib.linux-x86_64-2.7/buildozer/targets/android.py -> build/bdist.linux-x86_64/egg/buildozer/targets
copying build/lib.linux-x86_64-2.7/buildozer/targets/android_new.py -> build/bdist.linux-x86_64/egg/buildozer/targets
creating build/bdist.linux-x86_64/egg/buildozer/libs
copying build/lib.linux-x86_64-2.7/buildozer/libs/__init__.py -> build/bdist.linux-x86_64/egg/buildozer/libs
copying build/lib.linux-x86_64-2.7/buildozer/libs/_structures.py -> build/bdist.linux-x86_64/egg/buildozer/libs
copying build/lib.linux-x86_64-2.7/buildozer/libs/version.py -> build/bdist.linux-x86_64/egg/buildozer/libs
creating build/bdist.linux-x86_64/egg/buildozer/scripts
copying build/lib.linux-x86_64-2.7/buildozer/scripts/__init__.py -> build/bdist.linux-x86_64/egg/buildozer/scripts
copying build/lib.linux-x86_64-2.7/buildozer/scripts/client.py -> build/bdist.linux-x86_64/egg/buildozer/scripts
copying build/lib.linux-x86_64-2.7/buildozer/scripts/remote.py -> build/bdist.linux-x86_64/egg/buildozer/scripts
copying build/lib.linux-x86_64-2.7/buildozer/default.spec -> build/bdist.linux-x86_64/egg/buildozer
byte-compiling build/bdist.linux-x86_64/egg/buildozer/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/jsonstore.py to jsonstore.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/sitecustomize.py to sitecustomize.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/target.py to target.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/targets/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/targets/ios.py to ios.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/targets/osx.py to osx.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/targets/android.py to android.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/targets/android_new.py to android_new.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/libs/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/libs/_structures.py to _structures.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/libs/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/scripts/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/scripts/client.py to client.pyc
byte-compiling build/bdist.linux-x86_64/egg/buildozer/scripts/remote.py to remote.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying buildozer.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying buildozer.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying buildozer.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying buildozer.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying buildozer.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying buildozer.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
buildozer.__init__: module references __file__
buildozer.sitecustomize: module references __file__
buildozer.scripts.remote: module references __path__
creating dist
creating 'dist/buildozer-0.38.dev0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing buildozer-0.38.dev0-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/buildozer-0.38.dev0-py2.7.egg
Extracting buildozer-0.38.dev0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding buildozer 0.38.dev0 to easy-install.pth file
Installing buildozer script to /usr/local/bin
Installing buildozer-remote script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/buildozer-0.38.dev0-py2.7.egg
Processing dependencies for buildozer==0.38.dev0
Searching for sh
Reading https://pypi.python.org/simple/sh/
Downloading https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl#sha256=ae3258c5249493cebe73cb4e18253a41ed69262484bad36fdb3efcb8ad8870bb
Best match: sh 1.12.14
Processing sh-1.12.14-py2.py3-none-any.whl
Installing sh-1.12.14-py2.py3-none-any.whl to /usr/local/lib/python2.7/dist-packages
Adding sh 1.12.14 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg
Searching for pexpect
Reading https://pypi.python.org/simple/pexpect/
Downloading https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl#sha256=3fbd41d4caf27fa4a377bfd16fef87271099463e6fa73e92a52f92dfee5d425b
Best match: pexpect 4.6.0
Processing pexpect-4.6.0-py2.py3-none-any.whl
Installing pexpect-4.6.0-py2.py3-none-any.whl to /usr/local/lib/python2.7/dist-packages
writing requirements to /usr/local/lib/python2.7/dist-packages/pexpect-4.6.0-py2.7.egg/EGG-INFO/requires.txt
Adding pexpect 4.6.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pexpect-4.6.0-py2.7.egg
Searching for ptyprocess>=0.5
Reading https://pypi.python.org/simple/ptyprocess/
Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl#sha256=d7cc528d76e76342423ca640335bd3633420dc1366f258cb31d05e865ef5ca1f
Best match: ptyprocess 0.6.0
Processing ptyprocess-0.6.0-py2.py3-none-any.whl
Installing ptyprocess-0.6.0-py2.py3-none-any.whl to /usr/local/lib/python2.7/dist-packages
Adding ptyprocess 0.6.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/ptyprocess-0.6.0-py2.7.egg
Searching for virtualenv==15.1.0
Best match: virtualenv 15.1.0
Adding virtualenv 15.1.0 to easy-install.pth file
Installing virtualenv script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for buildozer==0.38.dev0
root@e4ee32fc258a:~/buildozer# buildozer --init  
Buildozer is running as root!
This is not recommended, and may lead to problems later.
Are you sure you want to continue [y/n]? y
# Ensure build layout
No buildozer.spec found in the current directory. Abandon.
root@e4ee32fc258a:~/buildozer# buildozer --version
Buildozer 0.38.dev0
root@e4ee32fc258a:~/buildozer# 
```

**Comment by guysoft** [comment]
This issue can be closed.

Also @homdx can see you are using p4aspaces you might want to see what I've been working on since yesterday:
https://github.com/guysoft/p4a-docker

**Comment by AndreMiras** [comment]
Closed via https://github.com/kivy/buildozer/pull/789
