### ISSUE TITLE
Openssl compilation fails, '__atomic' undefined

### ISSUE THREAD

**Issue by MDelaney7700** [kivy/buildozer#800]
### Versions

* Python: 3.7
* OS: Ubuntu 18.04 Desktop
* Kivy: 1.10.1
* Cython: 0.29

### Description

I'm trying to compile openssl for my kivy project, but I keep running into an error during compilation where a number of "__atomic" references are listed as undefined. The same error occurs when using the python2.7 recipe and 3.7 recipe.

### buildozer.spec
Command:
```sh
buildozer android debug
...
STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 1039, in <module>
    main()
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 1033, in main
    ToolchainCL()
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 553, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 150, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 191, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/build.py", line 634, in build_recipes
    recipe.build_arch(arch)
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/python.py", line 232, in build_arch
    _env=env)
  File "/home/mattdelaney/Documents/dssios/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/logger.py", line 178, in shprint
    for line in output:
  File "/home/mattdelaney/.local/lib/python3.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/mattdelaney/.local/lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/mattdelaney/.local/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_77:

  RAN: /home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/python2-libffi-openssl/armeabi-v7a__ndk_target_24/python2/configure --host=arm-linux-androideabi --build=x86_64-pc-linux-gnu --enable-shared --disable-ipv6 --disable-toolbox-glue --disable-framework ac_cv_file__dev_ptmx=yes ac_cv_file__dev_ptc=no --without-ensurepip ac_cv_little_endian_double=yes ac_cv_header_langinfo_h=no --prefix=/usr/local --exec-prefix=/usr/local

  STDOUT:
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for python2.7... python2.7
checking for python interpreter for cross build... python2.7
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux2
checking EXTRAPLATDIR...
checking for --without-gcc... no
checking for --with-icc... no
checking for arm-linux-androideabi-gcc... /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-none-linux-androideabi -gcc-toolchain /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
checking whether the C compiler works... no
configure: error: in `/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/python2-libffi-openssl/armeabi-v7a__ndk_target_24/python2/android-build':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Spec file:
```
[app]
title = Dss Time
package.name = dssapp
package.domain = com.delaneyware
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = openssl,python3,kivy,libffi,android,requests,certifi,python-dateutil
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.10.1
fullscreen = 0
android.api = 26
android.minapi = 24
android.ndk = 15c
p4a.branch = master
android.arch = armeabi-v7a

[buildozer]
log_level = 2
warn_on_root = 1
```

### Logs
Snippet of config.log
```
configure:3889: $? = 0
configure:3878: /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-none-linux-androideabi -gcc-toolchain /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3889: $? = 1
configure:3878: /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-none-linux-androideabi -gcc-toolchain /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -qversion >&5
clang: error: unknown argument '-qversion', did you mean '--version'?
clang: error: no input files
configure:3889: $? = 1
configure:3909: checking whether the C compiler works
configure:3931: /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-none-linux-androideabi -gcc-toolchain /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64  -fPIC --sysroot=/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/sysroot -D__ANDROID_API__=24 -isystem /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -I/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/sysroot/usr/include  -fPIC --sysroot=/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/sysroot -D__ANDROID_API__=24 -isystem /home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -I/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/sysroot/usr/include -I/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_24/libffi/arm-unknown-linux-androideabi/include -I/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/include -I/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/include/internal -I/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/include/openssl  --sysroot=/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/platforms/android-24/arch-arm -L/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/platforms/android-24/arch-arm/usr/lib -L/home/mattdelaney/.buildozer/android/platform/android-ndk-r15c/platforms/android-24/arch-arm/usr/lib -L/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_24/libffi/arm-unknown-linux-androideabi/.libs -L/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1 conftest.c  -lffi -lcrypto1.1 -lssl1.1 >&5
/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/libcrypto1.1.so: error: undefined reference to '__atomic_fetch_add_4'
/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/libcrypto1.1.so: error: undefined reference to '__atomic_fetch_sub_4'
/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/libcrypto1.1.so: error: undefined reference to '__atomic_store'
/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/libcrypto1.1.so: error: undefined reference to '__atomic_load'
/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_24/openssl1.1/libcrypto1.1.so: error: undefined reference to '__atomic_is_lock_free'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3935: $? = 1
configure:3973: result: no
configure: failed program was:
| /* confdefs.h */
| #define _GNU_SOURCE 1
| #define _NETBSD_SOURCE 1
| #define __BSD_VISIBLE 1
| #define _DARWIN_C_SOURCE 1
| #define _PYTHONFRAMEWORK ""
| #define _XOPEN_SOURCE 700
| #define _XOPEN_SOURCE_EXTENDED 1
| #define _POSIX_C_SOURCE 200809L
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3978: error: in `/home/mattdelaney/Documents/dssios/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl/armeabi-v7a__ndk_target_24/python3/android-build':
configure:3980: error: C compiler cannot create executables
```

**Comment by MDelaney7700** [comment]
I was able to fix this issue by changing my NDK version from 15c to 17b, and deleting the .buildozer directory in my project.

**Comment by inclement** [comment]
Thanks @MDelaney7700 , it looks like we'll want to recommend NDK 17 as the minimum supported one from now one.
