### ISSUE TITLE
"Command failed" when running "buildozer android debug deploy run"

### ISSUE THREAD

**Issue by rogeriodec** [kivy/buildozer#829]
### Versions

* Python: 3.6
* OS: Ubuntu 18.04.2 LTS
* Buildozer: last

### Description

I'm trying to run the "**buildozer android debug deploy run**" command completely (for the first time) for several days and always stuck on some difficulty.

Just for conference, I've already gone through the following commands:

```
sudo apt update
sudo apt install python3-pip

sudo pip3 install buildozer

buildozer init

sudo apt-get install zlib1g-dev

sudo apt-get update
sudo apt-get install git-core
sudo apt-get install cython

sudo apt-get update
sudo apt-get install openjdk-8-jdk

buildozer android debug deploy run
```

Now I'm getting this error:

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\''
# Cwd None
# Apache ANT found at /home/rogerio/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/rogerio/.buildozer/android/platform/android-sdk
# Android NDK found at /home/rogerio/.buildozer/android/platform/android-ndk-r17c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/rogerio/Desktop/Python/.buildozer/android/platform/build" --ndk-api=21'
# Cwd /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 27
[INFO]:    Available Android APIs are (27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /home/rogerio/.buildozer/android/platform/android-ndk-r17c
[INFO]:    Found NDK revision 17.2.4988734
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[WARNING]: Missing executable: pkg-config is not installed
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'six', 'pyjnius', 'android', 'kivy']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name myapp and requirements (python3, kivy)
[INFO]:    Dist contains the following requirements as recipes: ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'six', 'pyjnius', 'android', 'kivy']
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Recipe build order is ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'six', 'pyjnius', 'android', 'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 62 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/hostpython3
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    hostpython3 download already cached, skipping                       
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading libffi
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 57 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/libffi
[INFO]:    -> running basename https://github.com/lib...(and 32 more)
[INFO]:    libffi download already cached, skipping                            
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 58 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> running basename https://www.openssl.or...(and 29 more)
[INFO]:    openssl download already cached, skipping                           
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 61 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping                        
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 61 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping                        
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 59 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping                          
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 58 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/sqlite3
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    sqlite3 download already cached, skipping                           
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading python3
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 58 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/python3
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    python3 download already cached, skipping                           
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 55 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    sdl2 download already cached, skipping                              
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 54 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping                               
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 58 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    pyjnius download already cached, skipping                           
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/rogerio/Desktop...(and 55 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 26 more)
[INFO]:    kivy download already cached, skipping                              
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/hostpython3/desktop
[INFO]:    hostpython3 is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking libffi for armeabi-v7a
[INFO]:    -> running basename https://github.com/lib...(and 32 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21
[INFO]:    libffi is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.or...(and 29 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_21
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/sqlite3/armeabi-v7a__ndk_target_21
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking python3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21
[INFO]:    python3 is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/six-python3/armeabi-v7a__ndk_target_21
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    -> running rm -rf /home/rogerio/Desktop/P...(and 114 more)
[INFO]:    -> running cp -a /home/rogerio/Desktop/Py...(and 226 more)
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 26 more)
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/kivy-python3-sdl2/armeabi-v7a__ndk_target_21
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding libffi for armeabi-v7a
[INFO]:    libffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for libffi[armeabi-v7a]
[INFO]:    libffi already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sqlite3 for armeabi-v7a
[INFO]:    sqlite3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
[INFO]:    python3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python3[armeabi-v7a]
[INFO]:    python3 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/android-python3-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    <- directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    Skipping hostpython3 (3.7.1) build, as it has already been completed
[INFO]:    Building libffi for armeabi-v7a
[INFO]:    -> directory context /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi
[INFO]:    -> running autogen.sh
Exception in thread background thread for pid 17436:                           
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_127: 

  RAN: /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh

  STDOUT:
/home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh: 2: exec: autoreconf: not found


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1073, in <module>
    main()
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1067, in main
    ToolchainCL()
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 576, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 151, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 200, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 562, in build_recipes
    recipe.build_arch(arch)
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/__init__.py", line 33, in build_arch
    shprint(sh.Command('./autogen.sh'), _env=env)
  File "/home/rogerio/Desktop/Python/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 178, in shprint
    for line in output:
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/rogerio/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_127: 

  RAN: /home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh

  STDOUT:
/home/rogerio/Desktop/Python/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/autogen.sh: 2: exec: autoreconf: not found


  STDERR:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/rogerio/Desktop/Python/.buildozer/android/platform/build" --ndk-api=21
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

What is wrong?

**Comment by AndreMiras** [comment]
You're missing the `autoconf` system dependency and maybe some other deps, see https://github.com/kivy/python-for-android/blob/3808066/pythonforandroid/recipes/libffi/__init__.py#L14 and also check for existing similar "bug" in p4a git.
For further support please try on IRC, Discord or Matrix

**Comment by SammyMayn** [comment]
Can you tell me how to implement the 'autoconf' dependency ?

**Comment by Electrojones** [comment]
You can use `sudo apt-get install autoconf` to do this, but I had the same error and it did not solve it...

**Comment by jonathanvanschenck** [comment]
> You can use `sudo apt-get install autoconf` to do this, but I had the same error and it did not solve it...

I also had the same issue, though I had installed autoconf but still got the same error. It seems there is additional package that is missing: libltdl-dev (which can be installed via apt)

**Comment by hvitis** [comment]
Had the same problem. @jonathanvanschenck you're a genius

**Comment by srajith** [comment]
> > You can use `sudo apt-get install autoconf` to do this, but I had the same error and it did not solve it...
> 
> I also had the same issue, though I had installed autoconf but still got the same error. It seems there is additional package that is missing: libltdl-dev (which can be installed via apt)

hi i have same error i does not work @jonathanvanschenck

**Comment by thunder-hammer** [comment]
@srajith I also had to 'sudo apt install automake'. That at least moved me on to the next error.

**Comment by swarooppuranik** [comment]
@srajith I ran sudo apt-get install autoconf and sudo apt-get install libltdl-dev . Looks like worked for me.

**Comment by cat-commits** [comment]
there is a bunch of dependancies see 
https://buildozer.readthedocs.io/en/latest/installation.html

sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev

**Comment by purisahib** [comment]
"sudo apt-get install autoconf" this command not work in my program but problem is same also any one please help.

**Comment by purisahib** [comment]
configure:7745: error: possibly undefined macro: AC_PROG_LD
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by robinNcode** [comment]
The following steps were worked for me. Hopefully will work for you guys.
a) !pip install buildozer
b) !pip install cython==0.29.19
c) !sudo apt-get install -y \
    python3-pip \
    build-essential \
    git \
    python3 \
    python3-dev \
    ffmpeg \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev
d) !sudo apt-get install -y \
    libgstreamer1.0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good

e) !sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6

f) !sudo apt-get install autoconf
g) !sudo apt-get install libffi-dev
h) !sudo apt-get install libtool

i) !buildozer init

j) !buildozer -v android debug

**Comment by iftekharalammithu** [comment]
Update Commands 07-13-23


!pip install buildozer

!pip install -U cython

!sudo apt-get install -y \
    python3-pip \
    build-essential \
    git \
    python3 \
    python3-dev \
    ffmpeg \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev

!sudo apt-get install -y \
    libgstreamer1.0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good

!sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6

!sudo apt-get install libffi-dev
!sudo apt-get install libtool
!sudo apt-get install autoconf

!buildozer init

!buildozer -v android debug


** Thank me leter😎

**Comment by hugocarlossousa** [comment]
I'm having the same error in 2023, however I'm using google colab.
I've also tried with WSL + buildozer and it won't.
It runs all the debug plus when saving the error.

Could anyone help me?

**Comment by Empya** [comment]
> Update Commands 07-13-23
> 
> !pip install buildozer
> 
> !pip install -U cython
> 
> !sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
> 
> !sudo apt-get install -y libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
> 
> !sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6
> 
> !sudo apt-get install libffi-dev !sudo apt-get install libtool !sudo apt-get install autoconf
> 
> !buildozer init
> 
> !buildozer -v android debug
> 
> ** Thank me leter😎

**Comment by redrickh** [comment]
https://colab.research.google.com/drive/1K1P6S1-jeGJNrUXmDcF_m3RrtrzHqCrI?usp=sharing

this works! :)

**Comment by theunknownkid** [comment]
i managed to run @redrickh 's colab research and produce an output, but the app keeps crashing our mobile phone

**Comment by Empya1** [comment]
@theunknownkid if youve already built your android apk these are some reasons why it might crash:

1. it requires a specific **android permissions** to work e.g storage, internet ..

2. the **path to your app files** may be incorrect (the file path you used to access a file in your source code may not work in an apk)

3. **some neccessary modules are not included in your buildozer spec file**

4. when using sqlite3 database, your app is likely to crash if you **dont "" close the database connection"" after each database operation.**

i hope this helps, this worked for me
