### ISSUE TITLE
Errors while running buildozer android debug deploy

### ISSUE THREAD

**Issue by blvckallpv** [kivy/buildozer#832]
### Versions

* Python: 3
* OS: Kali Linux
* Buildozer: 0.40.dev0

### Description

I am new to kivy and i am trying to build my first apk, which failed, bringing up so many errors

### buildozer.spec
Command:
```sh
buildozer android debug deploy
```

Spec file:
```
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = testapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.10.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
android.api = 27

# (int) Minimum API your APK will support.
android.minapi = 21

# (int) Android SDK version to use
android.sdk = 20

# (str) Android NDK version to use
android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
android.add_libs_armeabi = libs/android/*.so
android.add_libs_armeabi_v7a = libs/android-v7/*.so
android.add_libs_x86 = libs/android-x86/*.so
android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
 p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 0

# (str) Path to build artifact storage, absolute or relative to spec file
build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

### Logs

```# Check configuration tokens
# WARNING: Config token app android.sdk is deprecated and ignored, but you set value 20
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
# ENVIRONMENT:
#     USER = 'root'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     XDG_CURRENT_DESKTOP = 'GNOME'
#     XDG_SESSION_TYPE = 'x11'
#     LOGNAME = 'root'
#     XDG_SEAT = 'seat0'
#     PATH = '/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#     XDG_VTNR = '2'
#     HOME = '/root'
#     DISPLAY = ':1'
#     SSH_AGENT_PID = '935'
#     XDG_SESSION_DESKTOP = 'gnome'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     XAUTHORITY = '/run/user/0/gdm/Xauthority'
#     SESSION_MANAGER = 'local/whiteknight:@/tmp/.ICE-unix/883,unix/whiteknight:/tmp/.ICE-unix/883'
#     SHLVL = '1'
#     QT_ACCESSIBILITY = '1'
#     WINDOWPATH = '2'
#     GPG_AGENT_INFO = '/run/user/0/gnupg/S.gpg-agent:0:1'
#     XDG_SESSION_CLASS = 'user'
#     USERNAME = 'root'
#     LANG = 'en_US.UTF-8'
#     XDG_RUNTIME_DIR = '/run/user/0'
#     SSH_AUTH_SOCK = '/run/user/0/keyring/ssh'
#     VTE_VERSION = '5402'
#     GDMSESSION = 'gnome'
#     XDG_SESSION_ID = '2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/0/bus'
#     _ = '/usr/local/bin/buildozer'
#     GNOME_TERMINAL_SERVICE = ':1.68'
#     DESKTOP_SESSION = 'gnome'
#     GTK_MODULES = 'gail:atk-bridge'
#     GDM_LANG = 'en_US.UTF-8'
#     XDG_DATA_DIRS = '/usr/share/gnome:/usr/local/share/:/usr/share/'
#     PWD = '/root/pyfiles/kivy'
#     COLORTERM = 'truecolor'
#     XDG_MENU_PREFIX = 'gnome-'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/974c9eac_071d_4ab7_a300_b82fcea1763e'
Debian 'dpkg' package management program version 1.19.2 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /root/miniconda3/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
# Install platform
# Run '/usr/bin/python2.7 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\''
# Cwd None
# ENVIRONMENT:
#     USER = 'root'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     XDG_CURRENT_DESKTOP = 'GNOME'
#     XDG_SESSION_TYPE = 'x11'
#     LOGNAME = 'root'
#     XDG_SEAT = 'seat0'
#     PATH = '/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#     XDG_VTNR = '2'
#     HOME = '/root'
#     DISPLAY = ':1'
#     SSH_AGENT_PID = '935'
#     XDG_SESSION_DESKTOP = 'gnome'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     XAUTHORITY = '/run/user/0/gdm/Xauthority'
#     SESSION_MANAGER = 'local/whiteknight:@/tmp/.ICE-unix/883,unix/whiteknight:/tmp/.ICE-unix/883'
#     SHLVL = '1'
#     QT_ACCESSIBILITY = '1'
#     WINDOWPATH = '2'
#     GPG_AGENT_INFO = '/run/user/0/gnupg/S.gpg-agent:0:1'
#     XDG_SESSION_CLASS = 'user'
#     USERNAME = 'root'
#     LANG = 'en_US.UTF-8'
#     XDG_RUNTIME_DIR = '/run/user/0'
#     SSH_AUTH_SOCK = '/run/user/0/keyring/ssh'
#     VTE_VERSION = '5402'
#     GDMSESSION = 'gnome'
#     XDG_SESSION_ID = '2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/0/bus'
#     _ = '/usr/local/bin/buildozer'
#     GNOME_TERMINAL_SERVICE = ':1.68'
#     DESKTOP_SESSION = 'gnome'
#     GTK_MODULES = 'gail:atk-bridge'
#     GDM_LANG = 'en_US.UTF-8'
#     XDG_DATA_DIRS = '/usr/share/gnome:/usr/local/share/:/usr/share/'
#     PWD = '/root/pyfiles/kivy'
#     COLORTERM = 'truecolor'
#     XDG_MENU_PREFIX = 'gnome-'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/974c9eac_071d_4ab7_a300_b82fcea1763e'
# Apache ANT found at /root/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /root/.buildozer/android/platform/android-sdk
# Android NDK found at /root/.buildozer/android/platform/android-ndk-r17c
# Installing/updating SDK platform tools if necessary
# Run '/root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools'
# Cwd /root/.buildozer/android/platform/android-sdk
# ENVIRONMENT:
#     USER = 'root'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     XDG_CURRENT_DESKTOP = 'GNOME'
#     XDG_SESSION_TYPE = 'x11'
#     LOGNAME = 'root'
#     XDG_SEAT = 'seat0'
#     PATH = '/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#     XDG_VTNR = '2'
#     HOME = '/root'
#     DISPLAY = ':1'
#     SSH_AGENT_PID = '935'
#     XDG_SESSION_DESKTOP = 'gnome'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     XAUTHORITY = '/run/user/0/gdm/Xauthority'
#     SESSION_MANAGER = 'local/whiteknight:@/tmp/.ICE-unix/883,unix/whiteknight:/tmp/.ICE-unix/883'
#     SHLVL = '1'
#     QT_ACCESSIBILITY = '1'
#     WINDOWPATH = '2'
#     GPG_AGENT_INFO = '/run/user/0/gnupg/S.gpg-agent:0:1'
#     XDG_SESSION_CLASS = 'user'
#     USERNAME = 'root'
#     LANG = 'en_US.UTF-8'
#     XDG_RUNTIME_DIR = '/run/user/0'
#     SSH_AUTH_SOCK = '/run/user/0/keyring/ssh'
#     VTE_VERSION = '5402'
#     GDMSESSION = 'gnome'
#     XDG_SESSION_ID = '2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/0/bus'
#     _ = '/usr/local/bin/buildozer'
#     GNOME_TERMINAL_SERVICE = ':1.68'
#     DESKTOP_SESSION = 'gnome'
#     GTK_MODULES = 'gail:atk-bridge'
#     GDM_LANG = 'en_US.UTF-8'
#     XDG_DATA_DIRS = '/usr/share/gnome:/usr/local/share/:/usr/share/'
#     PWD = '/root/pyfiles/kivy'
#     COLORTERM = 'truecolor'
#     XDG_MENU_PREFIX = 'gnome-'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/974c9eac_071d_4ab7_a300_b82fcea1763e'
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
# Command failed: /root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools
# ENVIRONMENT:
#     USER = 'root'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     XDG_CURRENT_DESKTOP = 'GNOME'
#     XDG_SESSION_TYPE = 'x11'
#     LOGNAME = 'root'
#     XDG_SEAT = 'seat0'
#     PATH = '/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#     XDG_VTNR = '2'
#     HOME = '/root'
#     DISPLAY = ':1'
#     SSH_AGENT_PID = '935'
#     XDG_SESSION_DESKTOP = 'gnome'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     XAUTHORITY = '/run/user/0/gdm/Xauthority'
#     SESSION_MANAGER = 'local/whiteknight:@/tmp/.ICE-unix/883,unix/whiteknight:/tmp/.ICE-unix/883'
#     SHLVL = '1'
#     QT_ACCESSIBILITY = '1'
#     WINDOWPATH = '2'
#     GPG_AGENT_INFO = '/run/user/0/gnupg/S.gpg-agent:0:1'
#     XDG_SESSION_CLASS = 'user'
#     USERNAME = 'root'
#     LANG = 'en_US.UTF-8'
#     XDG_RUNTIME_DIR = '/run/user/0'
#     SSH_AUTH_SOCK = '/run/user/0/keyring/ssh'
#     VTE_VERSION = '5402'
#     GDMSESSION = 'gnome'
#     XDG_SESSION_ID = '2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/0/bus'
#     _ = '/usr/local/bin/buildozer'
#     GNOME_TERMINAL_SERVICE = ':1.68'
#     DESKTOP_SESSION = 'gnome'
#     GTK_MODULES = 'gail:atk-bridge'
#     GDM_LANG = 'en_US.UTF-8'
#     XDG_DATA_DIRS = '/usr/share/gnome:/usr/local/share/:/usr/share/'
#     PWD = '/root/pyfiles/kivy'
#     COLORTERM = 'truecolor'
#     XDG_MENU_PREFIX = 'gnome-'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/974c9eac_071d_4ab7_a300_b82fcea1763e'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
[log.txt](https://github.com/kivy/buildozer/files/2896276/log.txt)

```

**Comment by AndreMiras** [comment]
Relevant part of the error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
# Command failed: /root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools
```
You probably have a too recent version of java, see https://stackoverflow.com/q/46402772/185510.
So try uninstalling what you have (java 9?) and installing `openjdk-8-jdk`, see here for Ubuntu:
https://github.com/kivy/buildozer/blob/0.39/docs/source/installation.rst#android-on-ubuntu-1804-64bit

Also I don't recommend installing/running buildozer as root user.

**Comment by blvckallpv** [comment]
I have done it, but i got another error in the process
# Check that aidl can be executed
# Search for Aidl
# Aidl not found, please install it.

I Checked and the Aidl can be executed, I'll need some help

**Comment by AndreMiras** [comment]
Glad you got that one working.
For your other problem please take a look at the issue below:
https://github.com/kivy/buildozer/issues/824
