### ISSUE TITLE
Applying patches for libffi[armeabi-v7a]

### ISSUE THREAD

**Issue by arcarus** [kivy/buildozer#840]
### Versions

* Python: 3.7.2
* OS: Opensuse Tumbleweed
* Buildozer: 0.39

### Description

Building an apk failes with an error at Applying patches for libffi[armeabi-v7a]

### buildozer.spec
Command: 
```sh
buildozer android debug deploy
```

Spec file:
```
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.10.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```
### Logs

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
/bin/sh: dpkg: command not found
# Search for Git (git)
#  -> found at /usr/lib/git/git
# Search for Cython (cython)
#  -> found at /usr/bin/cython-3.7
# Search for Java compiler (javac)
#  -> found at /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/bin/keytool
# Install platform
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\'
 \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="
nt"\''                                                                         
# Cwd None
# Apache ANT found at /home/arc/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/arc/.buildozer/android/platform/android-sdk
# Android NDK found at /home/arc/.buildozer/android/platform/android-ndk-r17c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp -
-bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --col
or=always --storage-dir="/home/arc/documents/sclprojects/kivy/.buildozer/android
/platform/build" --ndk-api=21'                                                 
# Cwd /home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-fo
r-android                                                                      
/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-for-andr
oid/pythonforandroid/toolchain.py:83: DeprecationWarning: the imp module is depr
ecated in favour of importlib; see the module's documentation for alternative us
es                                                                             
  import imp
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 27
[INFO]:    Available Android APIs are (27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /home/arc/.buildozer/android/platform/a
ndroid-ndk-r17c                                                                
[INFO]:    Found NDK revision 17.2.4988734
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argume
nt                                                                             
[INFO]:    Found virtualenv at /home/arc/.local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3', 'libffi', 'openssl',
 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'six', 'p
yjnius', 'android', 'kivy']                                                    
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name myapp and requirements (python3, kivy)
[INFO]:    Dist contains the following requirements as recipes: ['hostpython3', 
'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3
', 'sdl2', 'six', 'pyjnius', 'android', 'kivy']                                
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/bootstrap_builds/sdl2-python3                     
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Recipe build order is ['hostpython3', 'libffi', 'openssl', 'sdl2_imag
e', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'six', 'pyjnius', 'a
ndroid', 'kivy']                                                               
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 70 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/hostpython3                                    
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    hostpython3 download already cached, skipping                       
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading libffi
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 65 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/libffi                                         
[INFO]:    -> running basename https://github.com/lib...(and 32 more)
[INFO]:    libffi download already cached, skipping                            
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 66 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/openssl                                        
[INFO]:    -> running basename https://www.openssl.or...(and 29 more)
[INFO]:    openssl download already cached, skipping                           
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 69 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/sdl2_image                                     
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping                        
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 69 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/sdl2_mixer                                     
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping                        
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 67 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/sdl2_ttf                                       
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping                          
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 66 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/sqlite3                                        
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    sqlite3 download already cached, skipping                           
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading python3
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 66 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/python3                                        
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    python3 download already cached, skipping                           
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 63 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/sdl2                                           
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    sdl2 download already cached, skipping                              
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 62 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/six                                            
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping                               
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 66 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/pyjnius                                        
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    pyjnius download already cached, skipping                           
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/arc/documents/s...(and 63 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/packages/kivy                                           
[INFO]:    -> running basename https://github.com/kiv...(and 26 more)
[INFO]:    kivy download already cached, skipping                              
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/hostpython3/desktop                  
[INFO]:    hostpython3 is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking libffi for armeabi-v7a
[INFO]:    -> running basename https://github.com/lib...(and 32 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21    
[INFO]:    libffi is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.or...(and 29 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_21   
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/bootstrap_builds/sdl2-python3/jni                 
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/bootstrap_builds/sdl2-python3/jni                 
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/bootstrap_builds/sdl2-python3/jni                 
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/sqlite3/armeabi-v7a__ndk_target_21   
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking python3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org...(and 34 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi
-v7a__ndk_target_21                                                            
[INFO]:    python3 is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/bootstrap_builds/sdl2-python3/jni                 
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/six-python3/armeabi-v7a__ndk_target_21
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_
target_21                                                                      
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    -> running rm -rf /home/arc/documents/scl...(and 122 more)
[INFO]:    -> running cp -a /home/arc/documents/sclp...(and 242 more)
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 26 more)
[INFO]:    -> directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/build/build/other_builds/kivy-python3-sdl2/armeabi-v7a__ndk_tar
get_21                                                                         
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/arc/documents/sclprojects/kivy/.buildozer/
android/platform/python-for-android                                            
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding libffi for armeabi-v7a
[INFO]:    libffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for libffi[armeabi-v7a]
[INFO]:    Applying patch remove-version-info.patch
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/toolchain.py", line 1081, in <module>             
    main()
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/toolchain.py", line 1075, in main                 
    ToolchainCL()
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/toolchain.py", line 577, in __init__              
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/toolchain.py", line 151, in wrapper_func          
    build_dist_from_args(ctx, dist, args)
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/toolchain.py", line 200, in build_dist_from_args  
    build_recipes(build_order, python_modules, ctx)
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/build.py", line 555, in build_recipes             
    recipe.apply_patches(arch)
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/recipe.py", line 471, in apply_patches            
    arch.arch, build_dir=build_dir)
  File "/home/arc/documents/sclprojects/kivy/.buildozer/android/platform/python-
for-android/pythonforandroid/recipe.py", line 193, in apply_patch              
    shprint(sh.patch, "-t", "-d", build_dir, "-p1",
  File "/home/arc/.local/lib/python3.7/site-packages/sh.py", line 3349, in __get
attr__                                                                         
    return self.__env[name]
  File "/home/arc/.local/lib/python3.7/site-packages/sh.py", line 3226, in __get
item__                                                                         
    raise CommandNotFound(k)
sh.CommandNotFound: patch
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_n
ame=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy
-libs --color=always --storage-dir="/home/arc/documents/sclprojects/kivy/.buildo
zer/android/platform/build" --ndk-api=21  
```

**Comment by AndreMiras** [comment]
```
sh.CommandNotFound: patch
```
I won't really call that a bug, but rather a missing system dependency, so try a `yum install patch`.
If you really think it is a bug, then feel free to reopen
