### ISSUE TITLE
Unable to init project w/ docker image

### ISSUE THREAD

**Issue by JohnStrunk** [kivy/buildozer#863]
### Versions

* Python:
* OS: Fedora 28, kernel 4.20.14-100.fc28.x86_64
* Buildozer: Buildozer 0.40.dev0

### Description

I am trying to use buildozer via the docker image from https://hub.docker.com/r/kivy/buildozer. Based on the comments in the Dockerfile, it appears the container should be run as:

```
$ docker run --rm --volume "$HOME/.buildozer":/home/user/.buildozer --volume "$PWD":/home/user/hostcwd  kivy/buildozer --version
Buildozer 0.40.dev0
```

... so far, so good. I can get the version.

Next, I tried to init my project:

```
$ docker run --rm --volume "$HOME/.buildozer":/home/user/.buildozer --volume "$PWD":/home/user/hostcwd  kivy/buildozer init
Traceback (most recent call last):
  File "/home/user/.local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.40.dev0', 'console_scripts', 'buildozer')()
  File "/home/user/.local/lib/python3.6/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/user/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 1052, in run_command
    getattr(self, cmd)(*args)
  File "/home/user/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 1096, in cmd_init
    copyfile(join(dirname(__file__), 'default.spec'), 'buildozer.spec')
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'buildozer.spec'
```

The container is running with the arbitrary UID created in the base container, and that UID does not have write permission to my project directory.

Ideally, I should be able to run the container w/ my UID (but that doesn't work either):

```
$ docker run --rm --volume "$HOME/.buildozer":/home/user/.buildozer --volume "$PWD":/home/user/hostcwd --user `id -u` kivy/buildozer init
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"buildozer\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled
```

How do I use the container to init a project?

**Comment by AndreMiras** [comment]
Thanks for the bug report, I wasn't aware of that one.
I just gave it another try, see my debugging session below:
```
andre@localhost:~$ mkdir /tmp/buildozer
andre@localhost:~$ cd /tmp/buildozer/
andre@localhost:/tmp/buildozer$ ls -la
total 64
drwxr-xr-x  2 andre andre  4096 Mar 20 21:54 .
drwxrwxrwt 81 root  root  57344 Mar 20 21:54 ..
andre@localhost:/tmp/buildozer$ docker run --rm --volume "$HOME/.buildozer":/home/user/.buildozer --volume "$PWD":/home/user/hostcwd kivy/buildozer init
File buildozer.spec created, ready to customize!
andre@localhost:/tmp/buildozer$ ls -la
total 76
drwxr-xr-x  2 andre andre  4096 Mar 20 21:55 .
drwxrwxrwt 81 root  root  57344 Mar 20 21:54 ..
-rw-r--r--  1 andre andre  8922 Mar 20 21:55 buildozer.spec
andre@localhost:/tmp/buildozer$ id
uid=1000(andre) gid=1000(andre) groups=1000(andre),27(sudo),46(plugdev),126(docker)
andre@localhost:/tmp/buildozer$
```

**Comment by JohnStrunk** [comment]
Yep, it works if the uids happen to match. Thanks for taking a look. :+1: 

My environment:

```
# id -u in the container
$ docker run --rm --volume "$HOME/.buildozer":/home/user/.buildozer --volume "$PWD":/home/user/hostcwd  --entrypoint id kivy/buildozer -u
1000

# id -u outside
$ id -u
101587
```
