### ISSUE TITLE
TypeError: 'comment' is an invalid keyword argument for this function 

### ISSUE THREAD

**Issue by reetishrestha** [kivy/buildozer#868]
### Versions

* Python:2.7
* OS:10.13.6

Output Error:
```
Traceback (most recent call last):
  File "app.py", line 47, in <module>
    updated_parsed = entry.updated_parsed,
  File "/Users/ontreat/Documents/Reeti/Python/yankk/myvenv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ontreat/Documents/Reeti/Python/yankk/myvenv/lib/python3.6/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/Users/ontreat/Documents/Reeti/Python/yankk/myvenv/lib/python3.6/site-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'comment' is an invalid keyword argument for this function
```

**Comment by AndreMiras** [comment]
We're missing a lot of info here, it's hard to say. What command did you use. What buildozer version are you running?
