### ISSUE TITLE
packaging problem

### ISSUE THREAD

**Issue by chrispinematanda1500** [kivy/buildozer#873]
### Versions

* Python:
* OS:
* Buildozer:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec
Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by chrispinematanda1500** [comment]
python 3.6.7
linux ,ubuntu 18.04

i'm new at programming and i recently changed my os to linux so that i can be able to package my kivy app for android using the buildozer method.but even after following the instruction which are as follows
1.buildozer init
2.changed the version in the buildozer.spec file
3.try to create the apk file with the the with this code
buildozer android debug
but this is my output
chrispinematand@chrispinematand-HP-655-Notebook-PC:~$ buildozer android debug
Check configuration tokens
Ensure build layout
Check configuration tokens
Read available permissions from api-versions.xml
Preparing build
Check requirements for android
Run 'dpkg --version'
Cwd None

Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
Search for Git (git)
-> found at /usr/bin/git
Search for Cython (cython)
-> found at /usr/local/bin/cython
Search for Java compiler (javac)
-> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
Search for Java keytool (keytool)
-> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
Install platform
Run '/usr/bin/python3 -m pip install -q --user 'appdirs' 'colorama>=0.3.3' 'jinja2' 'six' 'enum34; python_version<"3.4"' 'sh>=1.10; sys_platform!="nt"''
Cwd None
Apache ANT found at /home/chrispinematand/.buildozer/android/platform/apache-ant-1.9.4
Android SDK found at /home/chrispinematand/.buildozer/android/platform/android-sdk
Android NDK is missing, downloading
Downloading https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip

Traceback (most recent call last):
File "/usr/local/bin/buildozer", line 11, in
load_entry_point('buildozer==0.40.dev0', 'console_scripts', 'buildozer')()
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/scripts/client.py", line 13, in main
Buildozer().run_command(sys.argv[1:])
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/init.py", line 1062, in run_command
self.target.run_commands(args)
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/target.py", line 92, in run_commands
func(args)
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/target.py", line 102, in cmd_debug
self.buildozer.prepare_for_build()
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/init.py", line 186, in prepare_for_build
self.target.install_platform()
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/targets/android.py", line 597, in install_platform
self._install_android_ndk()
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/targets/android.py", line 394, in _install_android_ndk
cwd=self.buildozer.global_platform_dir)
File "/usr/local/lib/python3.6/dist-packages/buildozer-0.40.dev0-py3.6.egg/buildozer/init.py", line 707, in download
urlretrieve(url, filename, report_hook)
File "/usr/lib/python3.6/urllib/request.py", line 1819, in retrieve
block = fp.read(bs)
File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
return func(*args, **kwargs)
File "/usr/lib/python3.6/http/client.py", line 449, in read
n = self.readinto(b)
File "/usr/lib/python3.6/http/client.py", line 493, in readinto
n = self.fp.readinto(b)
File "/usr/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
return self.read(nbytes, buffer)
File "/usr/lib/python3.6/ssl.py", line 874, in read
return self._sslobj.read(len, buffer)
File "/usr/lib/python3.6/ssl.py", line 631, in read
v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2292)
i have tryed it a number of time but keep getting the same thing.

**Comment by tshirtman** [comment]
weird, it seems like a server error, if you clicked on that link at that moment, did it work? (https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip) if it works now, can you retry the command?

**Comment by AndreMiras** [comment]
Definitely seems like a mac installation issue
