### ISSUE TITLE
host=arm-linux-androideabi

### ISSUE THREAD

**Issue by Abecedariann** [kivy/buildozer#884]
### Versions

* Python:2.7
* OS:Raspberry 
* Buildozer:

### Description

The  Raspberry has no 'arm-linux-androideabi',only arm-linux-gnueabihf.
When i install arm-linux-androideabi,it has a problem:cannot execute binary file: Exec format error.
So the Raspberry doesn't support arm-linux-androideabi.
And how can i do?

### Logs

```

Skipping hostpython3 (3.7.1) build, as it has already been completed
[INFO]:    Building libffi for armeabi-v7a
[INFO]:    -> directory context /home/pi/Downloads/gui/a/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi
[INFO]:    -> running autoreconf -vif
           working: autoreconf: running: automake --add-missing --copy --force-miss[INFO]:    -> running configure --host=arm-linux-androideabi --prefix=/home/pi/D...(and 143 more)
  Exception in thread background thread for pid 15403: nested variables... yes                             
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/pi/.local/lib/python2.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/pi/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_77: 

```

**Comment by inclement** [comment]
The arm-linux-androideabi should come from the Android NDK. It sounds like your ndk environment is not set up correctly. Probably this requires some effort on the rpi, as I don't think Google support it, although I've heard that it's possible.
