### ISSUE TITLE
Error with build requirements PIL (Python 3)

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/buildozer#890]
### Versions

* Python: 3
* OS: Mac OS
* Buildozer: 

### Description

Error with build requirements PIL (Python 3)

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

title = KivyMD Kitchen Sink
package.name = kitchen_sink
package.domain = org.kivymd
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
version = 0.98.1
requirements = python3,kivy,pil,android,git+https://github.com/HeaTTheatR/KivyMD.git
presplash.filename = %(source.dir)s/assets/presplash.png
android.presplash_color = #FFFFFF
icon.filename = %(source.dir)s/assets/kivy-logo-white-512.png
orientation = portrait
fullscreen = 1
android.permissions = INTERNET
android.api = 27
android.minapi = 21
android.ndk = 17c
android.ndk_path =/home/kivy/.buildozer/android/platform/android-ndk-r17c
android.sdk_path = /home/kivy/.buildozer/android/platform/android-sdk
android.ant_path =/home/kivy/.buildozer/android/platform/apache-ant-1.9.4

[buildozer]
log_level = 2
warn_on_root = 0

```

### Logs
```python
[INFO]:    Building compiled components in pil
[INFO]:    -> directory context /home/kivy/Downloads/.buildozer/android/platform/build/build/other_builds/pil-python3/armeabi-v7a__ndk_target_21/pil
[INFO]:    -> running python setup.py build_ext -v
Exception in thread background thread for pid 18648:                                                          
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/kivy/Downloads/.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
  File "setup.py", line 159
    print "--- using Tcl/Tk libraries at", TCL_ROOT
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("--- using Tcl/Tk libraries at", TCL_ROOT)?
?
```

**Comment by HeaTTheatR** [comment]
In /home/kivy/Downloads/.buildozer/android/platform/build/build/other_builds/pil-python3/armeabi-v7a__ndk_target_21/pil/setup.py:

```python
                if os.path.isfile(os.path.join(TCL_ROOT, "include", "tk.h")):
                    # FIXME: use distutils logging (?)
                    print "--- using Tcl/Tk libraries at", TCL_ROOT
                    print "--- using Tcl/Tk version", TCL_VERSION
```

**Comment by HeaTTheatR** [comment]
Use requirements = python3, kivy, pillow ...(not pil)
