### ISSUE TITLE
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size,

### ISSUE THREAD

**Issue by mcroni** [kivy/buildozer#900]
```
[INFO]:    <- directory context /home/mcroni/.buildozer/android/platform/python-for-android
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/mcroni/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/mcroni/.buildozer/android/platform/python-for-android
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /home/mcroni/.buildozer/android/platform/build/build/other_builds/six-python3/armeabi-v7a__ndk_target_21/six
[INFO]:    -> running python setup.py install -O2 --root=/home/mcroni/.buildozer/android/...(and 58 more)
[INFO]:    <- directory context /home/mcroni/.buildozer/android/platform/python-for-android
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    jnius apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in pyjnius
[INFO]:    -> directory context /home/mcroni/.buildozer/android/platform/build/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21/pyjnius
[INFO]:    -> running python -c import sys; print(sys.path)
[INFO]:    Trying first build of pyjnius to get cython files: this is expected to fail
[INFO]:    -> running python setup.py build_ext -v
Exception in thread background thread for pid 29969:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/mcroni/.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
/home/mcroni/.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/Lib/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/jnius
arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/mcroni/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/mcroni/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/mcroni/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/mcroni/.buildozer/android/platform/build/build/python-installs/myapp/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/mcroni/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/mcroni/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/mcroni/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/mcroni/.buildozer/android/platform/build/build/python-installs/myapp/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/home/mcroni/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -fPIC -I/home/mcroni/.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/mcroni/.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build -c jnius/jnius.c -o build/temp.linux-x86_64-3.7/jnius/jnius.o
arm-linux-androideabi-gcc: error: jnius/jnius.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
error: command 'arm-linux-androideabi-gcc' failed with exit status 1


  STDERR:


[INFO]:    pyjnius first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize jnius/jnius.pyx
[INFO]:    -> running cython ./jnius/jnius.pyx

Exception in thread background thread for pid 29976:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/mcroni/.local/bin/cython ./jnius/jnius.pyx

  STDOUT:
Traceback (most recent call last):
  File "/home/mcroni/.local/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 748, in compile_multiple
    context = options.create_context()
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing (/tmp/pip-1qm2aaj1-build/Cython/Compiler/Parsing.c:67386)
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1186, in <module>
    main()
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1180, in main
    ToolchainCL()
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 663, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 152, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 205, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 558, in build_recipes
    recipe.build_arch(arch)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 986, in build_arch
    self.build_cython_components(arch)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1011, in build_cython_components
    self.cythonize_build(env=env)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1061, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1052, in cythonize_file
    shprint(cython_command, filename, *self.cython_args, _env=cyenv)
  File "/home/mcroni/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 178, in shprint
    for line in output:
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/mcroni/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/mcroni/.local/bin/cython ./jnius/jnius.pyx

  STDOUT:
Traceback (most recent call last):
  File "/home/mcroni/.local/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 748, in compile_multiple
    context = options.create_context()
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/mcroni/.local/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing (/tmp/pip-1qm2aaj1-build/Cython/Compiler/Parsing.c:67386)
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
```
Edit: @AndreMiras added back quoting for readability

**Comment by inclement** [comment]
Interesting, this one is new to me and I don't know what's wrong. I'll see if I can reproduce in a clean VM.

**Comment by mcroni** [comment]
Got this from windows WSL

**Comment by hvitis** [comment]
I get the same error on Ubuntu 18
