### ISSUE TITLE
Couldn't find a virtualenv executable

### ISSUE THREAD

**Issue by Valmadson** [kivy/buildozer#925]
### Versions

* Python:3.6.5
* OS: Ubuntu 18.04.2 LTS
* Buildozer: 0.40.dev0

The error is in .spec?

### buildozer.spec

[app]
title = My App
package.name = exp1Pack
package.domain = org.test
p4a.branch = master
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1.2
requirements = python3,kivy            
orientation = portrait
android.arch = armeabi-v7a
osx.python_version = 3.6
osx.kivy_version = 1.10.0
fullscreen = 0
android.api = 28
android.minapi = 21
android.sdk = 24
android.ndk = 17c
log_level = 2

Command:
    buildozer -v android  debug

### Logs

# Downloading platform api target if necessary
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/home/linux/anaconda352/bin/python -m pythonforandroid.toolchain create --dist_name=exp1Pack --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/linux/exp1/.buildozer/android/platform/build" --ndk-api=21'
# Cwd /home/linux/exp1/.buildozer/android/platform/python-for-android
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 28
[INFO]:    Available Android APIs are (27, 28)
[INFO]:    Requested API target 28 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /home/linux/.buildozer/android/platform/android-ndk-r17c
[INFO]:    Found NDK revision 17.2.4988734
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
Traceback (most recent call last):
  File "/home/linux/anaconda352/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/linux/anaconda352/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/linux/exp1/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1186, in <module>
    main()
  File "/home/linux/exp1/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1180, in main
    ToolchainCL()
  File "/home/linux/exp1/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 663, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/linux/exp1/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 145, in wrapper_func
    user_ndk_api=self.ndk_api)
  File "/home/linux/exp1/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 318, in prepare_build_environment
    raise IOError('Couldn\'t find a virtualenv executable, '
OSError: Couldn't find a virtualenv executable, you must install this to use p4a.

**Comment by Felipe738743872** [comment]
Isso funcionou para mim

pip3 install --upgrade cython virtualenv
