### ISSUE TITLE
help command fails with `TypeError: join() argument must be str or bytes, not 'NoneType'`

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/buildozer#930]
### Versions

* Python: 3.6.8
* OS: Ubuntu 18.04
* Buildozer: 0.39

### Description
Help command fails with error: "TypeError: join() argument must be str or bytes, not 'NoneType'"
### buildozer.spec
Command:
buildozer help

Spec file: N/A

### Logs

```
Usage:
    buildozer [--profile <name>] [--verbose] [target] <command>...
    buildozer --version

Available targets:
  android            Android target, based on python-for-android project (old toolchain)

Global commands (without target):
  distclean          Clean the whole Buildozer environment.
  help               Show the Buildozer help.
  init               Create a initial buildozer.spec in the current directory
  serve              Serve the bin directory via SimpleHTTPServer
  setdefault         Set the default command to run when no arguments are given
  version            Show the Buildozer version

Target commands:
  clean      Clean the target environment
  update     Update the target dependencies
  debug      Build the application in debug mode
  release    Build the application in release mode
  deploy     Deploy the application on the device
  run        Run the application on the device
  serve      Serve the bin directory via SimpleHTTPServer
Traceback (most recent call last):
  File "/home/jra/.local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 1034, in run_command
    getattr(self, cmd)(*args)
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 1095, in cmd_help
    self.usage()
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 976, in usage
    mt = m.get_target(self)
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/targets/android.py", line 1228, in get_target
    return TargetAndroid(buildozer)
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/targets/android.py", line 59, in __init__
    self._build_dir = join(self.buildozer.platform_dir, 'build')
  File "/home/jra/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 878, in platform_dir
    return join(self.buildozer_dir, self.targetname, 'platform')
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

```

**Comment by avour** [comment]
This also happens to me on
    Python: 3.6.8
    OS: Arch Linux

**Comment by AndreMiras** [comment]
I think this is a dup of https://github.com/kivy/buildozer/issues/813 and got fixed in https://github.com/kivy/buildozer/pull/821
