### ISSUE TITLE
error ocurred

### ISSUE THREAD

**Issue by COIN-KR** [kivy/buildozer#964]
### Versions

* Python: 3.7
* OS: Ubuntu 18.04 lts
* Buildozer: latest

### Description

Error ocurred

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
didn't edit
```

### Logs

```
[INFO]:    -> directory context /home/coin/ubuntu/testkivy/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3/jni
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1192, in <module>
    main()
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 668, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 206, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 563, in build_recipes
    recipe.prepare_build_dir(arch.arch)
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 510, in prepare_build_dir
    self.unpack(arch)
  File "/home/coin/ubuntu/testkivy/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 409, in unpack
    sh.tar('xf', extraction_filename)
  File "/home/coin/.local/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/coin/.local/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/coin/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/coin/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /bin/tar xf /home/coin/ubuntu/testkivy/.buildozer/android/platform/build/packages/sdl2_image/SDL2_image-2.0.4.tar.gz

  STDOUT:


  STDERR:
/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/Resources: `Versions/Current/Resources'의 심볼릭 링크를 만들 수 없습니다: 명령을 허용하지 않음
/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/webp: `Versions/Current/webp'의 심볼릭 링크를 만들 수 없습니다: 명령을 허용하지 않음
/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/Headers: `Versions/Current/Headers'의 심볼릭 링크를 만들 수 없습니다: 명령을 허용하지 않음
/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/Versions/Current: `A'의 심볼릭 링크를 만들 수 없습니다: 명령을 허용하지 않음
/bin/tar: 앞서 발생한 오류로 실패 코드를 반환하며 빠져나감

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/coin/ubuntu/testkivy/.buildozer/android/platform/build" --ndk-api=21
# ENVIRONMENT:
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     LANG = 'ko_KR.UTF-8'
#     SUDO_GID = '1000'
#     DISPLAY = ':0'
#     OLDPWD = '/home/coin/ubuntu'
#     COLORTERM = 'truecolor'
#     USERNAME = 'root'
#     SUDO_COMMAND = '/bin/bash'
#     USER = 'root'
#     PWD = '/home/coin/ubuntu/testkivy'
#     HOME = '/home/coin'
#     SUDO_USER = 'coin'
#     SUDO_UID = '1000'
#     MAIL = '/var/mail/root'
#     SHELL = '/bin/bash'
#     TERM = 'xterm-256color'
#     SHLVL = '1'
#     LOGNAME = 'root'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     PATH = '/home/coin/.buildozer/android/platform/apache-ant-1.9.4/bin:/user/coin/Anaconda3/bin:/home/coin/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/home/coin/.buildozer/android/packages'
#     ANDROIDSDK = '/home/coin/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/coin/.buildozer/android/platform/android-ndk-r17c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by AndreMiras** [comment]
Try to debug manually to see what's the output.
So basically this error:
```
  RAN: /bin/tar xf /home/coin/ubuntu/testkivy/.buildozer/android/platform/build/packages/sdl2_image/SDL2_image-2.0.4.tar.gz
```
You want to run the tar command manually on the same file to see what the output is.

**Comment by AndreMiras** [comment]
Closing as stale, feel free to re-open providing the information requested
