### ISSUE TITLE
Buildozer almost completes and then errors saying file exists

### ISSUE THREAD

**Issue by itwageslave** [kivy/buildozer#99]
```
OSError: [Errno 17] File exists

# Copy /home/finn/PycharmProjects/kivy_android/2048-master/libs/google-play-services_lib/res/drawable-xxhdpi/ic_plusone_standard_off_client.png
# Copy /home/finn/PycharmProjects/kivy_android/2048-master/libs/google-play-services_lib/res/drawable-xxhdpi/ic_plusone_tall_off_client.png
Traceback (most recent call last):
  File "/usr/bin/buildozer", line 5, in <module>
    run()
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 1258, in run
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 885, in run_command
    self.target.run_commands(args)
  File "/usr/lib/python2.7/site-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/usr/lib/python2.7/site-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 178, in build
    self.build_application()
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 599, in build_application
    self._copy_garden_libs()
  File "/usr/lib/python2.7/site-packages/buildozer/__init__.py", line 689, in _copy_garden_libs
    copytree(self.gardenlibs_dir, join(self.app_dir, 'libs'))
  File "/usr/lib64/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/finn/PycharmProjects/kivy_android/2048-master/.buildozer/android/app/libs'
```

**Comment by abrarisme** [comment]
I'm getting the same error. This is happening on both versions 0.31 and 0.32dev.
