### ISSUE TITLE
Can't make an APK via Buildozer : clang++ error

### ISSUE THREAD

**Issue by AlexGr53** [kivy/buildozer#991]
### Versions

* Python: 3.7.2
* OS: Catalina 10.15.1
* Buildozer: 0.40

### Description

Hello, I'm trying to make an APK via buildozer. I still get the same error and I've been looking for several days now without an answer... I've done all the subjects already existing...

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = libffi,python3,kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.jpg

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
/Users/alex/.buildozer/android/platform/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpython3.7m
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:47: error: undefined reference to 'PyModule_Create2'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:154: error: undefined reference to 'Py_SetProgramName'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:160: error: undefined reference to 'PyImport_AppendInittab'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:181: error: undefined reference to 'Py_DecodeLocale'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:182: error: undefined reference to 'Py_SetPath'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:191: error: undefined reference to 'Py_Initialize'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:208: error: undefined reference to 'PyEval_InitThreads'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:214: error: undefined reference to 'PyRun_SimpleStringFlags'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:220: error: undefined reference to 'PyRun_SimpleStringFlags'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:229: error: undefined reference to 'PyRun_SimpleStringFlags'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:232: error: undefined reference to 'PyRun_SimpleStringFlags'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:326: error: undefined reference to 'PyRun_SimpleFileExFlags'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:329: error: undefined reference to 'PyErr_Occurred'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:331: error: undefined reference to 'PyErr_Print'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:332: error: undefined reference to 'PySys_GetObject'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:333: error: undefined reference to 'PyFile_WriteString'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:335: error: undefined reference to 'PyErr_Clear'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:362: error: undefined reference to 'Py_FinalizeEx'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:31: error: undefined reference to '_PyArg_ParseTuple_SizeT'
/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/start.c:0: error: undefined reference to '_Py_NoneStruct'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/obj/local/armeabi-v7a/libmain.so] Error 1


  STDERR:

# Command failed: /usr/local/opt/python/bin/python3.7 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=libffi,python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     TMPDIR = '/var/folders/tk/lhf48mld03vfm1mxcn13htw40000gn/T/'
#     XPC_FLAGS = '0x0'
#     TERM_PROGRAM_VERSION = '433'
#     LANG = 'fr_FR.UTF-8'
#     TERM_PROGRAM = 'Apple_Terminal'
#     XPC_SERVICE_NAME = '0'
#     TERM_SESSION_ID = '772E8DAB-2253-414D-ABB8-F4F378899744'
#     TERM = 'xterm-256color'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.P4zzw7TZXg/Listeners'
#     SHELL = '/bin/zsh'
#     HOME = '/Users/alex'
#     LOGNAME = 'alex'
#     USER = 'alex'
#     PATH = '/Users/alex/.buildozer/android/platform/apache-ant-1.9.4/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands'
#     SHLVL = '1'
#     PWD = '/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test'
#     OLDPWD = '/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/build'
#     _ = '/usr/local/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x1'
#     __PYVENV_LAUNCHER__ = '/usr/local/bin/python3'
#     PACKAGES_PATH = '/Users/alex/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/alex/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/alex/.buildozer/android/platform/android-ndk-r17c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by AndreMiras** [comment]
try with `p4a.branch = master` and delete your `~/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/` dir before re-running

**Comment by AlexGr53** [comment]
Thank you for your help!  I get this message: `zsh: command not found: p4a.branch`

**Comment by AndreMiras** [comment]
Sorry I meant in your `buildozer.spec` to update `p4a.branch` and actually put `develop` rather than `master`

**Comment by AlexGr53** [comment]
I did what you told me and it looks better, but I have a new error message :

`[INFO]:    Saving distribution info
[INFO]:    <- directory context /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/python-for-android
[INFO]:    # Your distribution was created successfully, exiting.
[INFO]:    Dist can be found at (for now) /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a
# Build the application #1
# Copy application source from /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test
# Create directory /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/app
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/icone.jpg
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/Croix.png
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/novastep.jpg
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/main.py
# Create directory /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/app/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/symlink_to_empty_file
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/non_empty_file
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/bad_symlink
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.40.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 1071, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 211, in build
    self.build_application()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 738, in build_application
    self._copy_application_sources()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 835, in _copy_application_sources
    copyfile(sfn, rfn)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/bad_symlink'`

I checked and the file is in the indicated path...

**Comment by AlexGr53** [comment]
I did what you told me and it looks better, but I have a new error message : 

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/bad_symlink'`

I checked and the file is in the indicated path.

**Comment by AlexGr53** [comment]
`/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:85: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 27
[INFO]:    Available Android APIs are (27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /Users/alex/.buildozer/android/platform/android-ndk-r19b
[INFO]:    Found NDK version 19b
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	myapp: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy), built for archs (armeabi-v7a)
[INFO]:    myapp has compatible recipes, using this one
# Build the application #4
# Copy application source from /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test
# Create directory /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/app
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/icone.jpg
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/Croix.png
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/novastep.jpg
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/main.py
# Create directory /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/.buildozer/android/app/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/symlink_to_empty_file
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/non_empty_file
# Copy /Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/bad_symlink
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.40.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 1071, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 211, in build
    self.build_application()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 738, in build_application
    self._copy_application_sources()
  File "/usr/local/lib/python3.7/site-packages/buildozer-0.40.dev0-py3.7.egg/buildozer/__init__.py", line 835, in _copy_application_sources
    copyfile(sfn, rfn)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alex/Documents/Cours/Novastep/Programmation/Interface/Test/llvm-project/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/bad_symlink'`

**Comment by AndreMiras** [comment]
We made some improvements for macOS recently. Also it's now part of our CI and seems to be working.
Feel free to try again on recent buildozer version and update the issue with new findings
